Repository DevCloudFE/vue-devui, pull requests merged in 2021-12, with the labels that each got.

#2 fix: fix accordion md dead link error
  README.md
  packages/devui-vue/docs/.vitepress/devui-theme/components/NavBar.vue
  packages/devui-vue/docs/components/accordion/index.md
  yarn.lock
Labels: PR: unreviewed

#3 docs: update README and releases link
  README.md
  packages/devui-vue/README.md
  packages/devui-vue/docs/.vitepress/config/enNav.ts
  packages/devui-vue/docs/.vitepress/config/nav.ts
  packages/devui-vue/docs/.vitepress/devui-theme/components/NavBar.vue
  packages/devui-vue/package.json
Labels: PR: unreviewed

#9 【Button】Add new style, 'success' & 'warning'
  packages/devui-vue/devui/button/src/button-types.ts
  packages/devui-vue/devui/button/src/button.scss
  packages/devui-vue/devui/style/theme/_color.scss
  packages/devui-vue/docs/components/button/index.md
Labels: PR: reviewed-approved

#15 【alert】修复alert设置dismissTimer后提前点击close报错，空样式等问题。
  packages/devui-vue/devui/alert/src/alert.tsx
Labels: PR: reviewed-approved

#10 feat(toast): add toast file
  packages/devui-vue/devui/toast/__tests__/toast.spec.ts
Labels: PR: reviewed-approved

#16 fix: Markdown-列表语法导致的样式错乱
  packages/devui-vue/docs/components/avatar/index.md
  packages/devui-vue/docs/components/form/index.md
  packages/devui-vue/docs/components/gantt/index.md
  packages/devui-vue/docs/components/input-icon/index.md
Labels: PR: reviewed-approved

#18 chroe: Added `Bug` and `Feature` issue templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: PR: reviewed-approved

#14 fix(editable-select): rename keyBoard to keyboard
  packages/devui-vue/devui/editable-select/src/composable/use-keyboard-select.ts
Labels: PR: reviewed-approved

#11 fix(TimePicker): 修改滚动条bug和完善时间限制
  packages/devui-vue/devui/time-picker/src/components/time-scroll/composables/use-time-scroll.ts
  packages/devui-vue/devui/time-picker/src/composables/use-time-picker.ts
Labels: PR: reviewed-approved

#17 【Dropdown】添加自定义宽度的功能
  packages/devui-vue/devui/dropdown/src/dropdown-types.ts
  packages/devui-vue/devui/dropdown/src/dropdown.scss
  packages/devui-vue/devui/dropdown/src/dropdown.tsx
  packages/devui-vue/docs/components/dropdown/index.md
Labels: PR: reviewed-approved

#28 fix: flexibleOverlay修复backdropClick错误
  packages/devui-vue/devui/overlay/src/flexible-overlay.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved

#25 feat(tooltip): add test file
  packages/devui-vue/devui/tooltip/__tests__/tooltip.spec.ts
Labels: PR: reviewed-approved

#22 feat(overlay): add test file
  packages/devui-vue/devui/overlay/__tests__/overlay.spec.ts
Labels: PR: reviewed-approved

#21 【imagePreview】disableDefault支持动态修改,修复md文档中的错误
  packages/devui-vue/devui/image-preview/src/image-preview-directive.ts
  packages/devui-vue/devui/image-preview/src/image-preview-types.ts
  packages/devui-vue/docs/components/image-preview/index.md
Labels: PR: reviewed-approved

#20 fix: 修复git钩子校验
  .eslintrc.js
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .ls-lint.yml
  .stylelintrc.json
  commitlint.config.js
  package.json
  packages/devui-vue/.husky/commit-msg
  packages/devui-vue/.husky/pre-commit
  packages/devui-vue/package.json
Labels: PR: partially-approved

#26 feat(colorPicker): new add colorPicker Component Full version available
  packages/devui-vue/devui/color-picker/__tests__/color-picker.spec.ts
  packages/devui-vue/devui/color-picker/index.ts
  packages/devui-vue/devui/color-picker/src/color-picker-types.ts
  packages/devui-vue/devui/color-picker/src/color-picker.scss
  packages/devui-vue/devui/color-picker/src/color-picker.tsx
  packages/devui-vue/devui/color-picker/src/components/color-alpha-slider/color-alpha-slider.scss
  packages/devui-vue/devui/color-picker/src/components/color-alpha-slider/color-alpha-slider.tsx
  packages/devui-vue/devui/color-picker/src/components/color-alpha-slider/color-picker-alpha-slider-types.ts
  packages/devui-vue/devui/color-picker/src/components/color-basic/color-basic-types.ts
  packages/devui-vue/devui/color-picker/src/components/color-basic/color-basic.scss
  packages/devui-vue/devui/color-picker/src/components/color-basic/color-basic.tsx
  packages/devui-vue/devui/color-picker/src/components/color-edit/color-edit.scss
  packages/devui-vue/devui/color-picker/src/components/color-edit/color-edit.tsx
  packages/devui-vue/devui/color-picker/src/components/color-edit/color-picker-edit-types.ts
  packages/devui-vue/devui/color-picker/src/components/color-history/color-history.scss
  packages/devui-vue/devui/color-picker/src/components/color-history/color-history.tsx
  packages/devui-vue/devui/color-picker/src/components/color-history/color-picker-history-types.ts
  packages/devui-vue/devui/color-picker/src/components/color-hue-slider/color-hue-slider.scss
  packages/devui-vue/devui/color-picker/src/components/color-hue-slider/color-hue-slider.tsx
  packages/devui-vue/devui/color-picker/src/components/color-hue-slider/color-picker-hue-slider-types.ts
  packages/devui-vue/devui/color-picker/src/components/color-palette/color-palette.scss
  packages/devui-vue/devui/color-picker/src/components/color-palette/color-palette.tsx
  packages/devui-vue/devui/color-picker/src/components/color-palette/color-picker-palette-types.ts
  packages/devui-vue/devui/color-picker/src/components/color-picker-panel/color-picker-panel-types.ts
  packages/devui-vue/devui/color-picker/src/components/color-picker-panel/color-picker-panel.scss
  packages/devui-vue/devui/color-picker/src/components/color-picker-panel/color-picker-panel.tsx
  packages/devui-vue/devui/color-picker/src/utils/color-utils-types.ts
  packages/devui-vue/devui/color-picker/src/utils/color-utils.ts
  packages/devui-vue/devui/color-picker/src/utils/color.ts
  packages/devui-vue/devui/color-picker/src/utils/composeable.ts
  packages/devui-vue/devui/color-picker/src/utils/domDragger.ts
  packages/devui-vue/devui/color-picker/src/utils/helpers.ts
  packages/devui-vue/docs/components/color-picker/index.md
Labels: PR: reviewed-approved, feature

#34 fix(button): 修复success按钮hover状态颜色错误的问题
  packages/devui-vue/devui/style/theme/_color.scss
Labels: PR: reviewed-approved

#49 fix(ripple): ripple文档 优化 css泄露问题
  packages/devui-vue/docs/components/ripple/index.md
  packages/devui-vue/docs/en-US/components/ripple/index.md
Labels: PR: reviewed-approved

#48 chore: add Github Action Sync to Gitee
  .github/workflows/sync-gitee.yml
  CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.zh-CN.md
Labels: PR: reviewed-approved

#47 fix: del global style pollution in accordion
  packages/devui-vue/devui/accordion/src/accordion.scss
Labels: PR: reviewed-approved

#46 chore: update ISSUE_TEMPLATE config
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: PR: reviewed-approved

#45 docs: add doc CONTRIBUTING.md
  CONTRIBUTING.md
  packages/devui-vue/docs/.vitepress/config/nav.ts
  packages/devui-vue/docs/CONTRIBUTING.md
Labels: PR: reviewed-approved

#43 Add allcontributors reboot to generate list of contributors
  .all-contributorsrc
  README.md
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#40 fix(splitter): 修复 collasped api 不起作用的问题、添加英文文档
  packages/devui-vue/devui/splitter/src/splitter-bar.tsx
  packages/devui-vue/devui/splitter/src/splitter-pane.tsx
  packages/devui-vue/docs/en-US/components/splitter/index.md
Labels: PR: reviewed-approved

#52 docs: README 贡献者名单异常
  README.md
Labels: PR: reviewed-approved

#36 fix(modal & button): dLoading 需要单独引入 & 默认点击背景可以 modal 关闭
  packages/devui-vue/devui/button/src/button.tsx
  packages/devui-vue/devui/modal/src/dialog-types.ts
  packages/devui-vue/devui/modal/src/modal-types.ts
  packages/devui-vue/devui/modal/src/modal.tsx
Labels: PR: reviewed-approved

#54 fix: read-tip icon样式泄露
  packages/devui-vue/docs/components/card/index.md
  packages/devui-vue/docs/components/read-tip/index.md
  packages/devui-vue/docs/en-US/components/read-tip/index.md
Labels: PR: reviewed-approved

#57 Fix(Panel): 修复了单元测试文件不通过问题
  packages/devui-vue/devui/panel/__tests__/panel.spec.ts
Labels: PR: reviewed-approved, unit test

#59 fix(ISSUE_TEMPLATE): 无法自动选中对应标签
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: PR: reviewed-approved

#65 feat: add scss preprocessor in docs && fix:(Toast) single lifeMode bug in Toast
  packages/devui-vue/devui/toast/src/hooks/use-toast-helper.ts
  packages/devui-vue/devui/toast/src/toast.tsx
  packages/devui-vue/docs/.vitepress/config/markdown.ts
  packages/devui-vue/docs/components/card/index.md
  packages/devui-vue/docs/components/pagination/index.md
Labels: PR: reviewed-approved

#66 fix(button): 修复文档中存在的问题
  packages/devui-vue/docs/components/button/index.md
Labels: PR: reviewed-approved

#60 fix(color-picker): 优化palette拖拽效果
  packages/devui-vue/devui/color-picker/src/components/color-palette/color-palette.tsx
  packages/devui-vue/devui/color-picker/src/utils/domDragger.ts
Labels: PR: reviewed-approved

#27 feat(drawer): add service model
  packages/devui-vue/devui/drawer/index.ts
  packages/devui-vue/devui/drawer/src/drawer-service.ts
  packages/devui-vue/devui/drawer/src/drawer.tsx
  packages/devui-vue/docs/components/drawer/index.md
Labels: PR: reviewed-approved, ✨ feature

#98 【Form】fix: 修复重置数组类型的值不正确问题
  packages/devui-vue/devui/form/src/form-item/form-item.tsx
Labels: PR: reviewed-approved

#93 fix(slider): 完成组件自检清单，修复输入框限制问题和最小值样式问题
  packages/devui-vue/devui/slider/src/slider.scss
  packages/devui-vue/devui/slider/src/slider.tsx
Labels: PR: reviewed-approved

#99 Popover增加controlled属性
  packages/devui-vue/devui/popover/__tests__/popover.spec.ts
  packages/devui-vue/devui/popover/src/popover.tsx
  packages/devui-vue/docs/components/popover/index.md
  packages/devui-vue/docs/en-US/components/popover/index.md
Labels: PR: reviewed-approved

#101 实现dragdrop指令基础用法
  packages/devui-vue/devui/dragdrop/index.ts
  packages/devui-vue/devui/dragdrop/src/constant.ts
  packages/devui-vue/devui/dragdrop/src/draggable-directive.ts
  packages/devui-vue/devui/dragdrop/src/droppable-directive.ts
  packages/devui-vue/devui/dragdrop/src/sortable-directive.ts
  packages/devui-vue/devui/dragdrop/src/utils.ts
  packages/devui-vue/docs/components/dragdrop/index.md
Labels: PR: reviewed-approved

#103 feat(button): btnStyle 更名为 variant
  packages/devui-vue/devui/button/__tests__/button.spec.ts
  packages/devui-vue/devui/button/src/button-types.ts
  packages/devui-vue/devui/button/src/button.tsx
  packages/devui-vue/devui/gantt/src/gantt-tools/index.tsx
  packages/devui-vue/devui/modal/src/dialog-types.ts
  packages/devui-vue/devui/modal/src/dialog.tsx
  packages/devui-vue/devui/time-picker/src/components/time-popup/index.tsx
  packages/devui-vue/devui/tooltip/__tests__/tooltip.spec.ts
  packages/devui-vue/devui/upload/src/single-upload.tsx
  packages/devui-vue/devui/upload/src/upload.tsx
  packages/devui-vue/docs/components/button/index.md
  packages/devui-vue/docs/components/color-picker/index.md
  packages/devui-vue/docs/components/modal/index.md
  packages/devui-vue/docs/components/popover/index.md
  packages/devui-vue/docs/components/ripple/index.md
  packages/devui-vue/docs/components/steps-guide/index.md
  packages/devui-vue/docs/components/toast/index.md
  packages/devui-vue/docs/components/tooltip/index.md
  packages/devui-vue/docs/en-US/components/popover/index.md
  packages/devui-vue/docs/en-US/components/ripple/index.md
  packages/devui-vue/docs/en-US/components/tooltip/index.md
Labels: PR: reviewed-approved

#124 feat(auto-complete): 新增auto-complete组件
  packages/devui-vue/devui/auto-complete/__tests__/auto-complete.spec.ts
  packages/devui-vue/devui/auto-complete/index.ts
  packages/devui-vue/devui/auto-complete/src/auto-complete-types.ts
  packages/devui-vue/devui/auto-complete/src/auto-complete.scss
  packages/devui-vue/devui/auto-complete/src/auto-complete.tsx
  packages/devui-vue/devui/auto-complete/src/components/dropdown.tsx
  packages/devui-vue/devui/auto-complete/src/composables/use-custom-template.ts
  packages/devui-vue/devui/auto-complete/src/composables/use-input-handle.ts
  packages/devui-vue/devui/auto-complete/src/composables/use-keyboard-select.ts
  packages/devui-vue/devui/auto-complete/src/composables/use-lazy-handle.ts
  packages/devui-vue/devui/auto-complete/src/composables/use-searchfn.ts
  packages/devui-vue/devui/auto-complete/src/composables/use-select-handle.ts
  packages/devui-vue/docs/components/auto-complete/index.md
  packages/devui-vue/docs/en-US/components/auto-complete/api-en.md
Labels: PR: reviewed-approved

#105 fix(docs): fix button demo
  packages/devui-vue/devui/drawer/src/drawer-service.ts
  packages/devui-vue/docs/components/button/index.md
Labels: PR: unreviewed

#106 fix: tree组件单元测试，tree组件folder部分嵌套div便于控制
  packages/devui-vue/devui/tree/__tests__/tree.spec.ts
  packages/devui-vue/devui/tree/src/tree.tsx
Labels: PR: reviewed-approved

#109 docs(color-picker): 优化文档api 格式 新增colorpicker 英文文档
  packages/devui-vue/docs/components/color-picker/index.md
  packages/devui-vue/docs/components/ripple/index.md
  packages/devui-vue/docs/components/statistic/index.md
  packages/devui-vue/docs/en-US/components/color-picker/index.md
  packages/devui-vue/docs/en-US/components/ripple/index.md
  packages/devui-vue/docs/en-US/components/statistic/index.md
Labels: PR: reviewed-approved

#123 docs(grid): 修改Grid组件文档问题 #63
  packages/devui-vue/docs/components/grid/index.md
Labels: PR: reviewed-approved
