Repository DevCloudFE/vue-devui, pull requests merged in 2022-05, with the labels that each got.

#599 chore: 修复PageContributor警告信息
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributor.vue
Labels: PR: unreviewed

#601 refactor(Alert): 重构样式命名
  packages/devui-vue/devui/alert/src/alert.scss
  packages/devui-vue/devui/alert/src/alert.tsx
  packages/devui-vue/devui/alert/src/components/alert-type-icon.tsx
Labels: PR: unreviewed, refactoring

#600 refactor(Accordion): 重构样式命名
  packages/devui-vue/devui/accordion/src/accordion-item-hreflink.tsx
  packages/devui-vue/devui/accordion/src/accordion-item-routerlink.tsx
  packages/devui-vue/devui/accordion/src/accordion-item.tsx
  packages/devui-vue/devui/accordion/src/accordion-list.tsx
  packages/devui-vue/devui/accordion/src/accordion-menu.tsx
  packages/devui-vue/devui/accordion/src/accordion-open-icon.tsx
  packages/devui-vue/devui/accordion/src/accordion.scss
  packages/devui-vue/devui/accordion/src/accordion.tsx
  packages/devui-vue/docs/components/accordion/index.md
Labels: PR: unreviewed, refactoring

#602 refactor(AutoComplete): 重构样式命名
  packages/devui-vue/devui/auto-complete/src/auto-complete.scss
  packages/devui-vue/devui/auto-complete/src/auto-complete.tsx
  packages/devui-vue/devui/auto-complete/src/components/dropdown.tsx
Labels: PR: reviewed-approved, refactoring

#603 refactor(Avatar): 重构样式命名
  packages/devui-vue/devui/avatar/src/avatar.scss
  packages/devui-vue/devui/avatar/src/avatar.tsx
Labels: PR: reviewed-approved, refactoring

#604 refactor(BackTop): 重构样式命名
  packages/devui-vue/devui/back-top/src/back-top.scss
  packages/devui-vue/devui/back-top/src/back-top.tsx
Labels: PR: unreviewed, refactoring

#605 refactor(Badge): 重构样式命名
  packages/devui-vue/devui/badge/src/badge.scss
  packages/devui-vue/devui/badge/src/badge.tsx
Labels: PR: unreviewed, refactoring

#606 refactor(Breadcrumb): 重构样式命名
  packages/devui-vue/devui/breadcrumb/src/breadcrumb-item.scss
  packages/devui-vue/devui/breadcrumb/src/breadcrumb-item.tsx
  packages/devui-vue/devui/breadcrumb/src/breadcrumb.scss
  packages/devui-vue/devui/breadcrumb/src/breadcrumb.tsx
Labels: PR: unreviewed, refactoring

#607 refactor(Button): 重构样式命名
  packages/devui-vue/devui/button/src/button.scss
  packages/devui-vue/devui/button/src/use-button.ts
Labels: PR: unreviewed, refactoring

#608 refactor(Card): 重构样式命名
  packages/devui-vue/devui/card/src/card.scss
  packages/devui-vue/devui/card/src/card.tsx
Labels: PR: unreviewed, refactoring

#609 refactor(Carousel): 重构样式命名
  packages/devui-vue/devui/carousel/src/carousel.scss
  packages/devui-vue/devui/carousel/src/carousel.tsx
  packages/devui-vue/devui/carousel/src/item.tsx
  packages/devui-vue/docs/components/carousel/index.md
Labels: PR: unreviewed, refactoring

#610 refactor(Checkbox): 重构样式命名
  packages/devui-vue/devui/checkbox/src/checkbox.scss
  packages/devui-vue/devui/checkbox/src/checkbox.tsx
  packages/devui-vue/devui/input/src/composables/use-input-render.ts
Labels: PR: unreviewed, refactoring

#612 refactor(FullScreen): 重构样式命名
  packages/devui-vue/devui/fullscreen/src/fullscreen.scss
  packages/devui-vue/devui/fullscreen/src/utils.ts
Labels: PR: unreviewed, refactoring

#613 refactor(Overlay): 重构样式命名
  packages/devui-vue/devui/overlay/src/base-overlay.scss
  packages/devui-vue/devui/overlay/src/base-overlay.tsx
  packages/devui-vue/devui/overlay/src/fixed-overlay/fixed-overlay.scss
  packages/devui-vue/devui/overlay/src/fixed-overlay/use-fixed-overlay.ts
  packages/devui-vue/devui/overlay/src/flexible-overlay/flexible-overlay.scss
  packages/devui-vue/devui/overlay/src/flexible-overlay/index.tsx
Labels: PR: unreviewed, refactoring

#615 refactor(Search): 重构样式命名
  packages/devui-vue/devui/input/src/input.scss
  packages/devui-vue/devui/search/src/composables/use-search-class.ts
  packages/devui-vue/devui/search/src/search.scss
  packages/devui-vue/devui/search/src/search.tsx
Labels: PR: unreviewed, refactoring

#616 refactor(Radio): 重构样式命名
  packages/devui-vue/devui/radio/src/radio-group.tsx
  packages/devui-vue/devui/radio/src/radio.scss
  packages/devui-vue/devui/radio/src/radio.tsx
Labels: PR: unreviewed, refactoring

#617 refactor(Select): 重构样式命名
  packages/devui-vue/devui/select/src/select.scss
  packages/devui-vue/devui/select/src/select.tsx
Labels: PR: unreviewed, refactoring

#620 refactor(Textarea): 重构样式命名
  packages/devui-vue/devui/textarea/src/textarea.scss
  packages/devui-vue/devui/textarea/src/textarea.tsx
Labels: PR: unreviewed

#619 refactor(Switch): 重构样式命名
  packages/devui-vue/devui/switch/src/switch.scss
  packages/devui-vue/devui/switch/src/switch.tsx
Labels: PR: unreviewed, refactoring

#618 refactor(Slider): 重构样式命名
  packages/devui-vue/devui/slider/src/slider.scss
  packages/devui-vue/devui/slider/src/slider.tsx
Labels: PR: unreviewed, refactoring

#621 refactor(Upload): 重构样式命名
  packages/devui-vue/devui/upload/src/upload.scss
  packages/devui-vue/devui/upload/src/upload.tsx
Labels: PR: unreviewed, refactoring

#623 refactor(List): 重构样式命名
  packages/devui-vue/devui/list/src/list-item.scss
  packages/devui-vue/devui/list/src/list-item.tsx
  packages/devui-vue/devui/list/src/list.tsx
Labels: PR: unreviewed, refactoring

#622 refactor(ImagePreview): 重构样式命名
  packages/devui-vue/devui/image-preview/src/image-preview.scss
  packages/devui-vue/devui/image-preview/src/image-preview.tsx
Labels: PR: unreviewed, refactoring

#627 refactor(Accordion): 重构样式命名
  packages/devui-vue/devui/accordion/src/accordion.tsx
Labels: PR: unreviewed, refactoring

#626 refactor(Status): 重构样式命名
  packages/devui-vue/devui/status/src/status.scss
  packages/devui-vue/devui/status/src/status.tsx
Labels: PR: unreviewed, refactoring

#625 refactor(Skeleton): 重构样式命名
  packages/devui-vue/devui/skeleton/src/skeleton.tsx
Labels: PR: unreviewed, refactoring

#624 refactor(Rate): 重构样式命名
  packages/devui-vue/devui/rate/src/rate.scss
  packages/devui-vue/devui/rate/src/rate.tsx
Labels: PR: unreviewed, refactoring

#611 fix(Alert): icon 组件 ts 类型错误。
  packages/devui-vue/devui/alert/src/alert.tsx
  packages/devui-vue/devui/alert/src/components/alert-close-icon.tsx
  packages/devui-vue/devui/alert/src/components/alert-type-icon.tsx
Labels: PR: reviewed-approved, refactoring

#628 refactor(Tag): 重构样式命名
  packages/devui-vue/devui/tag/src/composables/use-class.ts
  packages/devui-vue/devui/tag/src/tag.scss
  packages/devui-vue/devui/tag/src/tag.tsx
Labels: PR: reviewed-approved, refactoring

#631 fix(AutoComplete): 修复重构样式带来的测试错误
  packages/devui-vue/devui/auto-complete/__tests__/auto-complete.spec.ts
Labels: PR: unreviewed

#633 fix(Avatar): 修复重构样式带来的测试错误
  packages/devui-vue/devui/avatar/__tests__/avatar.spec.ts
Labels: PR: unreviewed

#632 refactor(Tree): 重构样式命名
  packages/devui-vue/devui/tree/src/components/tree-node-toggle.tsx
  packages/devui-vue/devui/tree/src/components/tree-node.tsx
  packages/devui-vue/devui/tree/src/components/use-tree-node.ts
  packages/devui-vue/devui/tree/src/deprecated-composables/use-draggable.ts
  packages/devui-vue/devui/tree/src/deprecated-tree.tsx
  packages/devui-vue/devui/tree/src/tree-node-content.tsx
  packages/devui-vue/devui/tree/src/tree.scss
  packages/devui-vue/devui/tree/src/tree.tsx
Labels: PR: unreviewed, refactoring

#637 refactor(Grid): 重构样式命名
  packages/devui-vue/devui/grid/src/col.scss
  packages/devui-vue/devui/grid/src/col.tsx
  packages/devui-vue/devui/grid/src/composables/use-grid.ts
  packages/devui-vue/devui/grid/src/row.scss
  packages/devui-vue/devui/grid/src/row.tsx
Labels: PR: unreviewed, refactoring

#640 refactor(Drawer): 重构样式命名
  packages/devui-vue/devui/drawer/src/components/drawer-overlay.scss
  packages/devui-vue/devui/drawer/src/components/drawer-overlay.tsx
  packages/devui-vue/devui/drawer/src/drawer.scss
  packages/devui-vue/devui/drawer/src/use-drawer.ts
Labels: PR: unreviewed, refactoring

#641 refactor(Loading): 重构样式命名
  packages/devui-vue/devui/loading/__tests__/loading.spec.ts
  packages/devui-vue/devui/loading/src/loading.scss
  packages/devui-vue/devui/loading/src/loading.tsx
Labels: PR: unreviewed, refactoring

#642 refactor(Modal): 重构样式命名
  packages/devui-vue/devui/modal/src/components/body.tsx
  packages/devui-vue/devui/modal/src/components/footer.tsx
  packages/devui-vue/devui/modal/src/components/header.tsx
  packages/devui-vue/devui/modal/src/modal.scss
  packages/devui-vue/devui/modal/src/modal.tsx
Labels: PR: unreviewed, refactoring

#646 refactor(Tooltip): 重构样式命名
  packages/devui-vue/devui/tooltip/src/tooltip.scss
  packages/devui-vue/devui/tooltip/src/tooltip.tsx
Labels: PR: unreviewed

#645 refactor(Progress): 重构样式命名
  packages/devui-vue/devui/progress/src/progress.scss
  packages/devui-vue/devui/progress/src/progress.tsx
Labels: PR: unreviewed, refactoring

#644 refactor(Popover): 重构样式命名
  packages/devui-vue/devui/popover/src/popover-icon.scss
  packages/devui-vue/devui/popover/src/popover-icon.tsx
  packages/devui-vue/devui/popover/src/popover-icons.tsx
  packages/devui-vue/devui/popover/src/popover.scss
  packages/devui-vue/devui/popover/src/popover.tsx
Labels: PR: unreviewed, refactoring

#643 refactor(Notification): 重构样式命名
  packages/devui-vue/devui/notification/src/notification-icon-close.tsx
  packages/devui-vue/devui/notification/src/notification-icons.tsx
  packages/devui-vue/devui/notification/src/notification-image.tsx
  packages/devui-vue/devui/notification/src/notification.scss
  packages/devui-vue/devui/notification/src/notification.tsx
Labels: PR: unreviewed, refactoring

#649 refactor(Pagination): 重构样式命名
  packages/devui-vue/devui/pagination/src/components/config-menu.tsx
  packages/devui-vue/devui/pagination/src/components/jump-page.tsx
  packages/devui-vue/devui/pagination/src/components/page-nums.tsx
  packages/devui-vue/devui/pagination/src/pagination.scss
  packages/devui-vue/devui/pagination/src/pagination.tsx
Labels: PR: unreviewed, refactoring

#647 refactor(Dropdown): 重构样式命名
  packages/devui-vue/devui/dropdown/src/dropdown-menu.tsx
  packages/devui-vue/devui/dropdown/src/dropdown.scss
  packages/devui-vue/devui/dropdown/src/dropdown.tsx
Labels: PR: unreviewed, refactoring

#652 refactor(Layout): 重构样式命名
  packages/devui-vue/devui/layout/src/aside.tsx
  packages/devui-vue/devui/layout/src/content.scss
  packages/devui-vue/devui/layout/src/content.tsx
  packages/devui-vue/devui/layout/src/footer.scss
  packages/devui-vue/devui/layout/src/footer.tsx
  packages/devui-vue/devui/layout/src/header.scss
  packages/devui-vue/devui/layout/src/header.tsx
  packages/devui-vue/devui/layout/src/layout.scss
  packages/devui-vue/devui/layout/src/layout.tsx
Labels: PR: unreviewed, refactoring

#651 refactor(Tabs): 重构样式命名
  packages/devui-vue/devui/tabs/src/tab.tsx
  packages/devui-vue/devui/tabs/src/tabs.scss
  packages/devui-vue/devui/tabs/src/tabs.tsx
Labels: PR: unreviewed, refactoring

#650 refactor(StepsGuide): 重构样式命名
  packages/devui-vue/devui/steps-guide/src/steps-guide.scss
  packages/devui-vue/devui/steps-guide/src/steps-guide.tsx
Labels: PR: unreviewed, refactoring

#653 refactor(Splitter): 重构样式命名
  packages/devui-vue/devui/splitter/src/components/splitter-bar.scss
  packages/devui-vue/devui/splitter/src/components/splitter-bar.tsx
  packages/devui-vue/devui/splitter/src/components/splitter-pane.scss
  packages/devui-vue/devui/splitter/src/components/splitter-pane.tsx
  packages/devui-vue/devui/splitter/src/splitter.scss
  packages/devui-vue/devui/splitter/src/splitter.tsx
Labels: PR: unreviewed, refactoring

#663 fix(Modal): 移除样式前缀
  packages/devui-vue/devui/modal/src/modal.scss
  packages/devui-vue/devui/modal/src/modal.tsx
Labels: PR: unreviewed

#662 fix(Popover): 移除popover中的样式前缀
  packages/devui-vue/devui/popover/src/popover.scss
  packages/devui-vue/devui/popover/src/popover.tsx
Labels: bug

#661 style(Tabs): 动画采用样式变量&间距需为4的倍数
  packages/devui-vue/devui/tabs/src/tabs.scss
Labels: bug, PR: unreviewed

#664 refactor(Skeleton): 重构样式前缀
  packages/devui-vue/devui/skeleton/src/components/skeleton-item.scss
  packages/devui-vue/devui/skeleton/src/components/skeleton-item.tsx
Labels: PR: unreviewed

#666 fix(Select): 事采用中划线件命名
  packages/devui-vue/devui/select/src/select.tsx
Labels: PR: unreviewed

#665 style(Switch): 修复动画的样式变量
  packages/devui-vue/devui/switch/src/switch.scss
Labels: bug, PR: unreviewed

#614 feat: width过小时生成省略号并支持悬浮
  packages/devui-vue/devui/menu/src/components/menu-item.tsx
  packages/devui-vue/devui/menu/src/components/sub-menu.tsx
  packages/devui-vue/devui/menu/src/helper/add-active-parent.ts
  packages/devui-vue/devui/menu/src/helper/init-select.ts
  packages/devui-vue/devui/menu/src/helper/layer-composables.ts
  packages/devui-vue/devui/menu/src/hook/use-click.ts
  packages/devui-vue/devui/menu/src/hook/use-show-submenu.ts
  packages/devui-vue/devui/menu/src/menu.scss
  packages/devui-vue/devui/menu/src/menu.tsx
  packages/devui-vue/devui/menu/src/styles/horizontal.scss
  packages/devui-vue/devui/menu/src/styles/public.scss
  packages/devui-vue/devui/menu/src/styles/vertical.scss
  packages/devui-vue/docs/components/menu/index.md
Labels: PR: reviewed-approved, feature

#668 docs(rate): 优化rate组件文档
  packages/devui-vue/docs/components/rate/index.md
Labels: documentation, PR: unreviewed

#667 fix(Checkbox): 参数halfchecked改成half-checked
  packages/devui-vue/devui/checkbox/src/checkbox-group.tsx
  packages/devui-vue/devui/checkbox/src/checkbox-types.ts
  packages/devui-vue/devui/checkbox/src/checkbox.scss
  packages/devui-vue/devui/checkbox/src/checkbox.tsx
  packages/devui-vue/docs/components/checkbox/index.md
Labels: PR: unreviewed

#680 feat(Table): 支持配置空数据文本/模板
  packages/devui-vue/devui/table/__tests__/table.spec.tsx
  packages/devui-vue/devui/table/src/table-types.ts
  packages/devui-vue/devui/table/src/table.scss
  packages/devui-vue/devui/table/src/table.tsx
  packages/devui-vue/docs/components/table/index.md
Labels: PR: unreviewed, feature

#659 refactor(Alert): 抽离测试样式
  packages/devui-vue/devui/alert/__tests__/alert.spec.ts
  packages/devui-vue/devui/shared/hooks/use-namespace.ts
Labels: PR: unreviewed

#682 feat(Table): 支持设置单元格内容水平对齐方式
  packages/devui-vue/devui/table/__tests__/table.spec.tsx
  packages/devui-vue/devui/table/src/components/body/body.scss
  packages/devui-vue/devui/table/src/components/column/column-types.ts
  packages/devui-vue/devui/table/src/components/column/use-column.ts
  packages/devui-vue/devui/table/src/components/header/header.scss
  packages/devui-vue/devui/table/src/composables/use-table.ts
  packages/devui-vue/docs/components/table/index.md
Labels: PR: reviewed-approved, feature

#634 fix(Badge): 修复重构样式带来的测试错误
  packages/devui-vue/devui/badge/__tests__/badge.spec.ts
Labels: bug, PR: reviewed-approved

#635 fix(Breadcrumb): 修复重构样式带来的测试错误
  packages/devui-vue/devui/breadcrumb/__tests__/breadcrumb.spec.ts
Labels: bug, PR: reviewed-approved

#638 fix(Card): 修复重构样式带来的测试错误
  packages/devui-vue/devui/card/__tests__/__snapshots__/card.spec.ts.snap
  packages/devui-vue/devui/card/__tests__/card.spec.ts
Labels: bug, PR: reviewed-approved

#639 fix(Carousel): 修复重构样式带来的测试错误
  packages/devui-vue/devui/carousel/__tests__/carousel.spec.ts
Labels: bug, PR: unreviewed, PR: reviewed-approved

#654 fix(Dropdown): 修复重构样式带来的测试错误
  packages/devui-vue/devui/dropdown/__tests__/dropdown.spec.tsx
Labels: bug, PR: reviewed-approved

#656 fix(EditableSelect): 修复测试错误
  packages/devui-vue/devui/editable-select/__tests__/editable-select.spec.ts
  packages/devui-vue/devui/editable-select/src/editable-select.tsx
Labels: bug, PR: reviewed-approved

#657 fix(Fullscreen): 修复测试错误并新增属性测试
  packages/devui-vue/devui/fullscreen/__tests__/fullscreen.spec.ts
Labels: bug, PR: reviewed-approved

#658 fix(Grid): 修复重构样式带来的测试错误
  packages/devui-vue/devui/grid/__tests__/grid.spec.tsx
  packages/devui-vue/devui/grid/src/col.tsx
  packages/devui-vue/devui/grid/src/composables/use-grid.ts
  packages/devui-vue/devui/grid/src/composables/use-screen.ts
  packages/devui-vue/devui/grid/src/row.tsx
Labels: bug

#685 feat(Table): 组件样式宽高等样式优化
  packages/devui-vue/devui/table/src/components/colgroup/colgroup.tsx
  packages/devui-vue/devui/table/src/components/column/use-column.ts
  packages/devui-vue/devui/table/src/composables/use-table.ts
  packages/devui-vue/docs/components/table/index.md
Labels: bug, PR: unreviewed

#684 feat(Table): 支持单元格点击事件
  packages/devui-vue/devui/table/__tests__/table.spec.tsx
  packages/devui-vue/devui/table/src/components/body/body-types.ts
  packages/devui-vue/devui/table/src/components/body/body.tsx
  packages/devui-vue/devui/table/src/table.tsx
  packages/devui-vue/docs/components/table/index.md
Labels: PR: unreviewed, feature

#686 feat(table): add table check event
  packages/devui-vue/devui/table/src/components/column/column.tsx
  packages/devui-vue/devui/table/src/components/column/config.tsx
  packages/devui-vue/devui/table/src/store/index.ts
  packages/devui-vue/devui/table/src/store/store-types.ts
  packages/devui-vue/devui/table/src/table.tsx
  packages/devui-vue/docs/components/table/index.md
Labels: PR: unreviewed, feature, refactoring

#681 docs: update contributing doc
  packages/devui-vue/docs/contributing/index.md
Labels: documentation, PR: unreviewed, PR: reviewed-approved

#687 refactor(AutoComplete): 抽离测试样式
  packages/devui-vue/devui/auto-complete/__tests__/auto-complete.spec.ts
Labels: PR: reviewed-approved, refactoring

#690 refactor(Avatar): 抽离测试样式
  packages/devui-vue/devui/avatar/__tests__/avatar.spec.ts
Labels: PR: reviewed-approved, refactoring

#688 feat(textarea): 支持autosize属性
  packages/devui-vue/devui/textarea/__tests__/textarea.spec.ts
  packages/devui-vue/devui/textarea/src/composables/use-textarea-autosize.ts
  packages/devui-vue/devui/textarea/src/textarea-types.ts
  packages/devui-vue/devui/textarea/src/textarea.tsx
  packages/devui-vue/devui/textarea/src/utils.ts
  packages/devui-vue/docs/components/textarea/index.md
Labels: PR: unreviewed, feature

#693 feat(Table): 支持配置是否显示表头
  packages/devui-vue/devui/table/__tests__/table.spec.tsx
  packages/devui-vue/devui/table/src/components/fix-header.tsx
  packages/devui-vue/devui/table/src/components/normal-header.tsx
  packages/devui-vue/devui/table/src/table-types.ts
  packages/devui-vue/docs/components/table/index.md
Labels: PR: unreviewed, feature

#696 feat(Table): 增加row-key参数
  packages/devui-vue/devui/table/src/table-types.ts
  packages/devui-vue/docs/components/table/index.md
Labels: PR: unreviewed

#697 feat(checkbox-group): checkbox-group add select max limit
  packages/devui-vue/devui/checkbox/__tests__/checkbox-group.spec.ts
  packages/devui-vue/devui/checkbox/src/checkbox-group.tsx
  packages/devui-vue/devui/checkbox/src/checkbox-types.ts
  packages/devui-vue/devui/checkbox/src/checkbox.tsx
  packages/devui-vue/docs/components/checkbox/index.md
Labels: PR: reviewed-approved, feature

#692 refactor(Breadcrumb): 抽离测试样式
  packages/devui-vue/devui/breadcrumb/__tests__/breadcrumb.spec.ts
Labels: PR: reviewed-approved, refactoring

#701 fix(Tabs): 修复Tabs组件插槽内容为空时渲染错误
  packages/devui-vue/devui/tabs/src/tab.tsx
  packages/devui-vue/devui/tabs/src/tabs.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved

#703 refactor(avatar): 将render移到setup使符合规范
  packages/devui-vue/devui/avatar/src/avatar.tsx
  packages/devui-vue/devui/button/src/button.scss
Labels: PR: unreviewed, refactoring

#704 feat(select): 添加d-option组件
  packages/devui-vue/devui/select/composables/use-cache-options.ts
  packages/devui-vue/devui/select/composables/use-select-outside-click.ts
  packages/devui-vue/devui/select/index.ts
  packages/devui-vue/devui/select/src/const.ts
  packages/devui-vue/devui/select/src/option.tsx
  packages/devui-vue/devui/select/src/select-types.ts
  packages/devui-vue/devui/select/src/select.tsx
  packages/devui-vue/devui/select/src/use-option.ts
  packages/devui-vue/devui/select/src/use-select.ts
Labels: PR: reviewed-approved, feature

#705 feat(Table): Table不同大小对应不同字号
  packages/devui-vue/devui/table/src/table.scss
Labels: PR: reviewed-approved, feature

#706 refactor(comment): 重构代码并完善demo和api文档
  packages/devui-vue/devui/comment/src/comment-types.ts
  packages/devui-vue/devui/comment/src/comment.scss
  packages/devui-vue/devui/comment/src/comment.tsx
  packages/devui-vue/devui/comment/src/get-slot.ts
  packages/devui-vue/devui/shared/utils/url.ts
  packages/devui-vue/docs/components/comment/index.md
Labels: PR: unreviewed, refactoring

#707 refactor(icon): 重构icon组件并支持svg图标
  packages/devui-vue/devui/icon/src/const.ts
  packages/devui-vue/devui/icon/src/icon-types.ts
  packages/devui-vue/devui/icon/src/icon.scss
  packages/devui-vue/devui/icon/src/icon.tsx
  packages/devui-vue/devui/icon/src/svg-icon.tsx
  packages/devui-vue/docs/components/icon/index.md
Labels: PR: unreviewed, feature, refactoring

#708 feat(table): add table checkable
  packages/devui-vue/devui/table/src/components/column/column-types.ts
  packages/devui-vue/devui/table/src/components/column/column.tsx
  packages/devui-vue/docs/components/table/index.md
Labels: PR: unreviewed, feature

#709 feat(checkbox): add size border
  packages/devui-vue/devui/checkbox/__tests__/checkbox-group.spec.ts
  packages/devui-vue/devui/checkbox/__tests__/checkbox.spec.ts
  packages/devui-vue/devui/checkbox/src/checkbox-group.scss
  packages/devui-vue/devui/checkbox/src/checkbox-group.tsx
  packages/devui-vue/devui/checkbox/src/checkbox-types.ts
  packages/devui-vue/devui/checkbox/src/checkbox.scss
  packages/devui-vue/devui/checkbox/src/checkbox.tsx
  packages/devui-vue/docs/components/checkbox/index.md
Labels: PR: reviewed-approved, feature

#711 fix(button): 修复button组件demo报错问题
  packages/devui-vue/docs/components/button/index.md
Labels: bug, PR: unreviewed, PR: reviewed-approved

#710 feat(Table): 支持单元格内容过长隐藏时显示tooltip
  packages/devui-vue/devui/table/__tests__/table.spec.tsx
  packages/devui-vue/devui/table/src/components/body-td/body-td-types.ts
  packages/devui-vue/devui/table/src/components/body-td/body-td.tsx
  packages/devui-vue/devui/table/src/components/body-td/use-body-td.ts
  packages/devui-vue/devui/table/src/components/body/body.scss
  packages/devui-vue/devui/table/src/components/column/column-types.ts
  packages/devui-vue/devui/table/src/components/column/use-column.ts
  packages/devui-vue/docs/components/table/index.md
Labels: PR: reviewed-approved, feature

#712 fix(Icon): 移除Icon组件的空根节点
  packages/devui-vue/devui/icon/src/icon.tsx
Labels: bug, PR: unreviewed

#714 feat(table): 支持基础版本reserve-check勾选状态保留功能
  packages/devui-vue/devui/table/src/components/column/column-types.ts
  packages/devui-vue/devui/table/src/components/column/column.tsx
  packages/devui-vue/devui/table/src/components/column/config.tsx
  packages/devui-vue/devui/table/src/store/store-types.ts
  packages/devui-vue/docs/components/table/index.md
Labels: PR: unreviewed, feature

#713 feat(input): 支持prefix、suffix、prepend、append
  packages/devui-vue/devui/input/__tests__/input.spec.ts
  packages/devui-vue/devui/input/src/composables/use-input-render.ts
  packages/devui-vue/devui/input/src/input-types.tsx
  packages/devui-vue/devui/input/src/input.scss
  packages/devui-vue/devui/input/src/input.tsx
  packages/devui-vue/docs/components/input/index.md
Labels: PR: reviewed-approved, feature

#636 fix(Button): 修复重构样式带来的测试错误
  packages/devui-vue/devui/button/__tests__/button-group.spec.tsx
  packages/devui-vue/devui/button/__tests__/button.spec.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved

#716 fix(Avatar): 修复由于`gender`属性值错误抛出的异常改为警告
  packages/devui-vue/devui/avatar/__tests__/avatar.spec.ts
  packages/devui-vue/devui/avatar/src/avatar.tsx
Labels: bug

#719 style: 修改漏掉的样式前缀
  packages/devui-vue/devui/dropdown/src/dropdown-menu.tsx
  packages/devui-vue/devui/dropdown/src/dropdown.scss
  packages/devui-vue/devui/dropdown/src/dropdown.tsx
  packages/devui-vue/devui/tooltip/src/tooltip.scss
  packages/devui-vue/devui/tooltip/src/tooltip.tsx
Labels: PR: unreviewed

#721 fix(Table): 修复监听单元格变化时range报错问题
  packages/devui-vue/devui/table/src/components/body-td/use-body-td.ts
Labels: bug, PR: unreviewed

#722 feat(select): option支持自定义内容
  packages/devui-vue/devui/select/__tests__/option.spec.tsx
  packages/devui-vue/devui/select/__tests__/select.spec.tsx
  packages/devui-vue/devui/select/composables/use-select-outside-click.ts
  packages/devui-vue/devui/select/src/option.tsx
  packages/devui-vue/devui/select/src/select-types.ts
  packages/devui-vue/devui/select/src/select.tsx
  packages/devui-vue/devui/select/src/use-option.ts
  packages/devui-vue/devui/select/src/use-select.ts
  packages/devui-vue/docs/components/select/index.md
Labels: PR: unreviewed

#729 refactor(checkbox): 重写render和把逻辑移到use文件里
  packages/devui-vue/devui/checkbox/src/checkbox-group.tsx
  packages/devui-vue/devui/checkbox/src/checkbox-types.ts
  packages/devui-vue/devui/checkbox/src/checkbox.tsx
  packages/devui-vue/devui/checkbox/src/use-checkbox.ts
  packages/devui-vue/docs/components/checkbox/index.md
Labels: PR: reviewed-approved, refactoring

#723 refactor(Card): 抽离测试样式
  packages/devui-vue/devui/card/__tests__/card.spec.ts
Labels: PR: reviewed-approved, refactoring

#715 Transfer Feat: 新增拖拽排序穿梭框
  packages/devui-vue/devui/skeleton/src/components/skeleton-item.tsx
  packages/devui-vue/devui/tabs/src/tabs.scss
  packages/devui-vue/devui/transfer/src/components/transfer-body.tsx
  packages/devui-vue/devui/transfer/src/components/transfer-panel.tsx
  packages/devui-vue/devui/transfer/src/composables/use-transfer-body.ts
  packages/devui-vue/devui/transfer/src/composables/use-transfer-header.ts
  packages/devui-vue/devui/transfer/src/composables/use-transfer-operate.ts
  packages/devui-vue/devui/transfer/src/composables/use-transfer-panel.ts
  packages/devui-vue/devui/transfer/src/composables/use-transfer.ts
  packages/devui-vue/devui/transfer/src/transfer-types.ts
  packages/devui-vue/devui/transfer/src/transfer.scss
  packages/devui-vue/devui/transfer/src/transfer.tsx
  packages/devui-vue/docs/components/transfer/index.md
Labels: PR: reviewed-approved, feature

#730 feat(select): 拆分input部分为子组件，多选显示tag.
  packages/devui-vue/devui/select/__tests__/option.spec.tsx
  packages/devui-vue/devui/select/__tests__/select.spec.tsx
  packages/devui-vue/devui/select/index.ts
  packages/devui-vue/devui/select/src/components/option.tsx
  packages/devui-vue/devui/select/src/components/select-content.tsx
  packages/devui-vue/devui/select/src/composables/use-cache-options.ts
  packages/devui-vue/devui/select/src/composables/use-option.ts
  packages/devui-vue/devui/select/src/composables/use-select-content.ts
  packages/devui-vue/devui/select/src/select-types.ts
  packages/devui-vue/devui/select/src/select.scss
  packages/devui-vue/devui/select/src/select.tsx
  packages/devui-vue/devui/select/src/use-select.ts
  packages/devui-vue/docs/components/select/index.md
Labels: PR: unreviewed, feature

#733 feat(Table): 支持拖动调整列宽功能
  packages/devui-vue/devui/table/src/components/colgroup/colgroup.tsx
  packages/devui-vue/devui/table/src/components/column/column-types.ts
  packages/devui-vue/devui/table/src/components/column/column.tsx
  packages/devui-vue/devui/table/src/components/column/use-column.ts
  packages/devui-vue/devui/table/src/components/header-th/header-th-types.ts
  packages/devui-vue/devui/table/src/components/header-th/header-th.tsx
  packages/devui-vue/devui/table/src/components/header-th/use-header-th.ts
  packages/devui-vue/devui/table/src/components/header/header.scss
  packages/devui-vue/devui/table/src/composables/use-table.ts
  packages/devui-vue/devui/table/src/table-types.ts
  packages/devui-vue/devui/table/src/table.scss
  packages/devui-vue/devui/table/src/table.tsx
  packages/devui-vue/devui/table/src/utils.ts
  packages/devui-vue/docs/components/table/index.md
Labels: PR: unreviewed, feature

#734 fix(checkbox): 修复 label, vlaue, isLimitDisabled 类型错误的问题
  packages/devui-vue/devui/checkbox/src/checkbox-types.ts
  packages/devui-vue/devui/checkbox/src/use-checkbox.ts
Labels: bug, PR: partially-approved

#726 fix(package): 解决 powershell 下命令执行的问题递归
  package.json
Labels: bug, PR: unreviewed, PR: reviewed-approved

#735 fix(Theme): 新增追光主题样式变量
  packages/devui-theme/src/theme-collection/extend-theme.ts
Labels: PR: unreviewed

#737 fix(Form): 修复Form中popover的用法
  packages/devui-vue/devui/form/src/components/form-control/form-control.scss
  packages/devui-vue/devui/form/src/components/form-control/form-control.tsx
  packages/devui-vue/devui/form/src/components/form-label/form-label.tsx
Labels: bug, PR: unreviewed

#736 feat(auto-complete): 支持size属性、clearable属性、clear事件，blur事件
  packages/devui-vue/devui/auto-complete/__tests__/auto-complete.spec.ts
  packages/devui-vue/devui/auto-complete/src/auto-complete-types.ts
  packages/devui-vue/devui/auto-complete/src/auto-complete.scss
  packages/devui-vue/devui/auto-complete/src/auto-complete.tsx
  packages/devui-vue/devui/auto-complete/src/composables/use-auto-complete-render.ts
  packages/devui-vue/devui/auto-complete/src/composables/use-input-handle.ts
  packages/devui-vue/devui/input/__tests__/input.spec.ts
  packages/devui-vue/docs/components/auto-complete/index.md
Labels: PR: unreviewed

#738 feat(select): select collapse tags
  packages/devui-vue/devui/select/__tests__/select.spec.tsx
  packages/devui-vue/devui/select/src/components/select-content.tsx
  packages/devui-vue/devui/select/src/composables/use-select-content.ts
  packages/devui-vue/devui/select/src/select-types.ts
  packages/devui-vue/devui/select/src/select.scss
  packages/devui-vue/devui/select/src/select.tsx
  packages/devui-vue/docs/components/select/index.md
Labels: PR: reviewed-approved, feature

#739 fix(Tabs): 修复type属性值变更后，视图不刷新的问题
  packages/devui-vue/devui/tabs/src/tabs-types.ts
  packages/devui-vue/devui/tabs/src/tabs.tsx
  packages/devui-vue/devui/tabs/src/use-tabs.ts
Labels: bug, PR: unreviewed, PR: reviewed-approved

#740 fix(Rate): 修复modelValue,count属性变更后视图不更新问题
  packages/devui-vue/devui/rate/src/rate.tsx
Labels: bug, PR: unreviewed

#741 fix(Textarea): 移除id参数&文档中参数value错误，应该是v-model
  packages/devui-vue/devui/textarea/src/textarea-types.ts
  packages/devui-vue/docs/components/textarea/index.md
Labels: bug, PR: unreviewed

#743 refactor(InputNumber): 重构代码结构
  packages/devui-vue/devui/input-number/src/input-number-types.ts
  packages/devui-vue/devui/input-number/src/input-number.scss
  packages/devui-vue/devui/input-number/src/input-number.tsx
  packages/devui-vue/devui/input-number/src/use-input-number.ts
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
Labels: PR: unreviewed, refactoring

#742 feat(checkbox-button): checkbox-button feature
  packages/devui-vue/devui/checkbox/__tests__/checkbox-button.spec.ts
  packages/devui-vue/devui/checkbox/__tests__/checkbox-group.spec.ts
  packages/devui-vue/devui/checkbox/index.ts
  packages/devui-vue/devui/checkbox/src/checkbox-button.scss
  packages/devui-vue/devui/checkbox/src/checkbox-button.tsx
  packages/devui-vue/devui/checkbox/src/checkbox-group.tsx
  packages/devui-vue/devui/checkbox/src/checkbox-types.ts
  packages/devui-vue/devui/checkbox/src/use-checkbox.ts
  packages/devui-vue/docs/components/checkbox/index.md
Labels: PR: reviewed-approved, feature

#744 feat(popover): add disabled feature
  packages/devui-vue/devui/popover/__tests__/popover.spec.tsx
  packages/devui-vue/devui/popover/src/popover-types.ts
  packages/devui-vue/devui/popover/src/use-popover.ts
  packages/devui-vue/docs/components/popover/index.md
Labels: PR: reviewed-approved, feature

#745 feat(Select): 添加filter筛选
  packages/devui-vue/devui/select/__tests__/option.spec.tsx
  packages/devui-vue/devui/select/__tests__/select.spec.tsx
  packages/devui-vue/devui/select/src/components/option.tsx
  packages/devui-vue/devui/select/src/components/select-content.tsx
  packages/devui-vue/devui/select/src/composables/use-option.ts
  packages/devui-vue/devui/select/src/composables/use-select-content.ts
  packages/devui-vue/devui/select/src/const.ts
  packages/devui-vue/devui/select/src/select-types.ts
  packages/devui-vue/devui/select/src/select.scss
  packages/devui-vue/devui/select/src/select.tsx
  packages/devui-vue/devui/select/src/use-select.ts
  packages/devui-vue/docs/components/select/index.md
Labels: PR: reviewed-approved, feature

#747 fix(menu): vertical模式下动画优化
  packages/devui-vue/devui/menu/src/components/menu-item.tsx
  packages/devui-vue/devui/menu/src/components/menu-transition.tsx
  packages/devui-vue/devui/menu/src/components/sub-menu.tsx
  packages/devui-vue/devui/menu/src/helper/init-select.ts
  packages/devui-vue/devui/menu/src/helper/layer-composables.ts
  packages/devui-vue/devui/menu/src/styles/vertical.scss
Labels: bug, PR: reviewed-approved, refactoring

#746 feat(select): d-select支持blur、focus事件，添加说明文档、测试用例
  packages/devui-vue/devui/select/__tests__/select.spec.tsx
  packages/devui-vue/devui/select/src/components/select-content.tsx
  packages/devui-vue/devui/select/src/composables/use-select-content.ts
  packages/devui-vue/devui/select/src/select-types.ts
  packages/devui-vue/devui/select/src/select.scss
  packages/devui-vue/devui/select/src/select.tsx
  packages/devui-vue/devui/select/src/use-select.ts
  packages/devui-vue/docs/components/auto-complete/index.md
  packages/devui-vue/docs/components/select/index.md
Labels: PR: reviewed-approved, feature

#750 refactor(comment): remove comment actions
  packages/devui-vue/devui/comment/src/comment-types.ts
  packages/devui-vue/devui/comment/src/comment.tsx
  packages/devui-vue/docs/components/comment/index.md
Labels: bug, PR: unreviewed

#749 fix(tag): 修复tag删除逻辑
  packages/devui-vue/devui/tag/__tests__/tag.spec.ts
  packages/devui-vue/devui/tag/src/tag.tsx
  packages/devui-vue/docs/components/tag/index.md
Labels: PR: reviewed-approved, refactoring

#725 refactor(table): 重构行勾选逻辑，支持勾选状态保留功能
  packages/devui-vue/devui/table/src/components/body-td/body-td-types.ts
  packages/devui-vue/devui/table/src/components/body-td/body-td.tsx
  packages/devui-vue/devui/table/src/components/body/body.tsx
  packages/devui-vue/devui/table/src/components/column/column-types.ts
  packages/devui-vue/devui/table/src/components/column/column.tsx
  packages/devui-vue/devui/table/src/components/column/config.tsx
  packages/devui-vue/devui/table/src/components/column/use-column.ts
  packages/devui-vue/devui/table/src/components/filter/filter-types.ts
  packages/devui-vue/devui/table/src/components/filter/multiple-filter.tsx
  packages/devui-vue/devui/table/src/store/index.ts
  packages/devui-vue/devui/table/src/store/store-types.ts
  packages/devui-vue/devui/table/src/table-types.ts
  packages/devui-vue/docs/components/table/index.md
Labels: PR: partially-approved, feature, refactoring

#753 feat(table): 增加表格展开行功能 expand
  packages/devui-vue/devui/table/src/components/body-td/body-td.tsx
  packages/devui-vue/devui/table/src/components/body/body.scss
  packages/devui-vue/devui/table/src/components/body/body.tsx
  packages/devui-vue/devui/table/src/components/colgroup/colgroup.tsx
  packages/devui-vue/devui/table/src/components/column/column-types.ts
  packages/devui-vue/devui/table/src/components/column/config.tsx
  packages/devui-vue/devui/table/src/components/column/use-column.ts
  packages/devui-vue/devui/table/src/components/header/header.tsx
  packages/devui-vue/devui/table/src/store/index.ts
  packages/devui-vue/devui/table/src/store/store-types.ts
  packages/devui-vue/docs/components/table/index.md
Labels: PR: unreviewed, feature

#751 feat(InputNumber): 新增精度参数&Input框相关方法
  packages/devui-vue/devui/input-number/src/input-number-icons.tsx
  packages/devui-vue/devui/input-number/src/input-number-types.ts
  packages/devui-vue/devui/input-number/src/input-number.scss
  packages/devui-vue/devui/input-number/src/input-number.tsx
  packages/devui-vue/devui/input-number/src/use-input-number.ts
  packages/devui-vue/devui/shared/utils/index.ts
  packages/devui-vue/devui/shared/utils/is.ts
  packages/devui-vue/docs/components/input-number/index.md
Labels: PR: reviewed-approved, feature

#755 feat(table): add expand-change event
  packages/devui-vue/devui/table/src/components/body/body.tsx
  packages/devui-vue/devui/table/src/components/column/config.tsx
  packages/devui-vue/devui/table/src/store/index.ts
  packages/devui-vue/devui/table/src/store/store-types.ts
  packages/devui-vue/devui/table/src/table.tsx
  packages/devui-vue/docs/components/table/index.md
Labels: PR: unreviewed, feature

#757 refactor(Form): Form使用结构变更，简化为d-form&d-form-item两层
  packages/devui-vue/devui/form/index.ts
  packages/devui-vue/devui/form/src/components/form-control/use-form-control.ts
  packages/devui-vue/devui/form/src/components/form-item/form-item-types.ts
  packages/devui-vue/devui/form/src/components/form-item/form-item.tsx
  packages/devui-vue/devui/form/src/components/form-label/use-form-label.ts
  packages/devui-vue/docs/components/form/index.md
Labels: PR: reviewed-approved, refactoring

#759 feat(table): add expandAllRows method
  packages/devui-vue/devui/table/src/store/index.ts
  packages/devui-vue/devui/table/src/store/store-types.ts
  packages/devui-vue/devui/table/src/table.tsx
  packages/devui-vue/docs/components/table/index.md
Labels: PR: unreviewed, feature

#766 fix(InputNumber): 修复交互问题
  packages/devui-vue/devui/input-number/src/input-number.tsx
  packages/devui-vue/devui/input-number/src/use-input-number.ts
Labels: PR: unreviewed

#765 feat(comment): comment avatar support base64 image
  packages/devui-vue/devui/comment/src/comment.tsx
  packages/devui-vue/devui/shared/utils/url.ts
Labels: PR: unreviewed, feature

#768 fix(select): 修复select样式、filter单元测试用例
  packages/devui-vue/devui/select/__tests__/select.spec.tsx
  packages/devui-vue/devui/select/src/select.scss
Labels: bug, PR: unreviewed, PR: reviewed-approved, unit-test

#770 feat(table): add expandRow/collapseRow methods
  packages/devui-vue/devui/table/src/store/index.ts
  packages/devui-vue/devui/table/src/store/store-types.ts
  packages/devui-vue/devui/table/src/table.tsx
  packages/devui-vue/docs/components/table/index.md
Labels: PR: unreviewed, feature

#779 docs: 补充组件的贡献者信息
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
Labels: PR: unreviewed, ignore-for-release

#781 fix(Form): 移除文档demo中的d-tag-input控件
  packages/devui-vue/devui/input-number/__tests__/input-number.spec.tsx
  packages/devui-vue/docs/components/form/index.md
Labels: PR: unreviewed, ignore-for-release

#782 fix(input/textarea/auto-complete): 修改样式，更新说明文档
  packages/devui-vue/devui/auto-complete/src/auto-complete.scss
  packages/devui-vue/devui/textarea/src/textarea.tsx
  packages/devui-vue/docs/components/input/index.md
Labels: bug, PR: reviewed-approved

#783 refactor(checkbox): 更新checkbox文档不要有重名变量和方法
  packages/devui-vue/docs/components/checkbox/index.md
Labels: PR: unreviewed

#784 fix(input/textarea): 修复说明文档命名重复问题
  packages/devui-vue/docs/components/input/index.md
  packages/devui-vue/docs/components/textarea/index.md
Labels: PR: unreviewed

#785 test(InputNumber): 补充InputNumber测试用例
  packages/devui-vue/devui/input-number/__tests__/input-number.spec.tsx
Labels: PR: unreviewed, ignore-for-release

#786 fix(input): 修复input、search、textarea聚焦时hover样式问题
  packages/devui-vue/devui/input/src/input.scss
  packages/devui-vue/devui/search/src/search.scss
  packages/devui-vue/devui/textarea/src/textarea.scss
Labels: PR: unreviewed

#787 fix(auto-complete): 修复输入框聚焦时的hover样式
  packages/devui-vue/devui/auto-complete/src/auto-complete.scss
Labels: PR: unreviewed

#788 feat(Modal): 新增escapable & showClose参数
  packages/devui-vue/devui/modal/__tests__/modal.spec.tsx
  packages/devui-vue/devui/modal/src/composables/use-modal.ts
  packages/devui-vue/devui/modal/src/modal-types.ts
  packages/devui-vue/devui/modal/src/modal.tsx
  packages/devui-vue/docs/components/modal/index.md
Labels: PR: unreviewed, feature

#790 feat(select): 添加远程加载loading属性，修复placeholder显示
  packages/devui-vue/devui/select/__tests__/select.spec.tsx
  packages/devui-vue/devui/select/src/composables/use-option.ts
  packages/devui-vue/devui/select/src/composables/use-select-content.ts
  packages/devui-vue/devui/select/src/select-types.ts
  packages/devui-vue/devui/select/src/use-select.ts
  packages/devui-vue/docs/components/select/index.md
Labels: PR: unreviewed, feature

#791 fix(AutoComplete): 修复禁用态样式问题&移除下拉菜单的箭头
  packages/devui-vue/devui/auto-complete/src/auto-complete.scss
  packages/devui-vue/devui/auto-complete/src/auto-complete.tsx
Labels: bug, PR: unreviewed

#793 feat(select): select组件支持focus、blur方法
  packages/devui-vue/devui/select/src/composables/use-cache-options.ts
  packages/devui-vue/devui/select/src/composables/use-select-function.ts
  packages/devui-vue/devui/select/src/select-types.ts
  packages/devui-vue/devui/select/src/select.scss
  packages/devui-vue/devui/select/src/select.tsx
  packages/devui-vue/devui/select/src/use-select.ts
  packages/devui-vue/docs/components/select/index.md
Labels: PR: unreviewed, feature

#794 fix(Table): 更新过滤和排序图标样式&排序图标增加命名前缀
  packages/devui-vue/devui/table/src/components/filter/filter.scss
  packages/devui-vue/devui/table/src/components/header/header.scss
  packages/devui-vue/devui/table/src/components/sort/sort.scss
  packages/devui-vue/devui/table/src/components/sort/sort.tsx
Labels: bug, PR: unreviewed

#795 refactor(FixedOverlay): 重构FixedOverlay
  packages/devui-vue/devui/overlay/src/fixed-overlay/fixed-overlay-types.ts
  packages/devui-vue/devui/overlay/src/fixed-overlay/fixed-overlay.scss
  packages/devui-vue/devui/overlay/src/fixed-overlay/index.tsx
  packages/devui-vue/devui/overlay/src/fixed-overlay/use-fixed-overlay.ts
  packages/devui-vue/docs/components/overlay/index.md
Labels: PR: reviewed-approved, refactoring

#796 feat(tree): add expandAllNodes method
  packages/devui-vue/devui/tree/src/composables/use-toggle.ts
  packages/devui-vue/docs/components/tree/index.md
Labels: PR: unreviewed, feature

#800 feat(Modal): 新增show-overlay&append-to-body参数&优化动画效果
  packages/devui-vue/devui/modal/src/composables/use-modal.ts
  packages/devui-vue/devui/modal/src/modal-types.ts
  packages/devui-vue/devui/modal/src/modal.scss
  packages/devui-vue/devui/modal/src/modal.tsx
  packages/devui-vue/docs/components/modal/index.md
Labels: PR: unreviewed, feature

#802 fix(Modal): 移除服务方式创建Modal的demo案例
  packages/devui-vue/docs/components/modal/index.md
Labels: PR: unreviewed

#799 feat(alert): alert增加center属性
  packages/devui-vue/devui/alert/__tests__/alert.spec.ts
  packages/devui-vue/devui/alert/src/alert-types.ts
  packages/devui-vue/devui/alert/src/alert.scss
  packages/devui-vue/devui/alert/src/alert.tsx
  packages/devui-vue/docs/components/alert/index.md
Labels: PR: unreviewed, feature
