Repository DevCloudFE/vue-devui, pull requests merged in 2022-07, with the labels that each got.

#938 fix(select): select组件图标及样式修复
  packages/devui-vue/devui/select/src/components/select-arrow-icon.tsx
  packages/devui-vue/devui/select/src/components/select-content.tsx
  packages/devui-vue/devui/select/src/composables/use-select-content.ts
  packages/devui-vue/devui/select/src/select-types.ts
  packages/devui-vue/devui/select/src/select.scss
Labels: bug, PR: unreviewed, PR: reviewed-approved

#936 perf(input/upload): 一些组件的样式刷新
  packages/devui-vue/devui/auto-complete/src/auto-complete.scss
  packages/devui-vue/devui/input/src/input.scss
  packages/devui-vue/devui/tabs/src/components/tab-nav/tab-nav.scss
  packages/devui-vue/devui/upload/src/upload.scss
  packages/devui-vue/devui/upload/src/upload.tsx
Labels: enhancement, PR: unreviewed, PR: reviewed-approved

#937 style(anchor): 修复eslint错误
  packages/devui-vue/devui/anchor/index.ts
  packages/devui-vue/devui/anchor/src/d-anchor-box.ts
  packages/devui-vue/devui/anchor/src/d-anchor-link.ts
  packages/devui-vue/devui/anchor/src/d-anchor.ts
  packages/devui-vue/devui/anchor/src/utils.ts
Labels: PR: reviewed-approved, refactoring

#939 refactor(cascader): refactor css use-filter
  packages/devui-vue/devui/cascader/__tests__/cascader.spec.ts
  packages/devui-vue/devui/cascader/components/cascader-item/index.scss
  packages/devui-vue/devui/cascader/components/cascader-item/index.tsx
  packages/devui-vue/devui/cascader/hooks/use-cascader.ts
  packages/devui-vue/devui/cascader/hooks/use-filter.ts
  packages/devui-vue/devui/cascader/src/cascader-types.ts
  packages/devui-vue/devui/cascader/src/cascader.scss
Labels: PR: reviewed-approved, refactoring

#940 style(breadcrumb): 修复类型报错
  packages/devui-vue/devui/breadcrumb/src/breadcrumb-item.tsx
  packages/devui-vue/devui/breadcrumb/src/breadcrumb.tsx
Labels: PR: reviewed-approved, refactoring

#941 style(back-top): 修复eslint错误
  packages/devui-vue/devui/back-top/__tests__/back-top.spec.ts
  packages/devui-vue/devui/back-top/index.ts
  packages/devui-vue/devui/back-top/src/back-top-types.ts
  packages/devui-vue/devui/back-top/src/hooks/index.ts
  packages/devui-vue/devui/back-top/src/hooks/use-event-listener.ts
  packages/devui-vue/devui/back-top/src/hooks/use-target.ts
  packages/devui-vue/devui/back-top/src/hooks/use-throttle.ts
  packages/devui-vue/devui/back-top/src/hooks/use-visibility.ts
Labels: PR: reviewed-approved, refactoring

#943 style(carousel): 修复eslint错误
  packages/devui-vue/devui/carousel/index.ts
  packages/devui-vue/devui/carousel/src/carousel.tsx
  packages/devui-vue/devui/carousel/src/types.ts
Labels: PR: reviewed-approved, refactoring

#942 style(badge): 修复类型报错
  packages/devui-vue/devui/badge/src/badge.tsx
Labels: PR: reviewed-approved, refactoring

#944 fix(collapse): 展开图标采用svg
  packages/devui-vue/devui/collapse/src/collapse-item.tsx
  packages/devui-vue/devui/collapse/src/collapse.scss
Labels: PR: unreviewed

#946 fix(collapse): 修改collapse组件open图标引用
  .eslintignore
  packages/devui-vue/devui/accordion/src/accordion-menu.tsx
  packages/devui-vue/devui/collapse/src/collapse-item.tsx
  packages/devui-vue/devui/collapse/src/collapse-open-icon.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved

#945 refactor(transfer): fix css
  packages/devui-vue/devui/transfer/src/components/transfer-body.tsx
  packages/devui-vue/devui/transfer/src/components/transfer-header.tsx
  packages/devui-vue/devui/transfer/src/transfer-checkbox.tsx
  packages/devui-vue/devui/transfer/src/transfer-drag-item.tsx
  packages/devui-vue/devui/transfer/src/transfer-operation.tsx
  packages/devui-vue/devui/transfer/src/transfer.scss
Labels: bug, PR: unreviewed, PR: reviewed-approved

#950 feat(locale): 组件内词条翻译
  packages/devui-vue/devui/accordion/src/accordion-list.tsx
  packages/devui-vue/devui/auto-complete/src/components/dropdown.tsx
  packages/devui-vue/devui/cascader/components/cascader-list/index.tsx
  packages/devui-vue/devui/color-picker/src/components/color-picker-panel/color-picker-panel.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/calendar-panel.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/date-picker-panel.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/month-calendar-panel.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/range-date-picker-pro.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/time-picker-panel.tsx
  packages/devui-vue/devui/date-picker-pro/src/const.ts
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro-types.ts
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro.tsx
  packages/devui-vue/devui/date-picker-pro/src/range-date-picker-types.ts
  packages/devui-vue/devui/date-picker-pro/src/use-picker-pro.ts
  packages/devui-vue/devui/editable-select/src/editable-select.tsx
  packages/devui-vue/devui/input/src/input-types.tsx
  packages/devui-vue/devui/input/src/input.scss
  packages/devui-vue/devui/input/src/input.tsx
  packages/devui-vue/devui/locale/lang/en-us.ts
  packages/devui-vue/devui/locale/lang/zh-cn.ts
  packages/devui-vue/devui/search/src/search-types.ts
  packages/devui-vue/devui/search/src/search.tsx
  packages/devui-vue/devui/select/src/components/select-content.tsx
  packages/devui-vue/devui/select/src/select-types.ts
  packages/devui-vue/devui/select/src/select.tsx
  packages/devui-vue/devui/select/src/use-select.ts
  packages/devui-vue/devui/splitter/src/components/splitter-bar.tsx
  packages/devui-vue/devui/steps-guide/src/steps-guide.tsx
  packages/devui-vue/devui/table/src/components/filter/multiple-filter.tsx
  packages/devui-vue/devui/tag-input/src/tag-input-types.ts
  packages/devui-vue/devui/tag-input/src/tag-input.tsx
  packages/devui-vue/devui/time-picker/src/components/time-popup/index.tsx
  packages/devui-vue/devui/time-select/src/time-select-types.ts
  packages/devui-vue/devui/time-select/src/time-select.tsx
  packages/devui-vue/devui/transfer/src/components/transfer-body.tsx
  packages/devui-vue/devui/transfer/src/components/transfer-header.tsx
  packages/devui-vue/devui/transfer/src/components/transfer-panel.tsx
  packages/devui-vue/devui/transfer/src/composables/use-transfer-body.ts
  packages/devui-vue/devui/transfer/src/composables/use-transfer-header.ts
  packages/devui-vue/devui/transfer/src/composables/use-transfer-panel.ts
  packages/devui-vue/devui/transfer/src/transfer-types.ts
  packages/devui-vue/devui/transfer/src/transfer.tsx
  packages/devui-vue/devui/tree-select/src/tree-select-types.ts
  packages/devui-vue/devui/tree-select/src/tree-select.tsx
  packages/devui-vue/devui/tree/src/components/tree-node.tsx
  packages/devui-vue/devui/tree/src/deprecated-tree.tsx
  packages/devui-vue/devui/upload/src/composables/use-select-files.ts
  packages/devui-vue/devui/upload/src/i18n-upload.ts
  packages/devui-vue/devui/upload/src/upload-types.ts
  packages/devui-vue/devui/upload/src/upload.tsx
  packages/devui-vue/docs/components/input/index.md
  packages/devui-vue/docs/components/time-select/index.md
Labels: PR: unreviewed, feature

#951 refactor(cascader): 清理无用代码
  packages/devui-vue/devui/cascader/hooks/use-cascader-multiple.ts
  packages/devui-vue/docs/components/cascader/index.md
Labels: PR: reviewed-approved, refactoring

#953 fix: 修复lang文件大小写问题
  packages/devui-vue/devui/locale/lang/en-us.ts
  packages/devui-vue/devui/locale/lang/zh-cn.ts
Labels: bug, PR: unreviewed

#955 fix(select): 修复select组件placeholder
  packages/devui-vue/devui/select/src/components/select-content.tsx
  packages/devui-vue/devui/select/src/composables/use-select-content.ts
Labels: bug, PR: unreviewed, PR: reviewed-approved

#956 fix(date-picker-pro): 修复日期选择器显示时间时，input框focus问题
  packages/devui-vue/devui/date-picker-pro/src/composables/use-calendar-selected.ts
Labels: bug, PR: unreviewed, PR: reviewed-approved

#954 fix(transfer): fix codecheck
  packages/devui-vue/devui/transfer/src/composables/use-transfer-body.ts
Labels: bug, PR: unreviewed

#961 fix(tree): 解决树节点勾选不生效和增删节点报错的问题
  packages/devui-vue/devui/tree/src/components/tree-node.tsx
  packages/devui-vue/devui/tree/src/composables/use-core.ts
  packages/devui-vue/devui/tree/src/composables/use-operate.ts
Labels: bug, PR: unreviewed

#957 fix(steps-guide): 修复固定前缀问题
  packages/devui-vue/devui/steps-guide/composables/use-steps-guide-position.ts
Labels: bug, PR: unreviewed, PR: reviewed-approved

#958 style(countdown): 修复eslint报错
  packages/devui-vue/devui/countdown/__tests__/countdown.spec.ts
  packages/devui-vue/devui/countdown/src/countdown.tsx
  packages/devui-vue/devui/countdown/src/utils.ts
Labels: PR: reviewed-approved, refactoring

#959 style(checkbox): 修复类型报错
  packages/devui-vue/devui/checkbox/src/checkbox-button.tsx
  packages/devui-vue/devui/checkbox/src/checkbox-types.ts
  packages/devui-vue/devui/checkbox/src/checkbox.tsx
  packages/devui-vue/devui/checkbox/src/use-checkbox.ts
Labels: PR: unreviewed, refactoring

#960 style(date-picker): 修复eslint错误
  packages/devui-vue/devui/date-picker/index.ts
  packages/devui-vue/devui/date-picker/src/components/calendar/index.tsx
  packages/devui-vue/devui/date-picker/src/components/helper.ts
  packages/devui-vue/devui/date-picker/src/components/panel/index.tsx
  packages/devui-vue/devui/date-picker/src/components/popup/index.tsx
  packages/devui-vue/devui/date-picker/src/components/timepicker/index.tsx
  packages/devui-vue/devui/date-picker/src/components/today-default/index.tsx
  packages/devui-vue/devui/date-picker/src/components/toolbar/index.tsx
  packages/devui-vue/devui/date-picker/src/components/toolbar/svg-icon.tsx
  packages/devui-vue/devui/date-picker/src/components/types.ts
  packages/devui-vue/devui/date-picker/src/components/utils.ts
  packages/devui-vue/devui/date-picker/src/components/vertical-slider/index.tsx
  packages/devui-vue/devui/date-picker/src/date-picker-types.ts
  packages/devui-vue/devui/date-picker/src/date-picker.tsx
  packages/devui-vue/devui/date-picker/src/helper.ts
  packages/devui-vue/devui/date-picker/src/utils.ts
Labels: PR: reviewed-approved, refactoring

#962 style(color-picker): 修复eslint报错
  packages/devui-vue/devui/color-picker/__tests__/color-picker.spec.ts
  packages/devui-vue/devui/color-picker/index.ts
  packages/devui-vue/devui/color-picker/src/color-picker-types.ts
  packages/devui-vue/devui/color-picker/src/color-picker.tsx
  packages/devui-vue/devui/color-picker/src/components/color-alpha-slider/color-alpha-slider.tsx
  packages/devui-vue/devui/color-picker/src/components/color-alpha-slider/color-picker-alpha-slider-types.ts
  packages/devui-vue/devui/color-picker/src/components/color-basic/color-basic-types.ts
  packages/devui-vue/devui/color-picker/src/components/color-basic/color-basic.tsx
  packages/devui-vue/devui/color-picker/src/components/color-edit/color-edit.tsx
  packages/devui-vue/devui/color-picker/src/components/color-history/color-history.tsx
  packages/devui-vue/devui/color-picker/src/components/color-hue-slider/color-hue-slider.tsx
  packages/devui-vue/devui/color-picker/src/components/color-hue-slider/color-picker-hue-slider-types.ts
  packages/devui-vue/devui/color-picker/src/components/color-palette/color-palette.tsx
  packages/devui-vue/devui/color-picker/src/components/color-palette/color-picker-palette-types.ts
  packages/devui-vue/devui/color-picker/src/components/color-picker-panel/color-picker-panel.tsx
  packages/devui-vue/devui/color-picker/src/utils/color-utils-types.ts
  packages/devui-vue/devui/color-picker/src/utils/color-utils.ts
  packages/devui-vue/devui/color-picker/src/utils/composeable.ts
  packages/devui-vue/devui/color-picker/src/utils/dom-dragger.ts
  packages/devui-vue/devui/color-picker/src/utils/helpers.ts
  packages/devui-vue/devui/shared/utils/omit.ts
Labels: PR: reviewed-approved, refactoring

#963 style(date-picker-pro): 修复eslint报错
  packages/devui-vue/devui/date-picker-pro/__tests__/date-picker-pro.spec.tsx
  packages/devui-vue/devui/date-picker-pro/__tests__/month-picker.spec.tsx
  packages/devui-vue/devui/date-picker-pro/__tests__/year-picker.spec.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/calendar-panel.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/icon-calendar.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/icon-close.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/month-calendar-panel.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/range-date-picker-pro.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/time-picker-panel.tsx
  packages/devui-vue/devui/date-picker-pro/src/composables/use-calendar-panel.ts
  packages/devui-vue/devui/date-picker-pro/src/composables/use-month-calendar-panel.ts
  packages/devui-vue/devui/date-picker-pro/src/composables/use-time-picker-panel.ts
  packages/devui-vue/devui/date-picker-pro/src/composables/use-year-calendar-panel.ts
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro-types.ts
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro.tsx
  packages/devui-vue/devui/date-picker-pro/src/range-date-picker-types.ts
  packages/devui-vue/devui/date-picker-pro/src/use-picker-pro.ts
  packages/devui-vue/devui/date-picker-pro/src/utils.ts
Labels: PR: reviewed-approved, refactoring

#964 style(dropdown): 修复eslint报错
  packages/devui-vue/devui/dropdown/src/dropdown-menu.tsx
  packages/devui-vue/devui/dropdown/src/dropdown-types.ts
  packages/devui-vue/devui/dropdown/src/dropdown.tsx
  packages/devui-vue/devui/dropdown/src/use-dropdown.ts
Labels: PR: reviewed-approved, refactoring

#966 style(fullscreen): 修复eslint错误
  packages/devui-vue/devui/fullscreen/__tests__/fullscreen.spec.ts
Labels: PR: reviewed-approved, refactoring

#967 style(input-icon): 修复eslint错误
  packages/devui-vue/devui/input-icon/src/input-icon.tsx
  packages/devui-vue/devui/input/src/input-types.tsx
Labels: PR: reviewed-approved, refactoring

#968 style(input-number): 修复eslint错误
  packages/devui-vue/devui/input-number/__tests__/input-number.spec.tsx
  packages/devui-vue/devui/input-number/index.ts
Labels: PR: reviewed-approved, refactoring

#969 style(layout): 修复类型错误
  packages/devui-vue/devui/layout/src/layout.tsx
Labels: PR: reviewed-approved, refactoring

#970 style(notification): 修复eslint错误
  packages/devui-vue/devui/menu/src/menu.tsx
  packages/devui-vue/devui/modal/__tests__/modal.spec.tsx
  packages/devui-vue/devui/nav-sprite/index.ts
  packages/devui-vue/devui/nav-sprite/src/nav-sprite-types.ts
  packages/devui-vue/devui/nav-sprite/src/nav-sprite.tsx
  packages/devui-vue/devui/notification/src/notification-icons.tsx
  packages/devui-vue/devui/notification/src/notification-service.tsx
  packages/devui-vue/devui/notification/src/use-notification.ts
Labels: PR: reviewed-approved, refactoring

#971 style(select): 修复esint报错
  packages/devui-vue/devui/select/__tests__/option-group.spec.tsx
  packages/devui-vue/devui/select/__tests__/select.spec.tsx
  packages/devui-vue/devui/select/src/components/select-content.tsx
  packages/devui-vue/devui/select/src/use-select.ts
Labels: PR: reviewed-approved, refactoring

#980 fix(select/date-picker-pro): 修复组件样式问题
  packages/devui-vue/devui/date-picker-pro/src/components/range-date-picker-pro.tsx
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro.scss
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro.tsx
  packages/devui-vue/devui/select/src/components/select-content.tsx
  packages/devui-vue/devui/select/src/select.scss
Labels: bug, PR: unreviewed, PR: reviewed-approved

#975 style(form): 修复eslint错误
  packages/devui-vue/devui/form/src/components/form-control/form-control-types.ts
  packages/devui-vue/devui/form/src/components/form-control/use-form-control.ts
  packages/devui-vue/devui/form/src/components/form-item/form-item-types.ts
  packages/devui-vue/devui/form/src/components/form-item/use-form-item.ts
  packages/devui-vue/devui/form/src/composables/use-form-validation.ts
  packages/devui-vue/devui/form/src/composables/use-validate.ts
  packages/devui-vue/devui/form/src/form-types.ts
Labels: PR: reviewed-approved, refactoring

#976 style(quadrant-diagram): 修复eslint报错
  packages/devui-vue/devui/quadrant-diagram/index.ts
  packages/devui-vue/devui/quadrant-diagram/src/components/axis/index.tsx
  packages/devui-vue/devui/quadrant-diagram/src/quadrant-diagram.tsx
  packages/devui-vue/devui/quadrant-diagram/type.ts
Labels: PR: reviewed-approved, refactoring

#977 style(skeleton、slider): 修复eslint报错
  packages/devui-vue/devui/skeleton/src/skeleton.tsx
  packages/devui-vue/devui/slider/__tests__/slider.spec.tsx
Labels: PR: reviewed-approved, refactoring

#981 fix(time-picker): fix time-picker position
  packages/devui-vue/devui/time-picker/src/time-picker.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved

#986 style(auto-complate、steps): 修复eslint报错
  packages/devui-vue/devui/auto-complete/__tests__/auto-complete.spec.ts
  packages/devui-vue/devui/steps/__tests__/steps.spec.tsx
Labels: PR: reviewed-approved, refactoring

#984 style(table): 修复eslint报错
  packages/devui-vue/devui/table/__tests__/table.spec.tsx
  packages/devui-vue/devui/table/src/components/body-td/body-td-types.ts
  packages/devui-vue/devui/table/src/components/body-td/body-td.tsx
  packages/devui-vue/devui/table/src/components/body-td/use-body-td.ts
  packages/devui-vue/devui/table/src/components/body/body-types.ts
  packages/devui-vue/devui/table/src/components/body/body.tsx
  packages/devui-vue/devui/table/src/components/body/use-body.ts
  packages/devui-vue/devui/table/src/components/colgroup/colgroup.tsx
  packages/devui-vue/devui/table/src/components/column/column-types.ts
  packages/devui-vue/devui/table/src/components/column/column.tsx
  packages/devui-vue/devui/table/src/components/column/config.tsx
  packages/devui-vue/devui/table/src/components/column/use-column.ts
  packages/devui-vue/devui/table/src/components/filter/filter-types.ts
  packages/devui-vue/devui/table/src/components/fix-header.tsx
  packages/devui-vue/devui/table/src/components/header-th/header-th-types.ts
  packages/devui-vue/devui/table/src/components/header-th/header-th.tsx
  packages/devui-vue/devui/table/src/components/header-th/use-header-th.ts
  packages/devui-vue/devui/table/src/components/header/header.tsx
  packages/devui-vue/devui/table/src/components/header/use-header.ts
  packages/devui-vue/devui/table/src/components/normal-header.tsx
  packages/devui-vue/devui/table/src/components/sort/sort.tsx
  packages/devui-vue/devui/table/src/composables/use-table.ts
  packages/devui-vue/devui/table/src/store/index.ts
  packages/devui-vue/devui/table/src/store/store-types.ts
  packages/devui-vue/devui/table/src/table-types.ts
  packages/devui-vue/devui/table/src/table.tsx
  packages/devui-vue/devui/table/src/utils.ts
Labels: PR: reviewed-approved, refactoring

#985 style(tabs): 修复eslint报错
  packages/devui-vue/devui/tabs/src/components/tab-nav/composables/use-tab-nav-event.ts
  packages/devui-vue/devui/tabs/src/components/tab-nav/composables/use-tab-nav-function.ts
  packages/devui-vue/devui/tabs/src/components/tab-nav/tab-nav-types.ts
  packages/devui-vue/devui/tabs/src/components/tab-nav/tab-nav.tsx
  packages/devui-vue/devui/tabs/src/components/tab/tab.tsx
  packages/devui-vue/devui/tabs/src/tabs-types.ts
  packages/devui-vue/devui/tabs/src/use-tabs.ts
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
Labels: PR: reviewed-approved, refactoring

#983 test(editable-select): 修复组件单元测试
  packages/devui-vue/devui/editable-select/__tests__/editable-select.spec.ts
  packages/devui-vue/devui/editable-select/src/composables/use-cache-filtered-options.ts
  packages/devui-vue/devui/editable-select/src/editable-select.tsx
Labels: PR: reviewed-approved, unit-test

#990 style(time-picker): 修复eslint报错
  packages/devui-vue/devui/time-picker/src/components/popup-line/composables/use-popup-line.ts
  packages/devui-vue/devui/time-picker/src/components/popup-line/index.tsx
  packages/devui-vue/devui/time-picker/src/components/time-popup/index.tsx
  packages/devui-vue/devui/time-picker/src/components/time-scroll/composables/use-time-scroll.ts
  packages/devui-vue/devui/time-picker/src/components/time-scroll/index.tsx
  packages/devui-vue/devui/time-picker/src/composables/use-time-picker.ts
  packages/devui-vue/devui/time-picker/src/types.ts
Labels: unit-test

#989 style(tree、upload): 修复所有eslint报错
  packages/devui-vue/devui/tree/__tests__/basic-tree/basic-tree.spec.tsx
  packages/devui-vue/devui/tree/__tests__/checkable-tree/checkable-tree.spec.tsx
  packages/devui-vue/devui/tree/__tests__/node-merge/node-merge.spec.tsx
  packages/devui-vue/devui/upload/src/composables/use-select-files.ts
Labels: PR: reviewed-approved, unit-test

#991 fix: 修复底部区域响应式问题
  packages/devui-vue/docs/.vitepress/devui-theme/components/HomeFooter.vue
Labels: bug, PR: unreviewed

#999 fix(tree): tree组件全局共用一个 Map 导致 “节点合并” 功能错误
  packages/devui-vue/devui/tree/src/composables/use-core.ts
Labels: PR: reviewed-approved

#1005 test(status): 修复单元测试报错
  packages/devui-vue/devui/card/__tests__/card.spec.ts
Labels: PR: reviewed-approved, unit-test

#1007 fix(Icon): Icon组件样式问题，影响到Steps组件样式
  packages/devui-vue/devui/icon/src/composables/use-icon-dom.tsx
  packages/devui-vue/devui/icon/src/icon.scss
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1006 refactor(menu): 重构类名
  packages/devui-vue/devui/menu/src/components/menu-item/menu-item.tsx
  packages/devui-vue/devui/menu/src/components/sub-menu/sub-menu.tsx
  packages/devui-vue/devui/menu/src/components/sub-menu/use-sub-menu.ts
  packages/devui-vue/devui/menu/src/menu.tsx
  packages/devui-vue/devui/menu/src/styles/clear.scss
  packages/devui-vue/devui/menu/src/styles/horizontal.scss
  packages/devui-vue/devui/menu/src/styles/vertical.scss
  packages/devui-vue/docs/components/menu/index.md
  packages/devui-vue/docs/en-US/components/menu/index.md
Labels: PR: reviewed-approved, refactoring

#1009 docs: 补充代码检查脚本命令的文档
  .eslintignore
  CONTRIBUTING.md
  packages/devui-vue/devui-cli/commands/code-check.js
Labels: documentation, PR: unreviewed

#1010 docs: 补充添加commit签名的内容
  CONTRIBUTING.md
  packages/devui-vue/docs/contributing/index.md
Labels: documentation, PR: unreviewed

#1011 fix: 解决深色模式下顶栏下拉框样式问题 close #1004
  packages/devui-vue/docs/.vitepress/devui-theme/components/NavDropdownLink.vue
Labels: bug, PR: unreviewed

#1016 test(collapse): 修复单元测试报错
  packages/devui-vue/devui/collapse/__tests__/collapse.spec.tsx
Labels: PR: reviewed-approved, unit-test

#1019 test(switch): 修复单元测试
  packages/devui-vue/devui/switch/__tests__/switch.spec.ts
Labels: PR: reviewed-approved, unit-test

#1020 fix(checkbox): checkbox-button 追光主题下样式异常 (close #1015);
  packages/devui-vue/devui/checkbox/src/checkbox-button.scss
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1024 docs: 更新组件进展文档
  packages/devui-vue/docs/components/overview/index.md
Labels: PR: unreviewed, ignore-for-release

#1034 feat(tree): 优化过滤后节点的显示
  packages/devui-vue/devui/tree/src/components/tree-node-content.tsx
  packages/devui-vue/devui/tree/src/composables/use-search-filter.ts
  packages/devui-vue/devui/tree/src/composables/use-tree-node.ts
Labels: PR: reviewed-approved, feature

#1027 test(notification): 修复单元测试报错
  packages/devui-vue/devui/notification/__tests__/notification.spec.tsx
Labels: PR: reviewed-approved, unit-test

#1028 test(progress): 修复单元测试报错
  packages/devui-vue/devui/progress/__tests__/progress.spec.ts
Labels: PR: reviewed-approved, unit-test

#1032 test(statistic): 修复单元测试报错
  packages/devui-vue/devui/statistic/__tests__/statistic.spec.ts
Labels: PR: reviewed-approved, unit-test

#1029 test(rate): 修复单元测试报错
  packages/devui-vue/devui/rate/__tests__/rate.spec.ts
Labels: PR: reviewed-approved, unit-test

#1031 test(skeleton): 修复单元测试报错
  packages/devui-vue/devui/skeleton/__tests__/skeleton-item.spec.ts
Labels: PR: reviewed-approved, unit-test

#1030 test(ripple): 修复单元测试报错
  packages/devui-vue/devui/ripple/__tests__/ripple.spec.ts
Labels: PR: reviewed-approved, unit-test

#1047 docs: 更新overview文档
  packages/devui-vue/docs/components/overview/index.md
Labels: PR: unreviewed, ignore-for-release

#1063 test(loading): 修复单元测试报错
  packages/devui-vue/devui/loading/__tests__/loading.spec.ts
Labels: PR: reviewed-approved, unit-test

#1065 test(splitter、input): 修复单元测试报错
  packages/devui-vue/devui/input/__tests__/input.spec.ts
  packages/devui-vue/devui/splitter/__tests__/splitter.spec.ts
Labels: PR: reviewed-approved, unit-test

#1066 test(slider): 修复eslint报错
  packages/devui-vue/devui/slider/__tests__/slider.spec.tsx
  packages/devui-vue/devui/slider/src/slider.tsx
Labels: unit-test

#1067 test(pagination、form): 修复单元测试、增加单元测试
  packages/devui-vue/devui/form/__tests__/form.spec.ts
  packages/devui-vue/devui/pagination/__tests__/pagination.spec.ts
  packages/devui-vue/docs/components/form/index.md
Labels: PR: reviewed-approved, unit-test

#1068 fix(ImagePreview): 优化ImagePreview组件样式
  packages/devui-theme/src/theme-collection/extend-theme.ts
  packages/devui-vue/devui/image-preview/src/image-preview.scss
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1070 test(upload、auto-complete): 修复单元测试报错
  packages/devui-vue/devui/auto-complete/__tests__/auto-complete.spec.ts
  packages/devui-vue/devui/upload/__tests__/upload.spec.ts
Labels: PR: reviewed-approved, unit-test

#1072 test(carousel): 修复单元测试报错
  packages/devui-vue/devui/carousel/__tests__/carousel.spec.ts
Labels: PR: reviewed-approved, unit-test

#1075 refactor(tree): 移除deprecated文件
  packages/devui-vue/devui/tree/src/composables/use-drag.ts
  packages/devui-vue/devui/tree/src/config.ts
  packages/devui-vue/devui/tree/src/deprecated-composables/use-checked.ts
  packages/devui-vue/devui/tree/src/deprecated-composables/use-highlight.ts
  packages/devui-vue/devui/tree/src/deprecated-composables/use-lazy.ts
  packages/devui-vue/devui/tree/src/deprecated-composables/use-merge-node.ts
  packages/devui-vue/devui/tree/src/deprecated-composables/use-operate.tsx
  packages/devui-vue/devui/tree/src/deprecated-composables/use-toggle.ts
  packages/devui-vue/devui/tree/src/deprecated-tree-types.ts
  packages/devui-vue/devui/tree/src/deprecated-tree.tsx
  packages/devui-vue/devui/tree/src/tree-node-content.tsx
Labels: PR: unreviewed, refactoring

#1074 test(Modal&Overlay): 修复Modal&Overlay组件单测
  packages/devui-vue/devui/auto-complete/__tests__/auto-complete.spec.ts
  packages/devui-vue/devui/carousel/__tests__/carousel.spec.ts
  packages/devui-vue/devui/modal/__tests__/modal.spec.tsx
  packages/devui-vue/devui/overlay/__tests__/overlay.spec.tsx
  packages/devui-vue/devui/shared/utils/index.ts
  packages/devui-vue/devui/shared/utils/wait.ts
Labels: PR: unreviewed, unit-test

#1076 test(comment、tag-input): 单元测试变动
  packages/devui-vue/devui/comment/__tests__/comment.spec.ts
  packages/devui-vue/devui/tag-input/__tests__/tag-input.spec.ts
Labels: PR: reviewed-approved, unit-test

#1077 test(time-select): 修复单元测试
  packages/devui-vue/devui/time-select/__tests__/time-select.spec.ts
  packages/devui-vue/devui/time-select/src/time-select.tsx
Labels: PR: reviewed-approved, unit-test

#1078 fix: 修复locale报错问题
  packages/devui-vue/devui/locale/create.ts
  packages/devui-vue/package.json
Labels: bug, PR: unreviewed

#1080 fix(Cascader): 修复条件判断不严谨导致DOM渲染错误
  packages/devui-vue/devui/cascader/components/cascader-item/index.tsx
Labels: bug, PR: unreviewed

#1081 test: 修复单元测试(cascader、steps-guide、transfer、tree-select)
  packages/devui-vue/devui/cascader/__tests__/cascader.spec.ts
  packages/devui-vue/devui/steps-guide/__tests__/steps-guide.spec.ts
  packages/devui-vue/devui/transfer/__tests__/transfer.spec.ts
  packages/devui-vue/devui/tree-select/__tests__/tree-select.spec.ts
Labels: PR: reviewed-approved, unit-test

#1084 fix(select): 修复select组件单元测试报错问题
  packages/devui-vue/devui/select/__tests__/option-group.spec.tsx
  packages/devui-vue/devui/select/__tests__/option.spec.tsx
  packages/devui-vue/devui/select/__tests__/select.spec.tsx
Labels: PR: reviewed-approved, unit-test

#1071 test(time-picker、tree): 修复单元测试报错
  packages/devui-vue/devui/time-picker/__tests__/time-picker.spec.ts
  packages/devui-vue/devui/tree/__tests__/basic-tree/basic-tree.spec.tsx
  packages/devui-vue/devui/tree/__tests__/checkable-tree/checkable-tree.spec.tsx
  packages/devui-vue/devui/tree/__tests__/lazy-node-tree/node-lazy-node.spec.tsx
  packages/devui-vue/devui/tree/__tests__/node-merge/node-merge.spec.tsx
  packages/devui-vue/devui/tree/__tests__/search-filter-tree/search-filter-tree.spec.tsx
  packages/devui-vue/devui/tree/src/composables/use-core.ts
Labels: PR: reviewed-approved, unit-test

#1086 test: 修复search/date-picker-pro组件单元测试问题
  .github/workflows/pull-request.yml
  packages/devui-vue/devui-cli/commands/code-check.js
  packages/devui-vue/devui/date-picker-pro/__tests__/date-picker-pro.spec.tsx
  packages/devui-vue/devui/search/__tests__/search.spec.ts
Labels: PR: unreviewed, unit-test

#1087 feat(table): Table组件添加懒加载功能 #1058
  package.json
  packages/devui-vue/devui/table/__tests__/table.spec.tsx
  packages/devui-vue/devui/table/src/components/body/body-types.ts
  packages/devui-vue/devui/table/src/components/body/body.scss
  packages/devui-vue/devui/table/src/components/body/body.tsx
  packages/devui-vue/devui/table/src/components/body/use-body.ts
  packages/devui-vue/devui/table/src/table-types.ts
  packages/devui-vue/devui/table/src/table.tsx
  packages/devui-vue/docs/components/table/index.md
  pnpm-lock.yaml
Labels: PR: reviewed-approved, feature

#1094 refactor: 移除back-top和textarea组件中的无用api
  packages/devui-vue/devui/back-top/src/back-top.tsx
  packages/devui-vue/devui/textarea/src/composables/use-textarea-event.ts
  packages/devui-vue/devui/textarea/src/textarea.tsx
  packages/devui-vue/docs/components/back-top/index.md
  packages/devui-vue/docs/components/textarea/index.md
Labels: PR: unreviewed, refactoring

#1095 fix: 解决写死registry导致的依赖安装失败
  packages/devui-vue/devui/panel/__tests__/panel.spec.ts
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1099 fix(tree): 修复tree组件nodeMap数据存储问题
  packages/devui-vue/devui/tree/src/composables/use-core.ts
  packages/devui-vue/devui/tree/src/composables/use-merge-nodes.ts
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1102 fix(tree): 解决勾选父节点禁用状态下的子节点也会被勾选的问题
  packages/devui-vue/devui/tree/__tests__/checkable-tree/checkable-tree-data.ts
  packages/devui-vue/devui/tree/__tests__/checkable-tree/checkable-tree.spec.tsx
  packages/devui-vue/devui/tree/src/composables/use-check.ts
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1104 chore: add pull request preview github action
  .github/workflows/preview-build.yml
  .github/workflows/preview-deploy.yml
Labels: enhancement, PR: unreviewed, PR: reviewed-approved

#1105 refactor(editable-select): 重构组件样式&代码结构
  packages/devui-vue/devui/editable-select/__tests__/editable-select.spec.ts
  packages/devui-vue/devui/editable-select/src/composables/use-cache-filtered-options.ts
  packages/devui-vue/devui/editable-select/src/composables/use-filter-options.ts
  packages/devui-vue/devui/editable-select/src/composables/use-input.ts
  packages/devui-vue/devui/editable-select/src/composables/use-keyboard-select.ts
  packages/devui-vue/devui/editable-select/src/composables/use-lazy-load.ts
  packages/devui-vue/devui/editable-select/src/composables/use-select.ts
  packages/devui-vue/devui/editable-select/src/editable-select-types.ts
  packages/devui-vue/devui/editable-select/src/editable-select.scss
  packages/devui-vue/devui/editable-select/src/editable-select.tsx
  packages/devui-vue/docs/components/editable-select/index.md
Labels: PR: reviewed-approved, refactoring

#1107 fix(Search): 组件内引入Icon，解决按需引入时Icon没有被解析的问题
  packages/devui-vue/devui/search/src/search.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1109 fix: 修复网站样式问题
  packages/devui-vue/docs/.vitepress/devui-theme/Layout.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/HomeHero.vue
Labels: bug, PR: unreviewed

#1113 docs(message): change message dome to setup mode
  packages/devui-vue/docs/components/message/index.md
Labels: documentation

#1111 fix(Drawer): 修复drawer和popover同时使用时，点击popover，drawer意外关闭的问题
  packages/devui-vue/devui/drawer/__tests__/drawer.spec.tsx
  packages/devui-vue/devui/drawer/src/use-drawer.ts
  packages/devui-vue/devui/popover/src/popover.tsx
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1115 docs: 更新贡献者信息
  packages/devui-vue/devui-cli/commands/release.js
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
  packages/devui-vue/package.json
Labels: documentation, PR: unreviewed

#1116 chore: Release Notes 的 Other Changes 中增加 unit-test 标签
  .github/release.yml
Labels: PR: unreviewed, ignore-for-release

#1117 fix: 在上一页/下一页按钮导航中隐藏未完成的组件
  packages/devui-vue/devui-cli/templates/vitepress-sidebar.js
  packages/devui-vue/docs/.vitepress/devui-theme/support/sideBar.js
Labels: bug, PR: unreviewed

#1118 fix: 修复本地上/下一页导航显示问题
  packages/devui-vue/docs/.vitepress/devui-theme/support/sideBar.js
Labels: bug, PR: unreviewed

#1122 fix(VirtualList): 完善文档，补充item-height参数说明
  packages/devui-vue/docs/components/virtual-list/index.md
Labels: documentation, PR: unreviewed, PR: reviewed-approved

#1123 fix(Tag): 优化文档中type参数默认值
  packages/devui-vue/docs/components/tag/index.md
Labels: documentation, PR: unreviewed, PR: reviewed-approved

#1125 fix(Dropdown): 修复展开时起始位置错误问题
  packages/devui-vue/devui/dropdown/src/use-dropdown.ts
Labels: bug, PR: unreviewed

#1126 fix(Cascader): 修复禁用选项字体无禁用色问题
  packages/devui-vue/devui/cascader/components/cascader-item/index.scss
Labels: bug, PR: unreviewed

#1124 fix(Carousel): 解决指示器样式和自动轮播问题
  packages/devui-theme/src/theme/theme-data.ts
  packages/devui-vue/devui/carousel/__tests__/carousel.spec.ts
  packages/devui-vue/devui/carousel/src/carousel.scss
  packages/devui-vue/devui/carousel/src/carousel.tsx
  packages/devui-vue/devui/carousel/src/types.ts
  packages/devui-vue/docs/components/carousel/index.md
Labels: bug, documentation, PR: unreviewed, unit-test

#1120 docs(message): modify the document title and other document styles
  packages/devui-vue/docs/components/message/index.md
Labels: documentation, PR: unreviewed, PR: reviewed-approved

#1130 docs: 更新timeline贡献者信息
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
Labels: PR: reviewed-approved

#1131 feat: 完成Mention组件所有功能及文档和demo说明
  package.json
  packages/devui-vue/devui/mention/index.ts
  packages/devui-vue/devui/mention/src/mention-types.ts
  packages/devui-vue/devui/mention/src/mention.scss
  packages/devui-vue/devui/mention/src/mention.tsx
  packages/devui-vue/devui/textarea/src/composables/use-textarea-event.ts
  packages/devui-vue/devui/textarea/src/textarea.tsx
  packages/devui-vue/docs/components/mention/index.md
  pnpm-lock.yaml
Labels: PR: reviewed-approved, feature

#1137 fix(Table): 修复无法自适应宽度的问题
  packages/devui-vue/devui/table/src/table.tsx
  packages/devui-vue/docs/components/table/index.md
Labels: bug, PR: unreviewed

#1134 feat: 增加vite @devui 路径别名配置
  packages/devui-vue/docs/vite.config.ts
  packages/devui-vue/tsconfig.json
Labels: enhancement, PR: reviewed-approved

#1127 feat(tree): 节点拖拽功能
  packages/devui-vue/devui/color-picker/src/utils/color-utils.ts
  packages/devui-vue/devui/shared/utils/index.ts
  packages/devui-vue/devui/shared/utils/omit.ts
  packages/devui-vue/devui/tree/__tests__/dragdrop-tree/dragdrop-tree-data.ts
  packages/devui-vue/devui/tree/__tests__/dragdrop-tree/dragdrop-tree.spec.tsx
  packages/devui-vue/devui/tree/src/components/tree-node.tsx
  packages/devui-vue/devui/tree/src/composables/index.ts
  packages/devui-vue/devui/tree/src/composables/use-drag.ts
  packages/devui-vue/devui/tree/src/composables/use-dragdrop.ts
  packages/devui-vue/devui/tree/src/composables/use-tree-node.ts
  packages/devui-vue/devui/tree/src/composables/use-tree-types.ts
  packages/devui-vue/devui/tree/src/composables/utils.ts
  packages/devui-vue/devui/tree/src/tree-types.ts
  packages/devui-vue/devui/tree/src/tree.scss
  packages/devui-vue/devui/tree/src/tree.tsx
  packages/devui-vue/devui/tree/src/utils.ts
  packages/devui-vue/docs/components/tree/index.md
Labels: PR: reviewed-approved, feature

#1136 docs(tree): 更新新增节点 demo 示例
  packages/devui-vue/docs/components/tree/index.md
Labels: documentation, PR: unreviewed, PR: reviewed-approved

#1140 fix(DatePickerPro): 修复 DatePickerPro 测试用例因日期格式不同导致的测试用例执行失败
  packages/devui-vue/devui/date-picker-pro/__tests__/date-picker-pro.spec.tsx
  packages/devui-vue/devui/date-picker-pro/__tests__/range-date-picker-pro.spec.tsx
Labels: PR: reviewed-approved, unit-test
