Repository DevCloudFE/vue-devui, pull requests merged in 2022-08, with the labels that each got.

#1148 fix(date-picker-pro): 解决DatePickerPro组件的单元测试报错
  packages/devui-vue/devui/date-picker-pro/__tests__/const.ts
  packages/devui-vue/devui/date-picker-pro/__tests__/date-picker-pro.spec.tsx
  packages/devui-vue/devui/date-picker-pro/__tests__/range-date-picker-pro.spec.tsx
  packages/devui-vue/devui/date-picker-pro/__tests__/utils.ts
Labels: PR: unreviewed, unit-test

#1155 chore: add v1.0.0 branches
  .github/workflows/pull-request.yml
  .github/workflows/sync-gitee.yml
Labels: PR: unreviewed, ignore-for-release

#1154 fix(Modal): 解决Modal组件默认情况下点击modal框内部关闭弹窗问题
  packages/devui-vue/devui/modal/src/modal.tsx
Labels: PR: reviewed-approved, v1.0.0

#1156 feat(Cascader): 增加host插槽，支持自定义展开菜单的宿主元素
  packages/devui-vue/devui/cascader/hooks/use-cascader-style.ts
  packages/devui-vue/devui/cascader/hooks/use-cascader.ts
  packages/devui-vue/devui/cascader/src/cascader-types.ts
  packages/devui-vue/devui/cascader/src/cascader.tsx
  packages/devui-vue/docs/components/cascader/index.md
Labels: PR: reviewed-approved, feature

#1160 fix(Cascader): 处理Cascader组件可搜索功能异常
  packages/devui-vue/devui/cascader/src/cascader.tsx
Labels: PR: unreviewed

#1165 fix(Cascader): 弹出面板移到body层，防止被父元素遮挡
  packages/devui-vue/devui/cascader/__tests__/cascader.spec.ts
  packages/devui-vue/devui/cascader/hooks/use-cascader-popup.ts
  packages/devui-vue/devui/cascader/hooks/use-cascader.ts
  packages/devui-vue/devui/cascader/src/cascader-types.ts
  packages/devui-vue/devui/cascader/src/cascader.tsx
Labels: bug, PR: unreviewed, unit-test

#1164 fix(TimePicker): 将弹出面板放到body层，解决被父元素遮挡的问题
  packages/devui-vue/devui/time-picker/__tests__/time-picker.spec.ts
  packages/devui-vue/devui/time-picker/src/composables/use-time-picker.ts
  packages/devui-vue/devui/time-picker/src/time-picker.tsx
  packages/devui-vue/devui/time-picker/src/types.ts
Labels: bug, PR: unreviewed, unit-test

#1162 fix(DatePickerPro): 解决弹出面板为加到body层，导致被父元素隐藏的问题
  packages/devui-vue/devui/date-picker-pro/__tests__/date-picker-pro.spec.tsx
  packages/devui-vue/devui/date-picker-pro/__tests__/month-picker.spec.tsx
  packages/devui-vue/devui/date-picker-pro/__tests__/range-date-picker-pro.spec.tsx
  packages/devui-vue/devui/date-picker-pro/__tests__/year-picker.spec.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/range-date-picker-pro.tsx
  packages/devui-vue/devui/date-picker-pro/src/composables/use-range-date-picker-pro.ts
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro-types.ts
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro.tsx
  packages/devui-vue/devui/date-picker-pro/src/range-date-picker-types.ts
  packages/devui-vue/devui/date-picker-pro/src/use-picker-pro.ts
Labels: bug, PR: unreviewed, unit-test

#1150 fix(Table): 修复数据结构层级较多时，渲染自定义模板失败的问题
  packages/devui-vue/devui/table/src/components/column/column.tsx
Labels: bug, PR: unreviewed

#1157 fix(Select): 解决使用过程中Select暴露出来的问题
  packages/devui-vue/devui/pagination/__tests__/pagination.spec.ts
  packages/devui-vue/devui/select/__tests__/option-group.spec.tsx
  packages/devui-vue/devui/select/__tests__/option.spec.tsx
  packages/devui-vue/devui/select/__tests__/select.spec.tsx
  packages/devui-vue/devui/select/src/select-types.ts
  packages/devui-vue/devui/select/src/select.tsx
  packages/devui-vue/devui/select/src/use-select.ts
  packages/devui-vue/devui/time-select/__tests__/time-select.spec.ts
  packages/devui-vue/docs/components/select/index.md
Labels: bug, PR: unreviewed, unit-test

#1145 fix(VirtualList): 解决item-height参数值固定，导致数据量较少时无法滚动的问题
  packages/devui-vue/devui/date-picker-pro/__tests__/date-picker-pro.spec.tsx
  packages/devui-vue/devui/date-picker-pro/__tests__/range-date-picker-pro.spec.tsx
  packages/devui-vue/devui/virtual-list/src/hooks/use-virtual.tsx
Labels: bug, PR: unreviewed

#1174 fix(devui-theme): 修复devui-theme默认主题问题
  packages/devui-theme/package.json
  packages/devui-theme/scripts/release.js
  packages/devui-theme/src/theme/theme-service.ts
  packages/devui-theme/vite.config.theme.collection.ts
  packages/devui-theme/vite.config.theme.ts
  packages/devui-vue/docs/quick-start/index.md
  packages/devui-vue/docs/theme-guide/index.md
  pnpm-lock.yaml
Labels: bug, PR: unreviewed, v1.0.0

#1141 docs(slider): 优化文档 demo 代码及数据结构错误
  packages/devui-vue/docs/components/slider/index.md
Labels: documentation, PR: unreviewed, PR: reviewed-approved

#1167 chore: fix vitepress head type
  packages/devui-vue/docs/.vitepress/config/head.ts
Labels: enhancement, PR: reviewed-approved

#1161 fix(menu): 修复样式问题
  packages/devui-vue/devui/menu/__tests__/menu.spec.ts
  packages/devui-vue/devui/menu/src/components/menu-item/menu-item.tsx
  packages/devui-vue/devui/menu/src/components/menu-item/use-menu-item.ts
  packages/devui-vue/devui/menu/src/components/sub-menu/sub-menu.tsx
  packages/devui-vue/devui/menu/src/composables/use-nearest-menu-element.ts
  packages/devui-vue/devui/menu/src/menu.scss
  packages/devui-vue/devui/menu/src/menu.tsx
  packages/devui-vue/devui/menu/src/styles/horizontal.scss
  packages/devui-vue/devui/menu/src/styles/public.scss
  packages/devui-vue/devui/menu/src/styles/vertical.scss
  packages/devui-vue/docs/components/menu/index.md
  packages/devui-vue/docs/en-US/components/menu/index.md
Labels: bug, PR: unreviewed, PR: reviewed-approved, v1.0.0

#1173 fix: 修改检视意见
  packages/devui-vue/devui/cascader/hooks/use-cascader-style.ts
  packages/devui-vue/devui/select/src/components/select-content.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1171 style(switch): 调整Switch组件样式问题
  packages/devui-vue/devui/switch/src/switch.scss
  packages/devui-vue/docs/components/switch/index.md
Labels: bug, PR: unreviewed, PR: reviewed-approved, v1.0.0

#1178 fix(Table): #1083 修复table中loadingMask无法全覆盖table的问题
  packages/devui-theme/src/styles-var/private/_z-index.scss
  packages/devui-vue/devui/color-picker/src/color-picker.scss
  packages/devui-vue/devui/loading/src/loading.scss
  packages/devui-vue/devui/styles-var/private/_z-index.scss
  packages/devui-vue/devui/table/src/table.scss
  packages/devui-vue/devui/table/src/table.tsx
  packages/devui-vue/docs/components/table/index.md
Labels: bug, PR: unreviewed, PR: reviewed-approved, v1.0.0

#1188 chore: add .code-workspace file
  vue-devui.code-workspace
Labels: enhancement, PR: unreviewed, PR: reviewed-approved

#1185 style(button): 修改Button按钮各尺寸大小
  packages/devui-vue/devui/button/src/button.scss
Labels: bug, PR: reviewed-approved, v1.0.0

#1182 test(tooltip): 修复 tooltip 测试用例偶现错误
  packages/devui-vue/devui/tooltip/__tests__/tooltip.spec.tsx
Labels: PR: reviewed-approved, unit-test

#1190 feat: add algolia search
  packages/devui-vue/docs/.vitepress/config/index.ts
  packages/devui-vue/docs/.vitepress/devui-theme/components/AlgoliaSearchBox.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/NavBar.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageToc.vue
  pnpm-lock.yaml
Labels: documentation, PR: unreviewed, v1.0.0

#1184 style(switch): 修复小号的带自定义文字的switch组件样式问题
  packages/devui-vue/devui/switch/src/switch.scss
  packages/devui-vue/docs/components/switch/index.md
Labels: bug, PR: unreviewed, PR: reviewed-approved, v1.0.0

#1192 fix(button): 修复primary+text按钮出现下划线问题 close #1170
  packages/devui-vue/devui/button/src/button.scss
Labels: bug, PR: unreviewed, v1.0.0

#1191 chore: add dev scripts
  package.json
  packages/devui-vue/docs/on-demand/index.md
  pnpm-lock.yaml
Labels: bug, PR: unreviewed

#1194 fix(date-picker-pro): 修复format为非法内容时日期显示异常的问题 closed #1153
  packages/devui-vue/devui/date-picker-pro/src/const.ts
  packages/devui-vue/devui/date-picker-pro/src/use-picker-pro.ts
  packages/devui-vue/devui/date-picker-pro/src/utils.ts
Labels: bug, PR: unreviewed, v1.0.0

#1195 fix(tree): 修复删除全部子节点之后父节点的展开/收起图标依然存在的问题 fixes #1179
  packages/devui-vue/devui/tree/src/composables/use-operate.ts
Labels: bug, PR: unreviewed, v1.0.0

#1197 fix(Select): 下拉面板展开时更新位置
  packages/devui-vue/devui/select/src/use-select.ts
Labels: bug, PR: unreviewed

#1196 fix(Cascader): 修复在Drawer中使用时，选择之后Drawer异常关闭的问题
  packages/devui-vue/devui/cascader/src/cascader.tsx
Labels: bug, PR: unreviewed

#1193 chore: update readme, fix scripts.json emoji
  README.md
  pnpm-lock.yaml
  scripts.json
Labels: documentation, PR: reviewed-approved

#1138 test(notification & table): 添加todo
  .gitignore
  packages/devui-vue/devui/notification/__tests__/notification.spec.tsx
  packages/devui-vue/devui/table/__tests__/table.spec.tsx
Labels: PR: reviewed-approved, unit-test

#1201 test: add some it.todo
  packages/devui-vue/devui/accordion/index.ts
  packages/devui-vue/devui/button/__tests__/button.spec.tsx
  packages/devui-vue/devui/drawer/__tests__/drawer.spec.tsx
  packages/devui-vue/devui/dropdown/__tests__/dropdown.spec.tsx
  packages/devui-vue/devui/icon/__tests__/icon.spec.ts
  packages/devui-vue/devui/message/__tests__/message.spec.tsx
  packages/devui-vue/devui/modal/__tests__/modal.spec.tsx
  packages/devui-vue/devui/notification/__tests__/notification.spec.tsx
  packages/devui-vue/devui/pagination/__tests__/pagination.spec.ts
  packages/devui-vue/devui/panel/__tests__/panel.spec.ts
  packages/devui-vue/devui/panel/index.ts
  packages/devui-vue/devui/popover/__tests__/popover.spec.tsx
  packages/devui-vue/devui/result/__tests__/result.spec.ts
  packages/devui-vue/devui/ripple/__tests__/ripple.spec.ts
  packages/devui-vue/devui/search/__tests__/search.spec.ts
  packages/devui-vue/devui/status/__tests__/status.spec.ts
  packages/devui-vue/devui/status/index.ts
  packages/devui-vue/devui/tooltip/__tests__/tooltip.spec.tsx
Labels: PR: unreviewed, unit-test

#1202 fix(Tabs): 修复删除选项卡异常问题
  packages/devui-vue/devui/tabs/src/components/tab-nav/composables/use-tab-nav-event.ts
  packages/devui-vue/devui/tabs/src/components/tab-nav/composables/use-tab-nav-function.ts
  packages/devui-vue/devui/tabs/src/components/tab-nav/tab-nav.tsx
  packages/devui-vue/devui/tabs/src/components/tab/tab-types.ts
  packages/devui-vue/devui/tabs/src/components/tab/tab.tsx
  packages/devui-vue/devui/tabs/src/tabs-types.ts
  packages/devui-vue/devui/tabs/src/tabs.scss
  packages/devui-vue/devui/tabs/src/tabs.tsx
Labels: bug, PR: unreviewed

#1203 fix(Tag): 移除容器外层多余marigin
  packages/devui-vue/devui/tag/src/tag.scss
  packages/devui-vue/docs/components/tag/index.md
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1204 test: add test todo for data entry and layout components
  packages/devui-vue/devui-cli/commands/code-check.js
  packages/devui-vue/devui/checkbox/__tests__/checkbox.spec.ts
  packages/devui-vue/devui/date-picker-pro/__tests__/date-picker-pro.spec.tsx
  packages/devui-vue/devui/date-picker-pro/__tests__/range-date-picker-pro.spec.tsx
  packages/devui-vue/devui/date-picker/index.ts
  packages/devui-vue/devui/editable-select/__tests__/editable-select.spec.ts
  packages/devui-vue/devui/form/__tests__/form-item.spec.tsx
  packages/devui-vue/devui/form/__tests__/form.spec.ts
  packages/devui-vue/devui/input-number/__tests__/input-number.spec.tsx
  packages/devui-vue/devui/input/__tests__/input.spec.ts
  packages/devui-vue/devui/layout/__tests__/layout.spec.ts
  packages/devui-vue/devui/mention/__tests__/mention.spec.tsx
  packages/devui-vue/devui/menu/__tests__/menu.spec.ts
  packages/devui-vue/devui/pagination/__tests__/pagination.spec.ts
  packages/devui-vue/devui/select/__tests__/select.spec.tsx
  packages/devui-vue/devui/select/src/select-types.ts
  packages/devui-vue/devui/select/src/use-select.ts
  packages/devui-vue/devui/slider/__tests__/slider.spec.tsx
  packages/devui-vue/devui/splitter/__tests__/splitter.spec.ts
  packages/devui-vue/devui/switch/__tests__/switch.spec.ts
  packages/devui-vue/devui/textarea/__tests__/textarea.spec.ts
  packages/devui-vue/devui/time-select/__tests__/time-select.spec.ts
  packages/devui-vue/devui/upload/__tests__/upload.spec.ts
  packages/devui-vue/docs/components/time-picker/index.md
Labels: PR: unreviewed, unit-test

#1206 test(badge): add test it.todo
  packages/devui-vue/devui/badge/__tests__/badge.spec.ts
Labels: PR: unreviewed, unit-test

#1205 fix(FlexibleOverlay): 在overlay阻止事件冒泡，防止弹出类组件和drawer等组合使用时，drawer异常关闭
  packages/devui-vue/devui/cascader/src/cascader.tsx
  packages/devui-vue/devui/dropdown/src/dropdown.tsx
  packages/devui-vue/devui/dropdown/src/use-dropdown.ts
  packages/devui-vue/devui/overlay/src/flexible-overlay/flexible-overlay-types.ts
  packages/devui-vue/devui/overlay/src/flexible-overlay/index.tsx
  packages/devui-vue/devui/popover/src/popover.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1208 docs: modify documents and add unit tests to do
  packages/devui-vue/devui/tree-select/__tests__/tree-select.spec.ts
  packages/devui-vue/devui/tree/__tests__/dragdrop-tree/dragdrop-tree.spec.tsx
  packages/devui-vue/devui/tree/__tests__/tree.spec.ts
  packages/devui-vue/docs/components/collapse/index.md
  packages/devui-vue/docs/components/layout/index.md
  packages/devui-vue/docs/components/rate/index.md
Labels: documentation, PR: reviewed-approved, unit-test

#1207 feat(input-number): 增加正则限制
  packages/devui-vue/devui/input-number/__tests__/input-number.spec.tsx
  packages/devui-vue/devui/input-number/src/input-number-types.ts
  packages/devui-vue/devui/input-number/src/use-input-number.ts
  packages/devui-vue/docs/components/input-number/index.md
Labels: PR: reviewed-approved, feature

#1212 fix(virtual-list): 修复默认列表项高度为0导致的虚拟列表失效问题
  packages/devui-vue/devui/virtual-list/src/const.ts
  packages/devui-vue/devui/virtual-list/src/virtual-list-types.ts
  packages/devui-vue/devui/virtual-list/src/virtual-list.tsx
  packages/devui-vue/docs/components/virtual-list/index.md
Labels: bug, PR: unreviewed

#1213 fix(Select): 修复新增选项时，面板位置错误问题
  packages/devui-vue/devui/select/src/use-select.ts
Labels: bug, PR: unreviewed

#1210 fix(Table): 表头固定时,横向滚动表头需要跟随滚动；新增cell-class参数
  packages/devui-vue/devui/table/src/components/body-td/body-td.tsx
  packages/devui-vue/devui/table/src/components/column/column-types.ts
  packages/devui-vue/devui/table/src/components/column/use-column.ts
  packages/devui-vue/devui/table/src/components/fix-header.tsx
  packages/devui-vue/devui/table/src/table.scss
  packages/devui-vue/docs/components/table/index.md
Labels: bug, PR: unreviewed, feature

#1219 fix(virtual-list): 解决虚拟滚动列表项超出容器被遮挡问题
  packages/devui-vue/devui/modal/src/modal.scss
  packages/devui-vue/devui/virtual-list/__tests__/index.spec.ts
  packages/devui-vue/devui/virtual-list/__tests__/virtual-list.spec.ts
  packages/devui-vue/devui/virtual-list/src/components/container.tsx
Labels: bug, PR: unreviewed

#1214 fix(tree): resolve tree component connection line error
  packages/devui-vue/devui/tree/src/composables/use-operate.ts
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1216 fix(input-number): 修正组件大小 及 修复操作按钮会超出容器的bug
  packages/devui-vue/devui/input-number/__tests__/input-number.spec.tsx
  packages/devui-vue/devui/input-number/src/input-number-types.ts
  packages/devui-vue/devui/input-number/src/input-number.scss
  packages/devui-vue/devui/input-number/src/use-input-number.ts
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1223 test(button): Complete the it.todo
  packages/devui-vue/devui/button/__tests__/button.spec.tsx
Labels: PR: reviewed-approved, unit-test

#1226 docs: 更新贡献者信息
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
Labels: PR: unreviewed

#1230 fix(icon): icon 字体文件加载失败，导致icon组件显示异常
  packages/devui-vue/docs/.vitepress/config/head.ts
  packages/devui-vue/docs/.vitepress/devui-theme/index.js
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1233 docs: 排查贡献者列表, 增加缺席的贡献者
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
Labels: PR: reviewed-approved

#1234 fix: 升级vue版本以解决本地环境字体文件404导致的图标不显示问题
  packages/devui-vue/devui/modal/src/composables/use-draggable.ts
  packages/devui-vue/devui/modal/src/modal.tsx
  packages/devui-vue/docs/.vitepress/config/head.ts
  packages/devui-vue/docs/.vitepress/devui-theme/index.js
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: bug, PR: unreviewed

#1229 test(notification): test manual click close
  packages/devui-vue/devui/notification/__tests__/notification.spec.tsx
Labels: PR: unreviewed, unit-test

#1235 fix(button): 修改图标按钮尺寸大小不一的情况
  packages/devui-vue/devui/button/src/button.scss
  packages/devui-vue/docs/components/button/index.md
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1237 docs: update overview docs
  packages/devui-vue/docs/components/overview/index.md
Labels: PR: unreviewed, ignore-for-release

#1238 fix: 更新弹出类组件的层级，避免被遮挡
  packages/devui-vue/devui/auto-complete/src/auto-complete.tsx
  packages/devui-vue/devui/cascader/src/cascader.scss
  packages/devui-vue/devui/cascader/src/cascader.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/range-date-picker-pro.tsx
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro.tsx
  packages/devui-vue/devui/drawer/src/drawer-types.ts
  packages/devui-vue/devui/drawer/src/drawer.tsx
  packages/devui-vue/devui/dropdown/src/use-dropdown.ts
  packages/devui-vue/devui/editable-select/src/editable-select.tsx
  packages/devui-vue/devui/image-preview/src/image-preview.scss
  packages/devui-vue/devui/modal/src/modal-types.ts
  packages/devui-vue/devui/modal/src/modal.scss
  packages/devui-vue/devui/modal/src/modal.tsx
  packages/devui-vue/devui/notification/src/notification.scss
  packages/devui-vue/devui/popover/src/use-popover.ts
  packages/devui-vue/devui/select/src/select.tsx
  packages/devui-vue/devui/time-picker/src/time-picker.tsx
  packages/devui-vue/docs/components/modal/index.md
Labels: bug, PR: unreviewed

#1239 fix(Select): 解决多选双向绑定问题
  packages/devui-vue/devui/select/src/components/option.tsx
  packages/devui-vue/devui/select/src/components/select-content.tsx
  packages/devui-vue/devui/select/src/select.scss
  packages/devui-vue/devui/select/src/use-select.ts
Labels: bug, PR: unreviewed

#1241 fix(Table): 滚动时固定列显示阴影
  packages/devui-vue/devui/table/src/components/body/body.scss
  packages/devui-vue/devui/table/src/components/body/body.tsx
  packages/devui-vue/devui/table/src/components/fix-header.tsx
  packages/devui-vue/devui/table/src/components/header/header.scss
  packages/devui-vue/devui/table/src/components/header/header.tsx
  packages/devui-vue/devui/table/src/composables/use-horizontal-scroll.ts
  packages/devui-vue/devui/table/src/composables/use-table-types.ts
  packages/devui-vue/devui/table/src/table.tsx
Labels: PR: unreviewed, feature

#1242 refactor(Table): 解决初始排序错误问题&优化排序代码
  packages/devui-vue/devui/table/src/components/header-th/use-header-th.ts
  packages/devui-vue/devui/table/src/composables/use-sort.ts
  packages/devui-vue/devui/table/src/composables/use-table-types.ts
  packages/devui-vue/devui/table/src/store/index.ts
  packages/devui-vue/devui/table/src/store/store-types.ts
Labels: bug, PR: unreviewed, refactoring

#1240 test(result): Complete the it.todo
  packages/devui-vue/devui/result/__tests__/result.spec.ts
Labels: PR: reviewed-approved, unit-test

#1244 refactor(Table): 重构多选事件触发逻辑
  packages/devui-vue/devui/table/src/components/column/config.tsx
  packages/devui-vue/devui/table/src/store/index.ts
  packages/devui-vue/devui/table/src/store/store-types.ts
  packages/devui-vue/devui/table/src/table.tsx
Labels: PR: unreviewed, refactoring

#1254 fix(editable-select): fix #1253
  packages/devui-vue/devui/editable-select/src/editable-select.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1252 test(editable-select): 增加对allow-clear属性的测试
  packages/devui-vue/devui/editable-select/__tests__/editable-select.spec.ts
Labels: PR: reviewed-approved, unit-test

#1250 docs(message): fix #1247
  packages/devui-vue/docs/components/message/index.md
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1258 fix: 修复Modal和Drawer同时使用异常关闭的问题
  packages/devui-vue/devui/drawer/__tests__/drawer.spec.tsx
  packages/devui-vue/devui/drawer/src/drawer-types.ts
  packages/devui-vue/devui/drawer/src/drawer.tsx
  packages/devui-vue/devui/drawer/src/use-drawer.ts
  packages/devui-vue/devui/modal/__tests__/modal.spec.tsx
  packages/devui-vue/devui/modal/src/composables/use-modal.ts
  packages/devui-vue/devui/modal/src/modal-types.ts
  packages/devui-vue/devui/modal/src/modal.scss
  packages/devui-vue/devui/modal/src/modal.tsx
Labels: bug, PR: unreviewed, unit-test, refactoring

#1259 fix(Select): 修复筛选时面板位置错误问题
  packages/devui-vue/devui/select/src/use-select.ts
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1260 fix(Table): 修复列和数据都是异步渲染时，数据渲染失败的问题
  packages/devui-vue/devui/table/src/composables/use-table.ts
  packages/devui-vue/docs/components/table/index.md
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1261 fix(Cascader): 修复动态设置options失效的问题
  packages/devui-vue/devui/cascader/hooks/use-cascader.ts
Labels: bug, PR: unreviewed

#1263 fix(Form): 修复校验提示距离表单控件较远的问题
  packages/devui-vue/devui/checkbox/src/checkbox-group.scss
  packages/devui-vue/devui/form/src/components/form-control/form-control.scss
  packages/devui-vue/devui/form/src/components/form-control/form-control.tsx
  packages/devui-vue/devui/radio/src/radio-group.scss
  packages/devui-vue/docs/components/form/index.md
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1268 feat(Tree): 增加收起展开动画效果
  packages/devui-vue/devui/tree/src/tree.scss
  packages/devui-vue/devui/tree/src/tree.tsx
  packages/devui-vue/docs/components/tree/index.md
Labels: PR: unreviewed, feature

#1271 fix(Search): 刷新无边框样式
  packages/devui-vue/devui/search/src/search.scss
Labels: bug, PR: unreviewed

#1270 fix(TimePicker): 修复回显数据与format格式不一致问题
  packages/devui-vue/devui/time-picker/src/components/popup-line/index.tsx
  packages/devui-vue/devui/time-picker/src/components/popup-line/popup-line-types.ts
  packages/devui-vue/devui/time-picker/src/components/time-popup/index.tsx
  packages/devui-vue/devui/time-picker/src/components/time-popup/time-popup-types.ts
  packages/devui-vue/devui/time-picker/src/composables/use-time-picker.ts
Labels: bug, PR: unreviewed

#1265 test(switch): test color prop
  packages/devui-vue/devui/switch/__tests__/switch.spec.ts
Labels: PR: reviewed-approved, unit-test

#1280 fix(Input): 优化不同size对应高度，解决清空图标显示问题
  packages/devui-vue/devui/icon/src/icon.scss
  packages/devui-vue/devui/icon/src/icon.tsx
  packages/devui-vue/devui/input/src/input.scss
  packages/devui-vue/devui/input/src/input.tsx
Labels: bug, PR: unreviewed

#1282 fix(Table): 样式调整
  packages/devui-vue/devui/table/src/components/body/body.scss
  packages/devui-vue/docs/components/table/index.md
Labels: bug, PR: unreviewed

#1281 fix(Search): 无边框不设置背景色
  packages/devui-vue/devui/search/src/search.scss
Labels: bug, PR: unreviewed

#1279 fix(Notification): 修复鼠标移入后自动关闭失效的问题
  packages/devui-vue/devui/notification/src/notification-service.tsx
  packages/devui-vue/devui/notification/src/notification.tsx
  packages/devui-vue/devui/notification/src/use-notification.ts
Labels: bug, PR: unreviewed

#1278 fix(Pagination): 优化组件样式
  packages/devui-theme/src/theme-collection/extend-theme.ts
  packages/devui-vue/devui/locale/lang/zh-cn.ts
  packages/devui-vue/devui/pagination/src/components/page-link-icons.tsx
  packages/devui-vue/devui/pagination/src/components/page-nums.tsx
  packages/devui-vue/devui/pagination/src/components/page-size.tsx
  packages/devui-vue/devui/pagination/src/pagination-types.ts
  packages/devui-vue/devui/pagination/src/pagination.scss
  packages/devui-vue/devui/pagination/src/pagination.tsx
  packages/devui-vue/devui/styles-var/private/_corner.scss
Labels: bug, PR: unreviewed

#1283 chore: release v1.0.0
  packages/devui-vue/package.json
Labels: PR: unreviewed, ignore-for-release, v1.0.0
