Repository DevCloudFE/vue-devui, pull requests merged in 2022-03, with the labels that each got.

#193 feat(drawer): add showAnimation prop
  packages/devui-vue/devui/drawer/src/components/drawer-body.tsx
  packages/devui-vue/devui/drawer/src/components/drawer-container.tsx
  packages/devui-vue/devui/drawer/src/components/drawer-header.tsx
  packages/devui-vue/devui/drawer/src/drawer-service.tsx
  packages/devui-vue/devui/drawer/src/drawer-types.ts
  packages/devui-vue/devui/drawer/src/drawer.scss
  packages/devui-vue/devui/drawer/src/drawer.tsx
  packages/devui-vue/docs/components/drawer/index.md
Labels: PR: reviewed-approved

#227 fix: fix build error caused by lodash-es
  packages/devui-vue/devui/drawer/src/drawer-service.tsx
Labels: PR: unreviewed

#229 fix(progress): fix progress import error
  packages/devui-vue/devui/progress/index.ts
Labels: PR: unreviewed

#231 docs: add change theme
  packages/devui-vue/docs/.vitepress/devui-theme/components/NavBar.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/NavBarTitle.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/icons/Theme.vue
  packages/devui-vue/docs/.vitepress/devui-theme/styles/layout.scss
Labels: PR: unreviewed

#232 fix(Table): 修复列排序bug；d-column增加默认插槽；抽离部分逻辑，降低圈复杂度
  packages/devui-vue/devui/table/src/column/use-column.ts
  packages/devui-vue/devui/table/src/fix-header.tsx
  packages/devui-vue/devui/table/src/normal-header.tsx
  packages/devui-vue/devui/table/src/store/index.ts
  packages/devui-vue/devui/table/src/table.tsx
  packages/devui-vue/docs/components/table/index.md
Labels: PR: reviewed-approved

#230 fix(Button): 优化Button组件API，抽离逻辑，更新其他组件demo中Button的用法
  packages/devui-vue/devui/button/index.ts
  packages/devui-vue/devui/button/src/button-types.ts
  packages/devui-vue/devui/button/src/button.scss
  packages/devui-vue/devui/button/src/button.tsx
  packages/devui-vue/devui/button/src/use-button.ts
  packages/devui-vue/devui/style/theme/_color.scss
  packages/devui-vue/docs/components/button/index.md
  packages/devui-vue/docs/components/carousel/index.md
  packages/devui-vue/docs/components/form/index.md
  packages/devui-vue/docs/components/loading/index.md
  packages/devui-vue/docs/components/modal/index.md
  packages/devui-vue/docs/components/pagination/index.md
  packages/devui-vue/docs/components/popover/index.md
  packages/devui-vue/docs/components/table/index.md
  packages/devui-vue/docs/components/toast/index.md
  packages/devui-vue/docs/components/tooltip/index.md
  packages/devui-vue/docs/components/upload/index.md
Labels: PR: reviewed-approved

#234 refactor(fullscreen): optimize fullscreen api and demo
  packages/devui-vue/devui/fullscreen/src/composables/use-fullscreen.ts
  packages/devui-vue/devui/fullscreen/src/composables/use-keydown.ts
  packages/devui-vue/devui/fullscreen/src/fullscreen-types.ts
  packages/devui-vue/devui/fullscreen/src/fullscreen.scss
  packages/devui-vue/devui/fullscreen/src/fullscreen.tsx
  packages/devui-vue/devui/fullscreen/src/utils.ts
  packages/devui-vue/docs/components/fullscreen/index.md
Labels: PR: unreviewed

#233 refactor(Select): 补充样式
  packages/devui-vue/devui/select/src/select.scss
Labels: PR: reviewed-approved

#235 refactor(drawer): 重构drawer组件
  packages/devui-vue/devui-cli/commands/build.js
  packages/devui-vue/devui/drawer/index.ts
  packages/devui-vue/devui/drawer/src/components/drawer-body.scss
  packages/devui-vue/devui/drawer/src/components/drawer-body.tsx
  packages/devui-vue/devui/drawer/src/components/drawer-container.tsx
  packages/devui-vue/devui/drawer/src/components/drawer-header.scss
  packages/devui-vue/devui/drawer/src/components/drawer-header.tsx
  packages/devui-vue/devui/drawer/src/components/drawer-overlay.scss
  packages/devui-vue/devui/drawer/src/components/drawer-overlay.tsx
  packages/devui-vue/devui/drawer/src/drawer-service.tsx
  packages/devui-vue/devui/drawer/src/drawer-types.ts
  packages/devui-vue/devui/drawer/src/drawer.scss
  packages/devui-vue/devui/drawer/src/drawer.tsx
  packages/devui-vue/devui/drawer/src/use-drawer.ts
  packages/devui-vue/devui/shared/util/lock-scroll.ts
  packages/devui-vue/docs/components/drawer/index.md
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: PR: reviewed-approved

#236 refactor(list): 封装List组件基础样式
  packages/devui-vue/devui/list/index.ts
  packages/devui-vue/devui/list/src/list-item.scss
  packages/devui-vue/devui/list/src/list-item.tsx
  packages/devui-vue/devui/list/src/list.scss
  packages/devui-vue/devui/list/src/list.tsx
  packages/devui-vue/docs/components/list/index.md
Labels: PR: reviewed-approved

#238 refactor(Overlay): 重构flexible-overlay
  packages/devui-vue/devui-cli/commands/build.js
  packages/devui-vue/devui/badge/index.ts
  packages/devui-vue/devui/badge/src/badge-types.ts
  packages/devui-vue/devui/badge/src/badge.tsx
  packages/devui-vue/devui/overlay/index.ts
  packages/devui-vue/devui/overlay/src/fixed-overlay.tsx
  packages/devui-vue/devui/overlay/src/flexible-overlay.scss
  packages/devui-vue/devui/overlay/src/flexible-overlay.tsx
  packages/devui-vue/devui/overlay/src/flexible-utils.ts
  packages/devui-vue/devui/overlay/src/overlay-types.ts
  packages/devui-vue/devui/overlay/src/use-flexible-overlay.ts
  packages/devui-vue/docs/components/badge/index.md
  packages/devui-vue/docs/components/overlay/index.md
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: PR: reviewed-approved

#239 refactor: add editorconfig file
  .editorconfig
Labels: PR: reviewed-approved

#241 refactor: toast
  packages/devui-vue/devui/notification/index.ts
  packages/devui-vue/devui/notification/src/notification-icon-close.tsx
  packages/devui-vue/devui/notification/src/notification-image.tsx
  packages/devui-vue/devui/notification/src/notification-service.tsx
  packages/devui-vue/devui/notification/src/notification-types.ts
  packages/devui-vue/devui/notification/src/notification.scss
  packages/devui-vue/devui/notification/src/notification.tsx
  packages/devui-vue/devui/notification/src/use-notification.ts
  packages/devui-vue/devui/toast/__tests__/toast.spec.ts
  packages/devui-vue/devui/toast/index.ts
  packages/devui-vue/devui/toast/src/hooks/use-toast-constant.ts
  packages/devui-vue/devui/toast/src/hooks/use-toast-event.ts
  packages/devui-vue/devui/toast/src/hooks/use-toast-helper.ts
  packages/devui-vue/devui/toast/src/hooks/use-toast-z-index.ts
  packages/devui-vue/devui/toast/src/toast-icon-close.tsx
  packages/devui-vue/devui/toast/src/toast-image.tsx
  packages/devui-vue/devui/toast/src/toast-service.ts
  packages/devui-vue/devui/toast/src/toast-types.ts
  packages/devui-vue/devui/toast/src/toast.tsx
  packages/devui-vue/devui/upload/src/upload.tsx
  packages/devui-vue/docs/components/notification/index.md
  packages/devui-vue/docs/components/toast/index.md
Labels: PR: reviewed-approved

#242 refactor(Modal): 重构Modal
  packages/devui-vue/devui/modal/index.ts
  packages/devui-vue/devui/modal/src/body.tsx
  packages/devui-vue/devui/modal/src/dialog-types.ts
  packages/devui-vue/devui/modal/src/dialog.tsx
  packages/devui-vue/devui/modal/src/footer.tsx
  packages/devui-vue/devui/modal/src/header.tsx
  packages/devui-vue/devui/modal/src/modal-types.ts
  packages/devui-vue/devui/modal/src/modal.scss
  packages/devui-vue/devui/modal/src/modal.tsx
  packages/devui-vue/devui/modal/src/services/dialog-service.ts
  packages/devui-vue/devui/modal/src/services/modal-service.ts
  packages/devui-vue/devui/modal/src/use-modal.ts
  packages/devui-vue/docs/components/modal/index.md
Labels: PR: reviewed-approved

#153 feat: 完善accordion路由跳转部分，并添加demo和api文档
  packages/devui-vue/devui/accordion/src/accordion-item-hreflink.tsx
  packages/devui-vue/devui/accordion/src/accordion-item-routerlink.tsx
  packages/devui-vue/devui/accordion/src/accordion-list.tsx
  packages/devui-vue/devui/accordion/src/composables/use-active.ts
  packages/devui-vue/devui/accordion/src/composables/use-toggle.ts
  packages/devui-vue/docs/components/accordion/index.md
Labels: PR: reviewed-approved

#244 refactor(Tooltip): 重构Tooltip
  packages/devui-vue/devui/tooltip/index.ts
  packages/devui-vue/devui/tooltip/src/tooltip-types.ts
  packages/devui-vue/devui/tooltip/src/tooltip.scss
  packages/devui-vue/devui/tooltip/src/tooltip.tsx
  packages/devui-vue/devui/tooltip/src/use-tooltip.ts
  packages/devui-vue/docs/components/tooltip/index.md
Labels: PR: reviewed-approved

#247 refactor(form): 提取校验函数到use-validate
  packages/devui-vue/devui/form/src/use-validate.ts
Labels: PR: reviewed-approved, refactoring

#248 refactor(form): 完成d-validate指令功能
  packages/devui-vue/devui/form/src/directive/d-validate.ts
  packages/devui-vue/devui/form/src/directive/style.scss
  packages/devui-vue/devui/form/src/form-types.ts
  packages/devui-vue/devui/form/src/util/index.ts
Labels: PR: reviewed-approved

#240 refactor: search
  packages/devui-vue/devui/search/src/hooks/use-search-keydown.ts
  packages/devui-vue/devui/search/src/hooks/use-search-keywords.ts
  packages/devui-vue/devui/search/src/search-types.ts
  packages/devui-vue/devui/search/src/search.tsx
  packages/devui-vue/docs/components/search/index.md
Labels: PR: reviewed-approved

#246 refactor(form): 给样式名增加devui-前缀
  packages/devui-vue/devui/form/src/directive/d-validate-rules.ts
  packages/devui-vue/devui/form/src/directive/style.scss
  packages/devui-vue/devui/form/src/form-control/form-control.scss
  packages/devui-vue/devui/form/src/form-control/form-control.tsx
  packages/devui-vue/devui/form/src/form-item/form-item.scss
  packages/devui-vue/devui/form/src/form-item/form-item.tsx
  packages/devui-vue/devui/form/src/form-label/form-label.scss
  packages/devui-vue/devui/form/src/form-label/form-label.tsx
  packages/devui-vue/devui/form/src/form-operation/form-operation.scss
  packages/devui-vue/devui/form/src/form-operation/form-operation.tsx
  packages/devui-vue/devui/form/src/form.scss
  packages/devui-vue/devui/form/src/form.tsx
  packages/devui-vue/devui/style/core/_form.scss
Labels: PR: reviewed-approved

#249 refactor(Upload): refactor Upload
  packages/devui-vue/devui/upload/index.ts
  packages/devui-vue/devui/upload/src/composables/use-select-files.ts
  packages/devui-vue/devui/upload/src/composables/use-upload.ts
  packages/devui-vue/devui/upload/src/file-drop-directive.ts
  packages/devui-vue/devui/upload/src/file-uploader.ts
  packages/devui-vue/devui/upload/src/i18n-upload.ts
  packages/devui-vue/devui/upload/src/single-upload.tsx
  packages/devui-vue/devui/upload/src/upload-types.ts
  packages/devui-vue/devui/upload/src/upload.scss
  packages/devui-vue/devui/upload/src/upload.tsx
  packages/devui-vue/devui/upload/src/use-select-files.ts
  packages/devui-vue/devui/upload/src/use-upload.ts
  packages/devui-vue/docs/components/upload/index.md
Labels: PR: reviewed-approved

#251 refactor(Dropdown): refactor Dropdown
  packages/devui-vue/devui/dropdown/index.ts
  packages/devui-vue/devui/dropdown/src/dropdown-directive.ts
  packages/devui-vue/devui/dropdown/src/dropdown-menu-types.ts
  packages/devui-vue/devui/dropdown/src/dropdown-menu.tsx
  packages/devui-vue/devui/dropdown/src/dropdown-types.ts
  packages/devui-vue/devui/dropdown/src/dropdown.scss
  packages/devui-vue/devui/dropdown/src/dropdown.tsx
  packages/devui-vue/devui/dropdown/src/use-dropdown.ts
  packages/devui-vue/docs/components/dropdown/index.md
Labels: PR: reviewed-approved

#252 refactor(Tabs): refactor Tabs
  packages/devui-vue/devui/tabs/src/tab.tsx
  packages/devui-vue/devui/tabs/src/tabs.tsx
  packages/devui-vue/docs/components/tabs/index.md
Labels: PR: reviewed-approved

#254 build: 完善脚本支持在左侧导航显示主题定制的文档
  packages/devui-vue/devui-cli/templates/vitepress-sidebar.js
Labels: PR: unreviewed

#256 fix: fix ls-lint/eslint/stylelint
  .husky/pre-commit
  .ls-lint.yml
  package.json
  packages/devui-vue/devui/color-picker/src/components/color-alpha-slider/color-alpha-slider.tsx
  packages/devui-vue/devui/color-picker/src/components/color-hue-slider/color-hue-slider.tsx
  packages/devui-vue/devui/color-picker/src/components/color-palette/color-palette.tsx
  packages/devui-vue/devui/color-picker/src/utils/dom-dragger.ts
Labels: PR: unreviewed

#257 style: fix stylelint errors
  packages/devui-vue/devui/cascader/components/cascader-tag/index.scss
  packages/devui-vue/devui/comment/src/comment.scss
  packages/devui-vue/devui/editable-select/src/editable-select.scss
  packages/devui-vue/devui/form/src/directive/style.scss
  packages/devui-vue/devui/form/src/form-item/form-item.scss
  packages/devui-vue/devui/upload/src/upload.scss
Labels: PR: unreviewed

#262 refactor: 优化组件命名并修复lint问题
  .husky/pre-commit
  .ls-lint.yml
  package.json
  packages/devui-vue/devui-cli/templates/vitepress-sidebar.js
  packages/devui-vue/devui/cascader/components/cascader-tag/index.scss
  packages/devui-vue/devui/color-picker/src/components/color-alpha-slider/color-alpha-slider.tsx
  packages/devui-vue/devui/color-picker/src/components/color-hue-slider/color-hue-slider.tsx
  packages/devui-vue/devui/color-picker/src/components/color-palette/color-palette.tsx
  packages/devui-vue/devui/color-picker/src/utils/dom-dragger.ts
  packages/devui-vue/devui/comment/src/comment.scss
  packages/devui-vue/devui/editable-select/src/editable-select.scss
  packages/devui-vue/devui/form/src/directive/style.scss
  packages/devui-vue/devui/form/src/form-item/form-item.scss
  packages/devui-vue/devui/time-axis/__tests__/time-axis.spec.ts
  packages/devui-vue/devui/time-axis/index.ts
  packages/devui-vue/devui/timeline/__tests__/timeline.spec.ts
  packages/devui-vue/devui/timeline/index.ts
  packages/devui-vue/devui/timeline/src/components/timeline-item/index.tsx
  packages/devui-vue/devui/timeline/src/components/timeline-item/types.ts
  packages/devui-vue/devui/timeline/src/timeline-types.ts
  packages/devui-vue/devui/timeline/src/timeline.scss
  packages/devui-vue/devui/timeline/src/timeline.tsx
  packages/devui-vue/devui/upload/src/upload.scss
  packages/devui-vue/docs/components/timeline/index.md
  packages/devui-vue/package.json
  packages/devui-vue/tsconfig.json
  pnpm-lock.yaml
Labels: PR: unreviewed

#267 refactor: 优化部分组件的api/demo命名
  packages/devui-vue/docs/components/alert/index.md
  packages/devui-vue/docs/components/icon/index.md
  packages/devui-vue/docs/components/panel/index.md
Labels: PR: unreviewed

#271 feat: Badge组件增加common类型
  packages/devui-vue/devui/badge/src/badge-types.ts
  packages/devui-vue/devui/badge/src/badge.scss
  packages/devui-vue/docs/components/badge/index.md
Labels: PR: reviewed-approved

#270 feat: 修改Tab和Button无限主题的颜色
  packages/devui-theme/src/theme-collection/extend-theme-vue.scss
  packages/devui-vue/devui/button/src/button.tsx
  packages/devui-vue/docs/.vitepress/devui-theme/styles/index.scss
Labels: PR: reviewed-approved

#272 refactor: 同步devui-theme
  packages/devui-theme/package.json
  packages/devui-theme/scripts/create-package.js
  packages/devui-theme/scripts/release.js
  packages/devui-theme/src/styles-var/devui-var.scss
  packages/devui-theme/src/styles-var/private/_font-size.scss
  packages/devui-theme/src/styles-var/private/_variables.scss
  packages/devui-theme/tsconfig.json
  packages/devui-theme/tsconfig.node.json
  packages/devui-theme/vite.config.theme-collection.ts
  packages/devui-theme/vite.config.theme.ts
  packages/devui-theme/vite.config.ts
  pnpm-lock.yaml
Labels: PR: reviewed-approved

#268 chore: 生成 changelog.md
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: PR: reviewed-approved

#222 fix(panel): fix issues #219
  packages/devui-theme/vite.config.theme.collection.ts
  packages/devui-vue/devui/panel/src/body/panel-body.tsx
  packages/devui-vue/devui/panel/src/foot/panel-footer.tsx
  packages/devui-vue/devui/panel/src/header/panel-header.tsx
  packages/devui-vue/devui/panel/src/panel.tsx
  packages/devui-vue/devui/panel/src/panel.type.ts
  packages/devui-vue/devui/panel/src/store/store.ts
  packages/devui-vue/docs/components/panel/index.md
Labels: PR: reviewed-approved

#275 style(skeleton): 手动修复 Eslint 报错
  packages/devui-vue/devui/skeleton/__tests__/skeleton-item.spec.ts
  packages/devui-vue/devui/skeleton/src/item/item.tsx
  packages/devui-vue/devui/skeleton/src/skeleton.tsx
Labels: PR: reviewed-approved

#273 refactor(icon): 优化Icon组件，修复ESLint问题
  packages/devui-vue/devui/icon/__tests__/icon.spec.ts
  packages/devui-vue/devui/icon/index.ts
  packages/devui-vue/devui/icon/src/icon-types.ts
  packages/devui-vue/devui/icon/src/icon.tsx
Labels: PR: unreviewed

#274 refactor(pagination): 优化Pagination组件，修复ESLint问题
  packages/devui-vue/devui/pagination/__tests__/pagination.spec.ts
  packages/devui-vue/devui/pagination/index.ts
  packages/devui-vue/devui/pagination/src/components/config-menu.tsx
  packages/devui-vue/devui/pagination/src/pagination-types.ts
  packages/devui-vue/devui/pagination/src/pagination.tsx
Labels: PR: unreviewed

#276 feat(Dropdown): 新增参数、方法等
  packages/devui-vue/devui/dropdown/src/dropdown-menu-types.ts
  packages/devui-vue/devui/dropdown/src/dropdown-menu.tsx
  packages/devui-vue/devui/dropdown/src/dropdown-types.ts
  packages/devui-vue/devui/dropdown/src/dropdown.tsx
  packages/devui-vue/devui/dropdown/src/use-dropdown.ts
  packages/devui-vue/devui/overlay/src/flexible-overlay.tsx
  packages/devui-vue/devui/overlay/src/overlay-types.ts
  packages/devui-vue/devui/overlay/src/use-flexible-overlay.ts
  packages/devui-vue/docs/components/dropdown/index.md
Labels: PR: reviewed-approved

#39 fix: input-number组件size大小样式调整优化
  packages/devui-vue/devui/input-number/src/input-number.scss
Labels: PR: reviewed-approved

#291 refactor(pagination): 导出Pagination组件的类型文件
  packages/devui-vue/devui/pagination/index.ts
  packages/devui-vue/devui/pagination/src/pagination-types.ts
  packages/devui-vue/devui/pagination/src/pagination.tsx
Labels: PR: unreviewed

#287 refactor(status): 优化Status组件的目录结构
  packages/devui-vue/devui/status/index.ts
  packages/devui-vue/devui/status/src/status-types.ts
  packages/devui-vue/devui/status/src/status.scss
  packages/devui-vue/devui/status/src/status.tsx
Labels: PR: unreviewed

#288 refactor(panel): 优化Panel组件的目录结构并修复ESLint问题
  packages/devui-vue/devui/panel/__tests__/panel.spec.ts
  packages/devui-vue/devui/panel/index.ts
  packages/devui-vue/devui/panel/src/components/panel-body.tsx
  packages/devui-vue/devui/panel/src/components/panel-footer.tsx
  packages/devui-vue/devui/panel/src/components/panel-header.tsx
  packages/devui-vue/devui/panel/src/foot/panel-footer.tsx
  packages/devui-vue/devui/panel/src/panel-types.ts
  packages/devui-vue/devui/panel/src/panel.scss
  packages/devui-vue/devui/panel/src/panel.tsx
  packages/devui-vue/devui/panel/src/store/index.ts
  packages/devui-vue/devui/panel/src/store/store.ts
Labels: PR: unreviewed

#289 refactor(search): 优化Search组件目录结构
  packages/devui-vue/devui/search/index.ts
  packages/devui-vue/devui/search/src/composables/use-search-class.ts
  packages/devui-vue/devui/search/src/composables/use-search-keydown.ts
  packages/devui-vue/devui/search/src/composables/use-search-keywords.ts
  packages/devui-vue/devui/search/src/search.tsx
Labels: PR: unreviewed

#296 docs: add ElsaOOo for maintenance
  README.md
Labels: PR: unreviewed

#298 docs: 优化快速开始和贡献指南文档
  packages/devui-vue/docs/CONTRIBUTING.md
  packages/devui-vue/docs/index.md
Labels: PR: unreviewed

#299 refactor(radio): 修复 eslint 报错、格式化代码统一代码风格
  packages/devui-vue/devui/radio/index.ts
  packages/devui-vue/devui/radio/src/radio-group.tsx
  packages/devui-vue/devui/radio/src/radio.scss
  packages/devui-vue/devui/radio/src/radio.tsx
Labels: PR: reviewed-approved, refactoring

#300 build: 增加发布npm包的脚本
  commitlint.config.js
  packages/devui-vue/devui-cli/commands/release.js
  packages/devui-vue/devui-cli/index.js
  packages/devui-vue/package.json
Labels: enhancement, PR: unreviewed

#301 build: 只构建status等于100%的组件
  packages/devui-vue/devui-cli/commands/build.js
Labels: enhancement, PR: unreviewed

#302 feat: 修复 Splitter ESLint 规范建议问题
  packages/devui-vue/devui/splitter/__mocks__/event-helper.ts
  packages/devui-vue/devui/splitter/__tests__/splitter.spec.ts
  packages/devui-vue/devui/splitter/src/splitter-bar.tsx
  packages/devui-vue/devui/splitter/src/splitter-pane.tsx
  packages/devui-vue/devui/splitter/src/splitter-store.ts
  packages/devui-vue/devui/splitter/src/splitter-types.ts
  packages/devui-vue/devui/splitter/src/splitter.tsx
  packages/devui-vue/devui/splitter/src/util/d-resize-directive.ts
Labels: PR: reviewed-approved

#303 docs: 完善组件文档和贡献者文档
  packages/devui-vue/docs/.vitepress/devui-theme/components/Page.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributor.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
  packages/devui-vue/docs/CONTRIBUTING.md
  packages/devui-vue/docs/components/accordion/index.md
Labels: PR: unreviewed

#304 docs: 新增 radio 组件贡献者信息
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
Labels: PR: reviewed-approved, ignore-for-release

#306 docs: 完善组件贡献者
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
Labels: PR: unreviewed, ignore-for-release

#307 fix: 修复贡献者头像错位问题
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributor.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
Labels: PR: unreviewed, ignore-for-release

#309 fix(select): 修复eslint的错误和警告
  packages/devui-vue/devui/select/hooks/use-cache-options.ts
  packages/devui-vue/devui/select/index.ts
  packages/devui-vue/devui/select/src/select.tsx
  packages/devui-vue/devui/select/src/use-select.ts
Labels: PR: reviewed-approved

#305 refactor(slider): 修复 eslint 的报错和警告，格式化代码
  .gitignore
  packages/devui-vue/devui/slider/index.ts
  packages/devui-vue/devui/slider/src/slider.tsx
Labels: PR: reviewed-approved

#311 docs: add contributor avatar
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
Labels: PR: unreviewed, ignore-for-release

#312 docs(panel): 修复了英文文档中的错误
  packages/devui-vue/docs/en-US/components/panel/index.md
Labels: 📄documentation, PR: reviewed-approved

#318 fix: CONTRIBUTING.md link
  CONTRIBUTING.md
Labels: PR: reviewed-approved

#317 feat: 新增useNamespace hooks，采用Bem规范统一样式命名
  packages/devui-vue/devui/shared/hooks/use-namespace.ts
Labels: PR: reviewed-approved

#319 docs: add contributing docs
  CONTRIBUTING.md
  packages/devui-vue/docs/.vitepress/config/nav.ts
  packages/devui-vue/docs/contributing/development-specification/api-demo-design/index.md
  packages/devui-vue/docs/contributing/development-specification/coding-specification/index.md
  packages/devui-vue/docs/contributing/development-specification/component-document/index.md
  packages/devui-vue/docs/contributing/development-specification/directory-organization/index.md
  packages/devui-vue/docs/contributing/development-specification/index.md
  packages/devui-vue/docs/contributing/index.md
Labels: 📄documentation, PR: unreviewed

#320 fix: 修复本地启动首次访问出现白页的问题
  packages/devui-vue/docs/vite.config.ts
Labels: 🐛 bug, PR: unreviewed

#321 fix: 修复控制台报dLoading重复注册的警告问题
  packages/devui-vue/devui/table/index.ts
  packages/devui-vue/devui/table/src/table.tsx
Labels: 🐛 bug, PR: unreviewed

#325 docs: update contributors
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
Labels: 📄documentation, PR: unreviewed, ignore-for-release

#328 fix(auto-complete): 修复eslint报错问题；修复appendToBody改动bug
  packages/devui-vue/devui/auto-complete/src/auto-complete-types.ts
  packages/devui-vue/devui/auto-complete/src/auto-complete.scss
  packages/devui-vue/devui/auto-complete/src/auto-complete.tsx
  packages/devui-vue/devui/auto-complete/src/components/dropdown.tsx
  packages/devui-vue/devui/auto-complete/src/composables/use-custom-template.ts
  packages/devui-vue/devui/auto-complete/src/composables/use-input-handle.ts
  packages/devui-vue/devui/auto-complete/src/composables/use-searchfn.ts
  packages/devui-vue/devui/auto-complete/src/composables/use-select-handle.ts
Labels: PR: reviewed-approved

#330 feat(Table): 修改Table组件目录结构和部分API文档规范
  packages/devui-vue/devui/table/index.ts
  packages/devui-vue/devui/table/src/components/body/body-types.ts
  packages/devui-vue/devui/table/src/components/body/body.scss
  packages/devui-vue/devui/table/src/components/body/body.tsx
  packages/devui-vue/devui/table/src/components/body/use-body.ts
  packages/devui-vue/devui/table/src/components/colgroup/colgroup.tsx
  packages/devui-vue/devui/table/src/components/column/column-types.ts
  packages/devui-vue/devui/table/src/components/column/column.tsx
  packages/devui-vue/devui/table/src/components/column/use-column.ts
  packages/devui-vue/devui/table/src/components/filter/filter.scss
  packages/devui-vue/devui/table/src/components/filter/filter.tsx
  packages/devui-vue/devui/table/src/components/filter/index.ts
  packages/devui-vue/devui/table/src/components/fix-header.tsx
  packages/devui-vue/devui/table/src/components/header/header.scss
  packages/devui-vue/devui/table/src/components/header/header.tsx
  packages/devui-vue/devui/table/src/components/header/header.type.ts
  packages/devui-vue/devui/table/src/components/header/use-header.ts
  packages/devui-vue/devui/table/src/components/normal-header.tsx
  packages/devui-vue/devui/table/src/components/sort/index.ts
  packages/devui-vue/devui/table/src/components/sort/sort.scss
  packages/devui-vue/devui/table/src/components/sort/sort.tsx
  packages/devui-vue/devui/table/src/composable/use-table.ts
  packages/devui-vue/devui/table/src/header/sort/sort.tsx
  packages/devui-vue/devui/table/src/store/index.ts
  packages/devui-vue/devui/table/src/table-types.ts
  packages/devui-vue/devui/table/src/table.tsx
  packages/devui-vue/devui/table/src/table.type.ts
  packages/devui-vue/docs/components/table/index.md
Labels: PR: reviewed-approved

#331 chore(tree): 修复部分ESLint问题
  packages/devui-vue/devui/tree/__tests__/tree.spec.ts
  packages/devui-vue/devui/tree/index.ts
  packages/devui-vue/devui/tree/src/composables/use-checked.ts
  packages/devui-vue/devui/tree/src/composables/use-draggable.ts
  packages/devui-vue/devui/tree/src/composables/use-merge-node.ts
  packages/devui-vue/devui/tree/src/composables/use-operate.tsx
  packages/devui-vue/devui/tree/src/composables/use-toggle.ts
  packages/devui-vue/devui/tree/src/tree-node-content.tsx
  packages/devui-vue/devui/tree/src/tree-types.ts
  packages/devui-vue/devui/tree/src/tree.tsx
  packages/devui-vue/devui/tree/src/util.ts
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
Labels: PR: unreviewed

#332 fix(Select): 修改Select组件的输入框背景色
  packages/devui-vue/devui/select/src/select.scss
  packages/devui-vue/devui/style/theme/_color.scss
Labels: PR: reviewed-approved

#333 fix(Radio): 修改Radio组件圆圈外层选中和禁用样式，个别动画参数用变量代替
  packages/devui-vue/devui/radio/src/radio.scss
  packages/devui-vue/devui/radio/src/radio.tsx
  packages/devui-vue/devui/style/theme/_color.scss
Labels: PR: reviewed-approved

#335 fix(Table): 替换Table组件部分样式为样式变量
  packages/devui-vue/devui/table/src/components/body/body.scss
  packages/devui-vue/devui/table/src/components/header/header.scss
Labels: PR: reviewed-approved

#334 fix(Progress): 替换Progress组件部分样式为样式变量
  .prettierrc
  packages/devui-vue/devui/progress/src/progress.scss
  packages/devui-vue/devui/progress/src/progress.tsx
Labels: PR: reviewed-approved

#338 chore: Tree 组件eslint报错修复
  packages/devui-vue/devui/tree/src/composables/use-draggable.ts
  packages/devui-vue/devui/tree/src/composables/use-lazy.ts
  packages/devui-vue/devui/tree/src/tree-types.ts
Labels: PR: reviewed-approved, refactoring

#339 fix: fix popover eslint errors
  packages/devui-vue/devui/popover/src/popover-icons.tsx
  packages/devui-vue/devui/popover/src/use-popover.ts
  packages/devui-vue/docs/en-US/components/popover/index.md
Labels: PR: reviewed-approved, refactoring

#341 feat(Table): 使用Rem规范修改Table组件样式命名
  packages/devui-vue/devui/table/src/components/body/body.scss
  packages/devui-vue/devui/table/src/components/body/body.tsx
  packages/devui-vue/devui/table/src/components/fix-header.tsx
  packages/devui-vue/devui/table/src/components/header/header.scss
  packages/devui-vue/devui/table/src/components/header/header.tsx
  packages/devui-vue/devui/table/src/composable/use-table.ts
  packages/devui-vue/devui/table/src/table.scss
  packages/devui-vue/devui/table/src/table.tsx
  packages/devui-vue/docs/components/table/index.md
Labels: PR: reviewed-approved, refactoring

#342 refactor(Table): TD和TH组件从body、header中抽离,解决一个文件定义多个组件的eslint报错
  packages/devui-vue/devui/table/src/components/body-td/body-td.tsx
  packages/devui-vue/devui/table/src/components/body/body.tsx
  packages/devui-vue/devui/table/src/components/header-th/header-th.tsx
  packages/devui-vue/devui/table/src/components/header-th/use-header-th.ts
  packages/devui-vue/devui/table/src/components/header/header.tsx
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
Labels: PR: unreviewed

#346 docs(nav): update playground link
  packages/devui-vue/docs/.vitepress/config/nav.ts
Labels: 📄documentation, PR: reviewed-approved

#348 docs(auto-complete): 完善文档，修改部分关联代码
  packages/devui-vue/devui/auto-complete/src/auto-complete.scss
  packages/devui-vue/devui/auto-complete/src/composables/use-custom-template.ts
  packages/devui-vue/docs/components/auto-complete/index.md
  packages/devui-vue/docs/en-US/components/auto-complete/api-en.md
Labels: 📄documentation, PR: reviewed-approved, refactoring

#349 fix(tag): 修复了color不随主题切换而变化的bug
  packages/devui-vue/devui/tag/src/hooks/use-class.ts
  packages/devui-vue/devui/tag/src/hooks/use-color.ts
  packages/devui-vue/devui/tag/src/tag.scss
  packages/devui-vue/devui/tag/src/tag.tsx
Labels: 🐛 bug, PR: unreviewed, PR: reviewed-approved

#350 docs(tag): 补全中英文文档
  packages/devui-vue/docs/components/tag/index.md
  packages/devui-vue/docs/en-US/components/tag/index.md
Labels: 📄documentation, PR: unreviewed, PR: reviewed-approved

#347 feat(Table): 完成Table组件合并单元格功能
  packages/devui-vue/devui/table/src/components/body/body.tsx
  packages/devui-vue/devui/table/src/components/body/use-body.ts
  packages/devui-vue/devui/table/src/table-types.ts
  packages/devui-vue/docs/components/table/index.md
Labels: PR: reviewed-approved, ✨ feature

#353 feat(Table): 表格支持sm/md/lg三种大小
  packages/devui-vue/devui/table/src/components/body/body.scss
  packages/devui-vue/devui/table/src/components/body/body.tsx
  packages/devui-vue/devui/table/src/components/header/header.scss
  packages/devui-vue/devui/table/src/components/header/header.tsx
  packages/devui-vue/devui/table/src/composable/use-table.ts
  packages/devui-vue/devui/table/src/table-types.ts
  packages/devui-vue/devui/table/src/table.scss
  packages/devui-vue/docs/components/table/index.md
Labels: PR: unreviewed

#356 test(tree): Tree组件单元测试基本设计
  packages/devui-vue/devui-cli/commands/code-check.js
  packages/devui-vue/devui/tree/__tests__/basic-tree/basic-data.ts
  packages/devui-vue/devui/tree/__tests__/basic-tree/basic-tree.spec.tsx
  packages/devui-vue/devui/tree/__tests__/tree.spec.ts
  packages/devui-vue/devui/tree/src/assets/close.svg
  packages/devui-vue/devui/tree/src/assets/open.svg
  packages/devui-vue/devui/tree/src/components/icon-close.tsx
  packages/devui-vue/devui/tree/src/components/icon-open.tsx
  packages/devui-vue/devui/tree/src/tree-types.ts
  packages/devui-vue/devui/tree/src/tree.tsx
Labels: PR: unreviewed, unit-test, refactoring

#358 fix(tag): 完成组件自检并修改进度为100%
  packages/devui-vue/devui/tag/__tests__/tag.spec.ts
  packages/devui-vue/devui/tag/index.ts
  packages/devui-vue/devui/tag/src/composables/index.ts
  packages/devui-vue/devui/tag/src/composables/use-class.ts
  packages/devui-vue/devui/tag/src/composables/use-color.ts
  packages/devui-vue/devui/tag/src/tag.tsx
Labels: PR: reviewed-approved

#340 fix(ripple): 修复ripple指令eslint 优化 api 优化中英文文档
  packages/devui-vue/devui/ripple/src/options.ts
  packages/devui-vue/devui/ripple/src/utils/create-container-element.ts
  packages/devui-vue/devui/ripple/src/utils/create-ripple-element.ts
  packages/devui-vue/devui/ripple/src/utils/ripple-count.ts
  packages/devui-vue/devui/ripple/src/v-ripple.ts
  packages/devui-vue/docs/components/ripple/index.md
  packages/devui-vue/docs/en-US/components/ripple/index.md
Labels: 📄documentation, PR: unreviewed, PR: reviewed-approved, refactoring

#354 fix: 修复tabs最后一个圆角样式问题
  packages/devui-vue/devui/tabs/src/tabs.scss
Labels: 🐛 bug, PR: reviewed-approved

#355 feat(Table): 新增borderType参数，支持设置表格边框类型
  packages/devui-vue/devui/table/src/components/body/body.scss
  packages/devui-vue/devui/table/src/composable/use-table.ts
  packages/devui-vue/devui/table/src/table-types.ts
  packages/devui-vue/devui/table/src/table.scss
  packages/devui-vue/docs/components/table/index.md
Labels: PR: reviewed-approved, ✨ feature

#359 test(tree): 完善tree组件基本功能的单元测试
  packages/devui-vue/devui/tree/__tests__/basic-tree/basic-tree-data.ts
  packages/devui-vue/devui/tree/__tests__/basic-tree/basic-tree.spec.tsx
  packages/devui-vue/devui/tree/__tests__/checkable-tree/checkable-tree-data.ts
  packages/devui-vue/devui/tree/__tests__/checkable-tree/checkable-tree.spec.tsx
  packages/devui-vue/devui/tree/__tests__/node-merge/node-merge-data.ts
  packages/devui-vue/devui/tree/__tests__/node-merge/node-merge.spec.tsx
  packages/devui-vue/devui/tree/__tests__/tree.spec.ts
  packages/devui-vue/devui/tree/src/composables/use-merge-node.ts
Labels: PR: unreviewed, unit-test

#360 docs: 遮罩层文档添加英文标题
  packages/devui-vue/docs/components/overlay/index.md
Labels: 📄documentation, PR: reviewed-approved

#362 fix(auto-complete): 修复文档demo样式bug
  packages/devui-vue/docs/components/auto-complete/index.md
  packages/devui-vue/docs/en-US/components/auto-complete/api-en.md
Labels: bug, PR: reviewed-approved

#364 fix(statistic): value may be empty bug eslint comp
  packages/devui-vue/devui/statistic/__tests__/statistic.spec.ts
  packages/devui-vue/devui/statistic/src/utils/separator.ts
Labels: bug, PR: reviewed-approved, unit-test

#363 fix(Popover): 修复Popover动态渲染时的bug
  packages/devui-vue/devui/overlay/src/flexible-overlay/use-flexible-overlay.ts
Labels: PR: reviewed-approved

#369 fix: 构建全量包应该将未完成组件排除
  packages/devui-vue/devui-cli/commands/create.js
Labels: bug, PR: unreviewed
