Repository DevCloudFE/vue-devui, pull requests merged in 2022-02, with the labels that each got.

#183 fix: 解决几个网站问题
  packages/devui-vue/docs/.vitepress/devui-theme/Layout.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/BackToTop.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/SideBarLink.js
  packages/devui-vue/docs/.vitepress/devui-theme/styles/sidebar-links.scss
Labels: PR: unreviewed

#184 feat: tree节点拖拽功能
  packages/devui-vue/devui/tree/src/composables/use-draggable.ts
  packages/devui-vue/devui/tree/src/composables/use-merge-node.ts
  packages/devui-vue/devui/tree/src/tree-types.ts
  packages/devui-vue/devui/tree/src/tree.scss
  packages/devui-vue/devui/tree/src/tree.tsx
  packages/devui-vue/devui/tree/src/util.ts
  packages/devui-vue/docs/components/tree/index.md
Labels: PR: reviewed-approved

#168 refactor(statistic): 重构Statistic Api Demo
  packages/devui-vue/devui/statistic/src/statistic-types.ts
  packages/devui-vue/devui/statistic/src/statistic.scss
  packages/devui-vue/devui/statistic/src/statistic.tsx
  packages/devui-vue/devui/statistic/src/utils/animation.ts
  packages/devui-vue/devui/statistic/src/utils/separator.ts
  packages/devui-vue/docs/components/statistic/index.md
  packages/devui-vue/docs/en-US/components/statistic/index.md
Labels: PR: reviewed-approved

#143 feat: Transfer Add Tooltips
  packages/devui-vue/devui/card/__tests__/__snapshots__/card.spec.ts.snap
  packages/devui-vue/devui/tooltip/index.ts
  packages/devui-vue/devui/transfer/__tests__/transfer.spec.ts
  packages/devui-vue/docs/components/transfer/index.md
Labels: PR: reviewed-approved

#142 feat: 去除alert关闭时dom操作
  packages/devui-vue/devui/alert/src/alert.scss
  packages/devui-vue/devui/alert/src/alert.tsx
Labels: PR: reviewed-approved

#185 docs: 优化文档中表格的样式
  packages/devui-vue/docs/.vitepress/devui-theme/styles/layout.scss
Labels: 📄documentation, PR: unreviewed

#186 chore: 修改.prerrierrc配置统一加上句尾分号
  .prettierrc
Labels: PR: unreviewed

#196 fix: [问题修改]密码输入框右侧图标在特定场景下不显示问题
  packages/devui-vue/devui/input/src/input.scss
  packages/devui-vue/devui/input/src/input.tsx
Labels: PR: reviewed-approved

#197 feat(site): add devui playground
  packages/devui-vue/docs/.vitepress/config/nav.ts
Labels: PR: reviewed-approved

#201 refactor: replace yarn with pnpm
  .github/workflows/pull-request.yml
  .gitignore
  lerna.json
  package.json
  packages/devui-vue/.yarnrc
  packages/devui-vue/devui/cascader/hooks/use-cascader-item.ts
  packages/devui-vue/devui/cascader/src/cascader.tsx
  packages/devui-vue/devui/color-picker/src/components/color-history/color-history.tsx
  packages/devui-vue/devui/form/src/directive/d-validate-rules.ts
  packages/devui-vue/devui/form/src/form-control/form-control.tsx
  packages/devui-vue/devui/nav-sprite/src/nav-sprite.tsx
  packages/devui-vue/devui/quadrant-diagram/src/components/axis/index.tsx
  packages/devui-vue/devui/search/src/hooks/use-search-keydown.ts
  packages/devui-vue/devui/toast/src/toast.tsx
  packages/devui-vue/devui/tree/src/composables/use-draggable.ts
  packages/devui-vue/docs/.vitepress/devui-theme/components/BackToTop.vue
  packages/devui-vue/docs/vite.config.ts
  packages/devui-vue/package.json
  packages/devui-vue/yarn.lock
  pnpm-lock.yaml
  pnpm-workspace.yaml
  yarn.lock
Labels: PR: unreviewed

#202 docs: update README
  .github/workflows/pull-request.yml
  .npmrc
  README.md
Labels: PR: unreviewed

#203 docs(cli): 增加 DevUI CLI 文档
  packages/devui-cli/README.md
  packages/devui-cli/package.json
  pnpm-lock.yaml
Labels: PR: unreviewed

#206 fix: 修复 devui-cli
  package.json
  packages/devui-cli/package.json
  packages/devui-cli/src/bin.ts
  packages/devui-cli/src/commands/base.ts
  packages/devui-cli/src/shared/config.ts
  packages/devui-cli/src/shared/utils.ts
  packages/devui-cli/src/templates/base/config.ts
  packages/devui-cli/src/templates/component/utils.ts
  packages/devui-cli/src/templates/lib-entry/lib-entry.ts
  packages/devui-cli/tsconfig.json
  packages/devui-vue/dc.config.ts
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: PR: reviewed-approved

#205 feat: add devui-theme
  packages/devui-theme/.gitignore
  packages/devui-theme/package.json
  packages/devui-theme/src/index.ts
  packages/devui-theme/src/styles-var/devui-var.less
  packages/devui-theme/src/styles-var/devui-var.scss
  packages/devui-theme/src/styles-var/private/_animation.scss
  packages/devui-theme/src/styles-var/private/_color.scss
  packages/devui-theme/src/styles-var/private/_corner.scss
  packages/devui-theme/src/styles-var/private/_font.scss
  packages/devui-theme/src/styles-var/private/_shadow.scss
  packages/devui-theme/src/styles-var/private/_variables.scss
  packages/devui-theme/src/styles-var/private/_z-index.scss
  packages/devui-theme/src/theme-collection/extend-theme.scss
  packages/devui-theme/src/theme-collection/extend-theme.ts
  packages/devui-theme/src/theme-collection/index.ts
  packages/devui-theme/src/theme-collection/public-api.ts
  packages/devui-theme/src/theme/index.ts
  packages/devui-theme/src/theme/key-config.ts
  packages/devui-theme/src/theme/media-query.ts
  packages/devui-theme/src/theme/public-api.ts
  packages/devui-theme/src/theme/theme-data.ts
  packages/devui-theme/src/theme/theme-management.ts
  packages/devui-theme/src/theme/theme-service.ts
  packages/devui-theme/src/theme/theme.ts
  packages/devui-theme/src/theme/utils/context-service.ts
  packages/devui-theme/src/theme/utils/event-bus.ts
  packages/devui-theme/src/theme/utils/index.ts
  packages/devui-theme/src/theme/utils/interface.ts
  packages/devui-theme/src/theme/utils/storage-service.ts
  packages/devui-theme/tsconfig.json
  packages/devui-theme/tsconfig.node.json
  packages/devui-theme/vite.config.ts
  packages/devui-vue/docs/.vitepress/devui-theme/components/NavBar.vue
  packages/devui-vue/docs/theme-guide/index.md
  packages/devui-vue/docs/vite.config.ts
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: PR: unreviewed

#209 build: add script cli
  packages/devui-vue/dc.config.ts
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: PR: unreviewed

#212 feat: 在生产环境隐藏未完成的组件
  packages/devui-vue/docs/.vitepress/devui-theme/components/SideBarLink.js
Labels: PR: unreviewed
