Repository DevCloudFE/vue-devui, pull requests merged in 2022-04, with the labels that each got.

#370 fix: 修复本地启动缺少组件导入的问题
  packages/devui-vue/devui-cli/commands/create.js
  packages/devui-vue/devui-cli/index.js
  packages/devui-vue/devui-cli/shared/constant.js
  packages/devui-vue/package.json
Labels: bug, PR: unreviewed, ignore-for-release

#372 chore: 修复search组件eslint问题
  packages/devui-vue/devui/search/src/search.tsx
Labels: PR: reviewed-approved, refactoring

#374 fix(Tree): 修复Tree组件引入lodash不准确，导致业务vite构建报错问题
  packages/devui-vue/devui/tree/src/composables/use-draggable.ts
Labels: bug, PR: reviewed-approved

#375 refactor(tree): 增加useTree并支持插件机制
  packages/devui-vue/devui/tree/src/components/icon-close.tsx
  packages/devui-vue/devui/tree/src/components/icon-open.tsx
  packages/devui-vue/devui/tree/src/components/tree-node-toggle.tsx
  packages/devui-vue/devui/tree/src/components/tree-node.tsx
  packages/devui-vue/devui/tree/src/core/tree-factory-types.ts
  packages/devui-vue/devui/tree/src/core/tree-factory.ts
  packages/devui-vue/devui/tree/src/core/use-check.ts
  packages/devui-vue/devui/tree/src/core/use-core.ts
  packages/devui-vue/devui/tree/src/core/use-disable.ts
  packages/devui-vue/devui/tree/src/core/use-operate.ts
  packages/devui-vue/devui/tree/src/core/use-select.ts
  packages/devui-vue/devui/tree/src/core/use-toggle.ts
  packages/devui-vue/devui/tree/src/core/use-tree.ts
  packages/devui-vue/devui/tree/src/core/utils.ts
Labels: PR: unreviewed, feature, refactoring

#378 chore(statistic): 修复eslint问题
  packages/devui-vue/devui/statistic/src/statistic.tsx
  packages/devui-vue/devui/statistic/src/utils/animation.ts
  packages/devui-vue/devui/statistic/src/utils/easing.ts
Labels: PR: reviewed-approved, refactoring

#382 docs: 添加badge的英文文档
  packages/devui-vue/docs/en-US/components/badge/index.md
Labels: documentation, PR: unreviewed, PR: reviewed-approved

#381 fix: 修复badge单元测试props属性错误问题
  packages/devui-vue/devui/badge/__tests__/badge.spec.ts
Labels: bug

#379 chore(image-preview): 修复image-preview的eslint问题、代码规范格式
  packages/devui-vue/devui/image-preview/__tests__/image-preview.spec.ts
  packages/devui-vue/devui/image-preview/src/image-preview-directive.ts
  packages/devui-vue/devui/image-preview/src/image-preview-service.ts
  packages/devui-vue/devui/image-preview/src/image-preview-types.ts
  packages/devui-vue/devui/image-preview/src/image-preview.tsx
  packages/devui-vue/devui/image-preview/src/transform.ts
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
Labels: PR: reviewed-approved, refactoring

#384 fix(Table): 修复表格选择功能无法适配表头分组的问题
  packages/devui-vue/devui/table/src/components/body-td/body-td.tsx
  packages/devui-vue/devui/table/src/components/body/body.tsx
  packages/devui-vue/devui/table/src/components/column/column-types.ts
  packages/devui-vue/devui/table/src/components/column/column.tsx
  packages/devui-vue/devui/table/src/components/column/config.tsx
  packages/devui-vue/devui/table/src/components/column/use-column.ts
  packages/devui-vue/devui/table/src/components/header-th/header-th.tsx
  packages/devui-vue/devui/table/src/components/header/header.scss
  packages/devui-vue/devui/table/src/components/header/header.tsx
  packages/devui-vue/devui/table/src/composable/use-table.ts
  packages/devui-vue/devui/table/src/store/index.ts
  packages/devui-vue/devui/table/src/store/store-types.ts
  packages/devui-vue/docs/components/table/index.md
Labels: bug, PR: unreviewed, PR: reviewed-approved

#383 chore(avatar): 修复eslint问题
  packages/devui-vue/devui/avatar/src/avatar-types.ts
  packages/devui-vue/devui/avatar/src/avatar.tsx
  packages/devui-vue/devui/avatar/src/icon-body.tsx
  packages/devui-vue/devui/avatar/src/icon-nobody.tsx
Labels: PR: reviewed-approved, refactoring

#385 chore(modal): 修复eslint问题
  packages/devui-vue/devui/modal/src/modal.tsx
  packages/devui-vue/devui/modal/src/services/common-modal-service.ts
  packages/devui-vue/devui/modal/src/services/modal-service.ts
  packages/devui-vue/devui/modal/src/use-moveable.ts
Labels: PR: reviewed-approved, refactoring

#386 feat(tree): 将useTree使用到Tree组件中
  packages/devui-vue/devui/tree/index.ts
  packages/devui-vue/devui/tree/src/components/tree-node-toggle.tsx
  packages/devui-vue/devui/tree/src/components/tree-node.tsx
  packages/devui-vue/devui/tree/src/const.ts
  packages/devui-vue/devui/tree/src/core/README.md
  packages/devui-vue/devui/tree/src/core/tree-factory.ts
  packages/devui-vue/devui/tree/src/core/use-check.ts
  packages/devui-vue/devui/tree/src/core/use-core.ts
  packages/devui-vue/devui/tree/src/core/use-disable.ts
  packages/devui-vue/devui/tree/src/core/use-operate.ts
  packages/devui-vue/devui/tree/src/core/use-select.ts
  packages/devui-vue/devui/tree/src/core/use-toggle.ts
  packages/devui-vue/devui/tree/src/core/use-tree-types.ts
  packages/devui-vue/devui/tree/src/core/use-tree.ts
  packages/devui-vue/devui/tree/src/core/utils.ts
  packages/devui-vue/devui/tree/src/new-tree.tsx
  packages/devui-vue/docs/components/tree/index.md
Labels: PR: unreviewed, feature

#387 feat(Table): 表格支持索引列
  packages/devui-vue/devui/table/src/components/column/column-types.ts
  packages/devui-vue/devui/table/src/components/column/config.tsx
  packages/devui-vue/devui/table/src/components/column/use-column.ts
  packages/devui-vue/docs/components/table/index.md
Labels: PR: reviewed-approved, feature

#388 chore(tag-input): 解决eslint问题
  packages/devui-vue/devui/tag-input/src/remove-btn.tsx
  packages/devui-vue/devui/tag-input/src/tag-input-types.ts
  packages/devui-vue/devui/tag-input/src/tag-input.tsx
Labels: PR: unreviewed, refactoring

#389 chore(upload): 修复eslint问题
  packages/devui-vue/devui/upload/src/composables/use-select-files.ts
  packages/devui-vue/devui/upload/src/composables/use-upload.ts
  packages/devui-vue/devui/upload/src/file-drop-directive.ts
  packages/devui-vue/devui/upload/src/file-uploader.ts
  packages/devui-vue/devui/upload/src/upload-types.ts
  packages/devui-vue/devui/upload/src/upload.tsx
Labels: PR: reviewed-approved, refactoring

#390 chore(pagination): 修复eslint问题
  packages/devui-vue/devui/pagination/src/components/jump-page.tsx
Labels: refactoring

#392 chore(loading): 修复eslint问题
  packages/devui-vue/devui/loading/src/directive.ts
  packages/devui-vue/devui/loading/src/service.ts
  packages/devui-vue/devui/loading/src/types.ts
  packages/devui-vue/devui/shared/scripts/component.ts
Labels: PR: reviewed-approved, refactoring

#394 fix(auto-complete): 修复eslint和单元测试问题
  packages/devui-vue/devui/auto-complete/__tests__/auto-complete.spec.ts
  packages/devui-vue/devui/auto-complete/index.ts
  packages/devui-vue/devui/auto-complete/src/auto-complete-types.ts
  packages/devui-vue/devui/auto-complete/src/auto-complete.scss
  packages/devui-vue/devui/auto-complete/src/auto-complete.tsx
  packages/devui-vue/devui/auto-complete/src/components/dropdown.tsx
  packages/devui-vue/devui/auto-complete/src/composables/use-custom-template.ts
  packages/devui-vue/devui/auto-complete/src/composables/use-input-handle.ts
  packages/devui-vue/devui/auto-complete/src/composables/use-keyboard-select.ts
  packages/devui-vue/devui/auto-complete/src/composables/use-lazy-handle.ts
  packages/devui-vue/devui/auto-complete/src/composables/use-searchfn.ts
  packages/devui-vue/devui/auto-complete/src/composables/use-select-handle.ts
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
  packages/devui-vue/docs/components/auto-complete/index.md
  packages/devui-vue/docs/en-US/components/auto-complete/api-en.md
  packages/devui-vue/tsconfig.json
Labels: PR: reviewed-approved, refactoring

#396 chore(read-tip): 修复eslint问题
  packages/devui-vue/devui/read-tip/__tests__/read-tip-template.spec.ts
  packages/devui-vue/devui/read-tip/src/read-tip-template.tsx
  packages/devui-vue/devui/read-tip/src/read-tip-types.ts
  packages/devui-vue/devui/read-tip/src/read-tip.tsx
Labels: PR: reviewed-approved, refactoring

#395 fix(drawer): type-error fix
  packages/devui-vue/devui/drawer/src/drawer-service.tsx
  packages/devui-vue/devui/drawer/src/drawer-types.ts
Labels: PR: reviewed-approved, refactoring

#397 feat(Table): 丰富自定义列参数&新增支持自定义表头
  packages/devui-vue/devui/table/src/components/column/column-types.ts
  packages/devui-vue/devui/table/src/components/column/config.tsx
  packages/devui-vue/devui/table/src/components/column/use-column.ts
  packages/devui-vue/docs/components/table/index.md
Labels: PR: reviewed-approved, feature

#400 feat(tree): 增加节点连接线
  packages/devui-vue/devui/tree/src/components/tree-node.tsx
  packages/devui-vue/devui/tree/src/components/use-tree-node.ts
  packages/devui-vue/devui/tree/src/const.ts
  packages/devui-vue/devui/tree/src/core/use-core.ts
  packages/devui-vue/devui/tree/src/core/use-tree-types.ts
  packages/devui-vue/devui/tree/src/tree.scss
  packages/devui-vue/docs/components/tree/index.md
Labels: PR: unreviewed, feature

#401 fix(Table): 修复表头背景失效问题&修复header跟body对齐问题
  packages/devui-vue/devui/table/src/components/header/header.scss
Labels: bug, PR: reviewed-approved

#402 feat(tree): 增加默认插槽
  packages/devui-vue/devui/tree/src/const.ts
  packages/devui-vue/devui/tree/src/new-tree.tsx
  packages/devui-vue/devui/tree/src/tree.scss
Labels: PR: unreviewed, feature

#404 test(Comment): 添加单元测试
  packages/devui-vue/devui/comment/__tests__/comment.spec.ts
Labels: PR: reviewed-approved

#403 feat(Table): 优化Table组件文档
  packages/devui-vue/devui/table/src/components/colgroup/colgroup.tsx
  packages/devui-vue/devui/table/src/table-types.ts
  packages/devui-vue/docs/components/table/index.md
Labels: documentation, PR: reviewed-approved

#405 feat(tree): add tree content/icon slot
  packages/devui-vue/devui/tree/src/components/tree-node-content.tsx
  packages/devui-vue/devui/tree/src/components/tree-node.tsx
  packages/devui-vue/devui/tree/src/new-tree.tsx
  packages/devui-vue/docs/components/tree/index.md
Labels: PR: unreviewed, feature

#408 feat(tree):增加 insertBefore 方法
  packages/devui-vue/devui/tree/src/core/use-operate.ts
  packages/devui-vue/devui/tree/src/core/use-tree-types.ts
  packages/devui-vue/devui/tree/src/core/utils.ts
  packages/devui-vue/devui/tree/src/new-tree.tsx
  packages/devui-vue/docs/components/tree/index.md
Labels: PR: unreviewed, feature

#409 refactor(tree): 将插件改造成带参的形式
  packages/devui-vue/devui/tree/src/core/README.md
  packages/devui-vue/devui/tree/src/core/use-check.ts
  packages/devui-vue/devui/tree/src/core/use-core.ts
  packages/devui-vue/devui/tree/src/core/use-disable.ts
  packages/devui-vue/devui/tree/src/core/use-operate.ts
  packages/devui-vue/devui/tree/src/core/use-select.ts
  packages/devui-vue/devui/tree/src/core/use-toggle.ts
  packages/devui-vue/devui/tree/src/core/use-tree-types.ts
  packages/devui-vue/devui/tree/src/core/use-tree.ts
  packages/devui-vue/devui/tree/src/new-tree.tsx
Labels: PR: unreviewed, refactoring

#410 chore(loading): 去除eslint-disable、修复eslint问题
  packages/devui-vue/devui/loading/__tests__/loading.spec.ts
  packages/devui-vue/devui/loading/src/directive.ts
Labels: PR: reviewed-approved, refactoring

#406 fixed:修改comment jest 校验
  packages/devui-vue/devui/comment/src/comment-types.ts
  packages/devui-vue/devui/comment/src/comment.tsx
Labels: PR: reviewed-approved, refactoring

#412 test(Popover): 补充Popover组件单元测试
  packages/devui-vue/devui/popover/__tests__/popover.spec.ts
  packages/devui-vue/devui/popover/__tests__/popover.spec.tsx
Labels: PR: reviewed-approved, refactoring

#413 test(Modal): 补充Modal组件单元测试
  packages/devui-vue/devui/modal/__tests__/modal.spec.tsx
Labels: PR: reviewed-approved, refactoring

#414 test(Overlay): 补充Overlay组件的单元测试
  packages/devui-vue/devui/overlay/__tests__/overlay.spec.ts
  packages/devui-vue/devui/overlay/__tests__/overlay.spec.tsx
Labels: PR: reviewed-approved, unit-test

#415 fix(Table): 优化Table组件文档和表头样式
  packages/devui-vue/devui/table/src/components/header/header.scss
  packages/devui-vue/docs/components/table/index.md
Labels: bug, PR: reviewed-approved

#416 test(Notification): 补充Notification单元测试
  packages/devui-vue/devui/notification/__tests__/notification.spec.tsx
Labels: PR: reviewed-approved, unit-test

#417 fix(Notification): 修正Notification组件的图标
  packages/devui-vue/devui/notification/src/notification-icons.tsx
  packages/devui-vue/devui/notification/src/notification-image.tsx
  packages/devui-vue/devui/notification/src/notification.scss
  packages/devui-vue/docs/components/notification/index.md
Labels: bug, PR: reviewed-approved

#418 test(Table): 补充Table组件单元测试
  packages/devui-vue/devui/table/__tests__/table.spec.ts
  packages/devui-vue/devui/table/__tests__/table.spec.tsx
  packages/devui-vue/devui/table/index.ts
Labels: PR: reviewed-approved, unit-test

#419 test(Layout): 补充Layout单元测试
  packages/devui-vue/devui/layout/__tests__/layout.spec.ts
  packages/devui-vue/devui/layout/src/aside.tsx
Labels: PR: reviewed-approved, unit-test

#423 fix(Notification): 修正Notification组件单元测试
  packages/devui-vue/devui/notification/__tests__/notification.spec.tsx
Labels: PR: reviewed-approved, unit-test

#420 feat(Table): 规范细节微调&参照规范完善Table文档
  packages/devui-vue/docs/components/table/index.md
  packages/devui-vue/docs/contributing/development-specification/component-document/index.md
Labels: documentation, PR: reviewed-approved

#425 docs(button): optimize demo
  packages/devui-vue/docs/.vitepress/devui-theme/styles/demo-block.scss
  packages/devui-vue/docs/.vitepress/devui-theme/styles/layout.scss
  packages/devui-vue/docs/components/button/index.md
  packages/devui-vue/docs/components/fullscreen/index.md
Labels: documentation, PR: unreviewed

#427 build: add ready components white list
  packages/devui-vue/devui-cli/commands/build.js
  packages/devui-vue/devui-cli/commands/code-check.js
  packages/devui-vue/devui-cli/commands/create.js
  packages/devui-vue/devui-cli/shared/constant.js
  packages/devui-vue/devui-cli/shared/utils.js
  packages/devui-vue/devui/tree/src/core/use-tree-types.ts
  packages/devui-vue/devui/tree/src/new-tree-types.ts
  packages/devui-vue/devui/tree/src/new-tree.tsx
  packages/devui-vue/docs/.vitepress/devui-theme/components/SideBarLink.js
  packages/devui-vue/docs/components/tree/index.md
Labels: PR: unreviewed, refactoring

#429 feat(Table): Table组件支持列排序功能
  packages/devui-vue/devui/table/__tests__/table.spec.tsx
  packages/devui-vue/devui/table/src/components/body-td/body-td.tsx
  packages/devui-vue/devui/table/src/components/column/column-types.ts
  packages/devui-vue/devui/table/src/components/column/use-column.ts
  packages/devui-vue/devui/table/src/components/header-th/header-th.tsx
  packages/devui-vue/devui/table/src/components/header-th/use-header-th.ts
  packages/devui-vue/devui/table/src/components/header/header.scss
  packages/devui-vue/devui/table/src/components/sort/index.ts
  packages/devui-vue/devui/table/src/components/sort/sort-types.ts
  packages/devui-vue/devui/table/src/components/sort/sort.tsx
  packages/devui-vue/devui/table/src/composables/use-table.ts
  packages/devui-vue/devui/table/src/store/index.ts
  packages/devui-vue/devui/table/src/store/store-types.ts
  packages/devui-vue/devui/table/src/table-types.ts
  packages/devui-vue/devui/table/src/table.tsx
  packages/devui-vue/docs/components/table/index.md
Labels: PR: reviewed-approved, feature

#430 refactor(devui-cli): 优化创建组件模板的脚本
  packages/devui-vue/devui-cli/commands/create.js
  packages/devui-vue/devui-cli/templates/component.js
  packages/devui-vue/docs/components/cascader/index.md
Labels: PR: unreviewed, refactoring

#432 fix(Rate): 修复 rate 组件半选模式报错 (#376)
  packages/devui-vue/devui/rate/src/rate-types.ts
  packages/devui-vue/devui/rate/src/rate.tsx
  packages/devui-vue/docs/components/rate/index.md
Labels: bug, PR: reviewed-approved

#433 fix(devui-cli): 优化创建组件模板的脚本
  packages/devui-vue/devui-cli/commands/create.js
  packages/devui-vue/devui-cli/templates/component.js
Labels: bug, PR: unreviewed

#435 feat(Popover): 优化Popover组件文档
  packages/devui-vue/docs/components/popover/index.md
Labels: documentation, PR: reviewed-approved

#437 fix: GitHub format
  CONTRIBUTING.md
Labels: documentation, PR: reviewed-approved

#442 fix(Dropdown): 修复Dropdown隐藏不销毁时位置不更新的bug&支持贴视图边界对齐时设置偏移量
  packages/devui-vue/devui/dropdown/src/dropdown-types.ts
  packages/devui-vue/devui/dropdown/src/dropdown.tsx
  packages/devui-vue/devui/overlay/src/flexible-overlay/flexible-overlay-types.ts
  packages/devui-vue/devui/overlay/src/flexible-overlay/use-flexible-overlay.ts
  packages/devui-vue/docs/components/dropdown/index.md
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: bug, PR: reviewed-approved

#443 docs(overview): 完善组件功能概览
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageToc.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/SideBar.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/SideBarLink.js
  packages/devui-vue/docs/.vitepress/devui-theme/styles/sidebar-links.scss
  packages/devui-vue/docs/components/overview/index.md
Labels: documentation, PR: unreviewed

#445 refactor: 将randomId抽离到shared/utils目录中
  packages/devui-vue/devui/anchor/src/d-anchor-box.ts
  packages/devui-vue/devui/anchor/src/d-anchor-link.ts
  packages/devui-vue/devui/anchor/src/d-anchor.ts
  packages/devui-vue/devui/anchor/src/utils.ts
  packages/devui-vue/devui/breadcrumb/src/breadcrumb.tsx
  packages/devui-vue/devui/drawer/src/use-drawer.ts
  packages/devui-vue/devui/dropdown/src/use-dropdown.ts
  packages/devui-vue/devui/modal/index.ts
  packages/devui-vue/devui/overlay/index.ts
  packages/devui-vue/devui/shared/devui-directive/clickoutside.ts
  packages/devui-vue/devui/shared/utils/class.ts
  packages/devui-vue/devui/shared/utils/common-var.ts
  packages/devui-vue/devui/shared/utils/debounce.ts
  packages/devui-vue/devui/shared/utils/dom.ts
  packages/devui-vue/devui/shared/utils/index.ts
  packages/devui-vue/devui/shared/utils/lock-scroll.ts
  packages/devui-vue/devui/shared/utils/props-util.ts
  packages/devui-vue/devui/shared/utils/random-id.ts
  packages/devui-vue/devui/shared/utils/set-style.ts
  packages/devui-vue/devui/splitter/src/components/splitter-bar.tsx
  packages/devui-vue/devui/splitter/src/components/splitter-pane.tsx
  packages/devui-vue/devui/theme/core/theme.ts
  packages/devui-vue/devui/tree/src/composables/use-checked.ts
  packages/devui-vue/devui/tree/src/core/utils.ts
  packages/devui-vue/devui/tree/src/tree.tsx
  packages/devui-vue/devui/tree/src/utils.ts
Labels: PR: unreviewed, refactoring

#446 refactor: 移除无用的logs
  packages/devui-vue/devui/accordion/src/accordion-item-routerlink.tsx
  packages/devui-vue/devui/cascader/components/cascader-item/index.tsx
  packages/devui-vue/devui/cascader/components/cascader-list/index.tsx
  packages/devui-vue/devui/cascader/hooks/use-cascader-multiple.ts
  packages/devui-vue/devui/date-picker/src/components/vertical-slider/index.tsx
  packages/devui-vue/devui/form/src/form-item/form-item.tsx
  packages/devui-vue/devui/gantt/src/gantt-scale/use-scale-data.ts
  packages/devui-vue/devui/gantt/src/use-gantt.ts
  packages/devui-vue/devui/grid/__tests__/grid.spec.tsx
  packages/devui-vue/devui/image-preview/src/image-preview-directive.ts
  packages/devui-vue/devui/quadrant-diagram/__tests__/quadrant-diagram.spec.ts
  packages/devui-vue/devui/ripple/__tests__/ripple.spec.ts
  packages/devui-vue/devui/tooltip/__tests__/tooltip.spec.ts
Labels: PR: unreviewed, refactoring

#449 docs(rate): 修正 rate组件文档 中文名称、移除多余文字、参数命名 allowHalf 改为 allow-half
  packages/devui-vue/docs/components/rate/index.md
Labels: documentation, PR: reviewed-approved

#458 fix(AutoComplete): 修复AutoComplete没有获取焦点时输入框高亮的bug
  packages/devui-vue/devui/auto-complete/src/auto-complete.tsx
  packages/devui-vue/devui/auto-complete/src/composables/use-input-handle.ts
Labels: bug, PR: unreviewed, PR: reviewed-approved

#466 refactor(breadcrumb): 优化面包屑组件目录结构和文档
  packages/devui-vue/devui/breadcrumb/index.ts
  packages/devui-vue/docs/components/breadcrumb/index.md
Labels: documentation, PR: unreviewed

#457 fix(Popover): 修复Popover被Overlay覆盖样式的问题
  packages/devui-vue/devui/popover/src/popover.scss
Labels: bug, PR: reviewed-approved

#468 feat(Tooltip): 补充Tooltip单元测试&优化文档格式
  packages/devui-vue/devui/tooltip/__tests__/tooltip.spec.ts
  packages/devui-vue/devui/tooltip/__tests__/tooltip.spec.tsx
  packages/devui-vue/docs/components/tooltip/index.md
Labels: documentation, PR: reviewed-approved, unit-test

#473 test(Dropdown): 补充Dropdown单元测试
  packages/devui-vue/devui/dropdown/__tests__/dropdown.spec.ts
  packages/devui-vue/devui/dropdown/__tests__/dropdown.spec.tsx
  packages/devui-vue/devui/dropdown/src/use-dropdown.ts
Labels: PR: reviewed-approved, unit-test

#478 docs(overview): Overview页面增加组件所属版本信息
  packages/devui-vue/docs/components/overview/index.md
Labels: documentation, PR: unreviewed, ignore-for-release

#479 docs(overview): 增加版本号高亮效果
  packages/devui-vue/docs/.vitepress/devui-theme/styles/demo-block.scss
  packages/devui-vue/docs/components/overview/index.md
Labels: documentation, PR: unreviewed, ignore-for-release

#490 fix(Dropdown): 修复Dropdown漏传参数问题
  packages/devui-vue/devui/dropdown/src/dropdown.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved

#494 feat(slider): 新增color属性
  packages/devui-vue/devui/slider/__tests__/slider.spec.ts
  packages/devui-vue/devui/slider/src/slider-types.ts
  packages/devui-vue/devui/slider/src/slider.tsx
  packages/devui-vue/docs/components/slider/index.md
Labels: PR: reviewed-approved, feature

#499 docs: 增加网站首页
  packages/devui-vue/devui-cli/templates/vitepress-sidebar.js
  packages/devui-vue/docs/.vitepress/config/enNav.ts
  packages/devui-vue/docs/.vitepress/config/nav.ts
  packages/devui-vue/docs/.vitepress/devui-theme/Layout.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/Home.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/HomeFooter.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/HomeHero.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/NavBarTitle.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/Page.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributor.vue
  packages/devui-vue/docs/.vitepress/devui-theme/styles/demo-block.scss
  packages/devui-vue/docs/assets/devui-design.svg
  packages/devui-vue/docs/assets/github.jpeg
  packages/devui-vue/docs/assets/logo.svg
  packages/devui-vue/docs/en-US/index.md
  packages/devui-vue/docs/en-US/quick-start/index.md
  packages/devui-vue/docs/index.md
  packages/devui-vue/docs/quick-start/index.md
  packages/devui-vue/package.json
Labels: documentation, PR: unreviewed

#501 docs: 首页适配多种手机机型
  packages/devui-vue/docs/.vitepress/devui-theme/Layout.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/HomeHero.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributor.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
Labels: documentation, PR: unreviewed

#504 docs: 优化首页样式
  packages/devui-vue/docs/.vitepress/devui-theme/Layout.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/HomeFooter.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/HomeHero.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/NavBar.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/Page.vue
Labels: documentation, PR: unreviewed

#506 fix(Slider): 修复disabled时input未禁用
  packages/devui-vue/devui/slider/__tests__/slider.spec.ts
  packages/devui-vue/devui/slider/src/slider.tsx
  packages/devui-vue/docs/components/slider/index.md
Labels: bug, PR: reviewed-approved

#514 feat(tree): 勾选功能增加父子关联逻辑
  packages/devui-vue/devui/tree/src/components/tree-node.tsx
  packages/devui-vue/devui/tree/src/components/use-tree-node.ts
  packages/devui-vue/devui/tree/src/core/use-check.ts
  packages/devui-vue/devui/tree/src/core/use-core.ts
  packages/devui-vue/devui/tree/src/core/use-tree-types.ts
  packages/devui-vue/docs/components/tree/index.md
Labels: PR: unreviewed, feature

#512 refactor(Form): 优化表单API和文档
  packages/devui-vue/devui/form/src/components/form-control/form-control-types.ts
  packages/devui-vue/devui/form/src/components/form-icons.tsx
  packages/devui-vue/devui/form/src/components/form-label/form-label-types.ts
  packages/devui-vue/devui/form/src/components/form-label/form-label.scss
  packages/devui-vue/devui/form/src/components/form-label/form-label.tsx
  packages/devui-vue/devui/form/src/components/form-label/use-form-label.ts
  packages/devui-vue/devui/form/src/form.tsx
  packages/devui-vue/docs/components/form/index.md
Labels: PR: unreviewed, refactoring

#517 docs(Select): 添加select的主页地址和头像
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
Labels: PR: reviewed-approved

#518 feat(tree): 增加checkStrategy支持自定义勾选策略
  packages/devui-vue/devui/tree/src/components/tree-node.tsx
  packages/devui-vue/devui/tree/src/core/use-check.ts
  packages/devui-vue/devui/tree/src/core/use-core.ts
  packages/devui-vue/devui/tree/src/new-tree.tsx
  packages/devui-vue/docs/components/tree/index.md
Labels: PR: unreviewed, feature

#524 fix(Button): Button组件的图标大小需要用样式变量设置
  packages/devui-vue/devui/button/src/button.tsx
Labels: bug, PR: unreviewed

#523 refactor(Slider): 给一些具有any的类型添加具体类型
  packages/devui-vue/devui/slider/src/slider.tsx
Labels: PR: reviewed-approved, refactoring

#525 docs(slider): 补充color属性的相关文档
  packages/devui-vue/docs/components/slider/index.md
  packages/devui-vue/docs/en-US/components/slider/index.md
Labels: documentation, PR: reviewed-approved

#526 fix(tree): 修复tree组件连接线错误问题
  packages/devui-vue/devui/tree/src/core/use-core.ts
Labels: bug, PR: unreviewed

#527 feat(multi-auto-complete): 初始化组件
  packages/devui-vue/devui/multi-auto-complete/__tests__/multi-auto-complete.spec.tsx
  packages/devui-vue/devui/multi-auto-complete/index.ts
  packages/devui-vue/devui/multi-auto-complete/src/multi-auto-complete-types.ts
  packages/devui-vue/devui/multi-auto-complete/src/multi-auto-complete.scss
  packages/devui-vue/devui/multi-auto-complete/src/multi-auto-complete.tsx
  packages/devui-vue/docs/components/multi-auto-complete/index.md
Labels: PR: reviewed-approved, feature

#531 feat(tree): 增加合并节点的功能
  packages/devui-vue/devui/tree/src/core/use-merge-nodes.ts
  packages/devui-vue/devui/tree/src/core/use-operate.ts
  packages/devui-vue/devui/tree/src/new-tree.tsx
  packages/devui-vue/docs/components/tree/index.md
Labels: PR: unreviewed, feature

#533 chore(tree): 修复eslint问题
  packages/devui-vue/devui/tree/src/core/use-merge-nodes.ts
  packages/devui-vue/devui/tree/src/core/use-tree-types.ts
Labels: PR: unreviewed, refactoring

#534 feat(Form): 完成基本的校验功能
  packages/devui-vue/devui/form/src/components/form-control/form-control.scss
  packages/devui-vue/devui/form/src/components/form-control/form-control.tsx
  packages/devui-vue/devui/form/src/components/form-control/use-form-control.ts
  packages/devui-vue/devui/form/src/components/form-item/form-item-types.ts
  packages/devui-vue/devui/form/src/components/form-item/form-item.tsx
  packages/devui-vue/devui/form/src/components/form-item/use-form-item.ts
  packages/devui-vue/devui/form/src/components/form-label/form-label-types.ts
  packages/devui-vue/devui/form/src/components/form-label/form-label.tsx
  packages/devui-vue/devui/form/src/components/form-label/use-form-label.ts
  packages/devui-vue/devui/form/src/components/form-operation/form-operation.tsx
  packages/devui-vue/devui/form/src/composables/use-field-collection.ts
  packages/devui-vue/devui/form/src/composables/use-form-validation.ts
  packages/devui-vue/devui/form/src/form-types.ts
  packages/devui-vue/devui/form/src/form.tsx
  packages/devui-vue/devui/input/src/input.scss
  packages/devui-vue/devui/input/src/input.tsx
  packages/devui-vue/docs/components/form/index.md
Labels: PR: unreviewed, feature

#535 refactor(tree): 优化Tree组件目录结构
  packages/devui-vue/devui/tree/index.ts
  packages/devui-vue/devui/tree/src/components/tree-node-content.tsx
  packages/devui-vue/devui/tree/src/components/tree-node-toggle.tsx
  packages/devui-vue/devui/tree/src/components/tree-node.tsx
  packages/devui-vue/devui/tree/src/components/use-tree-node.ts
  packages/devui-vue/devui/tree/src/composables/README.md
  packages/devui-vue/devui/tree/src/composables/use-check.ts
  packages/devui-vue/devui/tree/src/composables/use-core.ts
  packages/devui-vue/devui/tree/src/composables/use-disable.ts
  packages/devui-vue/devui/tree/src/composables/use-merge-nodes.ts
  packages/devui-vue/devui/tree/src/composables/use-operate.ts
  packages/devui-vue/devui/tree/src/composables/use-select.ts
  packages/devui-vue/devui/tree/src/composables/use-toggle.ts
  packages/devui-vue/devui/tree/src/composables/use-tree-types.ts
  packages/devui-vue/devui/tree/src/composables/use-tree.ts
  packages/devui-vue/devui/tree/src/composables/utils.ts
  packages/devui-vue/devui/tree/src/core/use-toggle.ts
  packages/devui-vue/devui/tree/src/deprecated-composables/use-checked.ts
  packages/devui-vue/devui/tree/src/deprecated-composables/use-draggable.ts
  packages/devui-vue/devui/tree/src/deprecated-composables/use-highlight.ts
  packages/devui-vue/devui/tree/src/deprecated-composables/use-lazy.ts
  packages/devui-vue/devui/tree/src/deprecated-composables/use-merge-node.ts
  packages/devui-vue/devui/tree/src/deprecated-composables/use-operate.tsx
  packages/devui-vue/devui/tree/src/deprecated-composables/use-toggle.ts
  packages/devui-vue/devui/tree/src/deprecated-tree-types.ts
  packages/devui-vue/devui/tree/src/deprecated-tree.tsx
  packages/devui-vue/devui/tree/src/new-tree-types.ts
  packages/devui-vue/devui/tree/src/new-tree.tsx
  packages/devui-vue/devui/tree/src/tree-node-content.tsx
  packages/devui-vue/devui/tree/src/tree-types.ts
  packages/devui-vue/devui/tree/src/tree.tsx
  packages/devui-vue/devui/tree/src/utils.ts
  packages/devui-vue/docs/components/tree/index.md
Labels: PR: unreviewed, refactoring

#536 feat(Form): 表单项的必填红色星号标志可以正确被设置
  packages/devui-vue/devui/form/src/components/form-item/form-item-types.ts
  packages/devui-vue/devui/form/src/components/form-item/form-item.tsx
  packages/devui-vue/devui/form/src/components/form-item/use-form-item.ts
  packages/devui-vue/devui/form/src/components/form-label/use-form-label.ts
Labels: PR: unreviewed, feature

#537 fix(theme): 修复了menu组件覆盖文档的错误
  packages/devui-vue/devui/menu/src/components/menu-item.tsx
  packages/devui-vue/devui/menu/src/styles/clear.scss
Labels: bug, PR: reviewed-approved

#538 chore: add tree to whitelist
  packages/devui-vue/devui-cli/shared/constant.js
  packages/devui-vue/docs/.vitepress/devui-theme/components/SideBarLink.js
Labels: PR: unreviewed

#539 feat(Form): 优化校验结果的样式&优化文档
  packages/devui-vue/devui/form/index.ts
  packages/devui-vue/devui/form/src/components/form-control/form-control.scss
  packages/devui-vue/devui/form/src/components/form-item/form-item.scss
  packages/devui-vue/devui/form/src/components/form-item/form-item.tsx
  packages/devui-vue/devui/form/src/components/form-item/use-form-item.ts
  packages/devui-vue/devui/form/src/components/form-label/form-label.scss
  packages/devui-vue/devui/form/src/components/form-label/use-form-label.ts
  packages/devui-vue/docs/components/form/index.md
Labels: PR: unreviewed, feature

#542 docs: 优化部分组件文档
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageToc.vue
  packages/devui-vue/docs/components/alert/index.md
  packages/devui-vue/docs/components/auto-complete/index.md
  packages/devui-vue/docs/components/button/index.md
  packages/devui-vue/docs/components/checkbox/index.md
  packages/devui-vue/docs/components/editable-select/index.md
  packages/devui-vue/docs/components/input/index.md
  packages/devui-vue/docs/components/loading/index.md
  packages/devui-vue/docs/components/modal/index.md
  packages/devui-vue/docs/components/notification/index.md
  packages/devui-vue/docs/components/overlay/index.md
  packages/devui-vue/docs/components/pagination/index.md
  packages/devui-vue/docs/components/panel/index.md
  packages/devui-vue/docs/components/radio/index.md
  packages/devui-vue/docs/components/read-tip/index.md
  packages/devui-vue/docs/components/result/index.md
  packages/devui-vue/docs/components/search/index.md
  packages/devui-vue/docs/components/status/index.md
Labels: documentation, PR: unreviewed

#545 docs: 优化组件文档
  packages/devui-vue/devui/input-number/src/input-number-types.ts
  packages/devui-vue/docs/components/drawer/index.md
  packages/devui-vue/docs/components/input-number/index.md
  packages/devui-vue/docs/components/panel/index.md
  packages/devui-vue/docs/components/result/index.md
  packages/devui-vue/docs/components/select/index.md
  packages/devui-vue/docs/components/tabs/index.md
  packages/devui-vue/docs/components/tooltip/index.md
Labels: documentation, PR: unreviewed

#546 fix(auto-complete): 修复input宽度没有自适应的bug
  packages/devui-vue/devui/auto-complete/src/auto-complete.scss
Labels: bug, PR: reviewed-approved

#548 style(List): ListItem组件增加垂直居中的样式
  packages/devui-vue/devui/list/src/list-item.scss
Labels: bug, PR: unreviewed

#550 refactor(pagination): 重构Pagination组件使其符合开发规范
  packages/devui-vue/devui/pagination/src/pagination.scss
  packages/devui-vue/devui/pagination/src/pagination.tsx
  packages/devui-vue/devui/style/core/_form.scss
Labels: PR: unreviewed, refactoring

#554 fix(editable-select): 修复了组件样式bug
  packages/devui-vue/devui/editable-select/src/composables/use-input.ts
  packages/devui-vue/devui/editable-select/src/editable-select-types.ts
  packages/devui-vue/devui/editable-select/src/editable-select.scss
  packages/devui-vue/devui/editable-select/src/editable-select.tsx
Labels: PR: reviewed-approved

#555 fix(Progress): 修复percentage属性值越界时产生的显示渲染错误
  packages/devui-vue/devui/progress/__tests__/progress.spec.ts
  packages/devui-vue/devui/progress/src/progress.tsx
  packages/devui-vue/devui/shared/utils/index.ts
  packages/devui-vue/devui/shared/utils/middle-num.ts
Labels: bug, PR: reviewed-approved

#561 refactor(Progress): 给一些具有any的类型添加具体类型
  packages/devui-vue/devui/progress/src/progress-types.ts
  packages/devui-vue/devui/progress/src/progress.tsx
Labels: PR: reviewed-approved, refactoring

#564 feat(Progress): add `percentageTextPlacement` `percentageTextColor` api
  packages/devui-vue/devui/progress/__tests__/progress.spec.ts
  packages/devui-vue/devui/progress/src/progress-types.ts
  packages/devui-vue/devui/progress/src/progress.scss
  packages/devui-vue/devui/progress/src/progress.tsx
  packages/devui-vue/docs/components/progress/index.md
  packages/devui-vue/docs/en-US/components/progress/index.md
Labels: PR: reviewed-approved, feature

#565 docs(DatePicker): 修正DatePicker文档格式 (#544)。
  packages/devui-vue/docs/components/date-picker/index.md
Labels: documentation, PR: unreviewed, PR: reviewed-approved

#570 feat(Form): 增加校验消息提示类型参数
  packages/devui-vue/devui/form/index.ts
  packages/devui-vue/devui/form/src/components/form-control/form-control.scss
  packages/devui-vue/devui/form/src/components/form-control/form-control.tsx
  packages/devui-vue/devui/form/src/components/form-control/use-form-control.ts
  packages/devui-vue/devui/form/src/components/form-item/form-item-types.ts
  packages/devui-vue/devui/form/src/components/form-item/form-item.tsx
  packages/devui-vue/devui/form/src/components/form-item/use-form-item.ts
  packages/devui-vue/devui/form/src/components/form-label/use-form-label.ts
  packages/devui-vue/devui/form/src/components/form-operation/form-operation.tsx
  packages/devui-vue/devui/form/src/directives/d-validate-rules.ts
  packages/devui-vue/devui/form/src/directives/d-validate.ts
  packages/devui-vue/devui/form/src/directives/style.scss
  packages/devui-vue/devui/form/src/form-types.ts
  packages/devui-vue/devui/form/src/form.tsx
  packages/devui-vue/devui/form/src/utils/event-bus.ts
  packages/devui-vue/devui/form/src/utils/index.ts
  packages/devui-vue/devui/input/src/input.tsx
  packages/devui-vue/docs/components/form/index.md
Labels: PR: unreviewed, feature

#574 fix(Checkbox): 修复没有导出CheckboxGroup的问题
  packages/devui-vue/devui/checkbox/index.ts
Labels: bug, PR: unreviewed

#577 fix(editable-select): 修复键盘选择bug
  packages/devui-vue/devui/editable-select/src/composables/use-keyboard-select.ts
Labels: bug, PR: reviewed-approved

#579 fix(Button): Button组件形态为outline，类型为primary禁用的情况下，不应该有hover效果 (#575)。
  packages/devui-vue/devui/button/src/button.scss
Labels: bug, PR: reviewed-approved

#580 fix(Button): Button组件的outline形态hover效果缺少动效 (#573)。
  packages/devui-vue/devui/button/src/button.scss
Labels: bug, PR: reviewed-approved

#581 fix(Loading): Loading 组件动效的卡顿感 (#571)。
  packages/devui-vue/devui/loading/src/loading.scss
Labels: bug, PR: reviewed-approved

#578 fix(Rate): 修复`type`属性下`color`属性失效问题
  packages/devui-vue/devui/rate/__tests__/rate.spec.ts
  packages/devui-vue/devui/rate/src/rate.scss
  packages/devui-vue/devui/rate/src/rate.tsx
Labels: bug, PR: reviewed-approved

#586 feat(Form): 新增移除校验结果和重置值的方法
  packages/devui-vue/devui/form/src/components/form-item/form-item-types.ts
  packages/devui-vue/devui/form/src/components/form-item/form-item.tsx
  packages/devui-vue/devui/form/src/components/form-item/use-form-item.ts
  packages/devui-vue/devui/form/src/composables/use-form-validation.ts
  packages/devui-vue/devui/form/src/form-types.ts
  packages/devui-vue/devui/form/src/form.tsx
  packages/devui-vue/docs/components/form/index.md
Labels: PR: unreviewed, feature

#585 fix(Cascader): 修复Cascader组件中class与Tag组件class重名导致tag组件样式异常 (close #582) 。
  packages/devui-vue/devui/cascader/components/cascader-tag/index.scss
  packages/devui-vue/devui/cascader/components/cascader-tag/index.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved

#589 fix(Popover): 鼠标移入Popover内Popover不应关闭
  packages/devui-vue/devui/popover/src/popover-types.ts
  packages/devui-vue/devui/popover/src/popover.tsx
  packages/devui-vue/devui/popover/src/use-popover.ts
Labels: bug, PR: unreviewed

#588 refactor(Input): 重构Input组件代码
  packages/devui-vue/devui/input/src/composables/use-input-event.ts
  packages/devui-vue/devui/input/src/composables/use-input-render.ts
  packages/devui-vue/devui/input/src/input-types.tsx
  packages/devui-vue/devui/input/src/input.scss
  packages/devui-vue/devui/input/src/input.tsx
  packages/devui-vue/devui/style/core/_form.scss
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
  packages/devui-vue/docs/components/input/index.md
Labels: PR: unreviewed, refactoring

#590 fix(Tooltip): 修复鼠标不能移入到内容上的问题
  packages/devui-vue/devui/tooltip/src/tooltip-types.ts
  packages/devui-vue/devui/tooltip/src/tooltip.tsx
  packages/devui-vue/devui/tooltip/src/use-tooltip.ts
  packages/devui-vue/docs/components/tooltip/index.md
Labels: bug, PR: unreviewed

#591 feat(Form): 支持validate事件&支持配置rules变更后立即触发校验
  packages/devui-vue/devui/form/src/components/form-item/use-form-item.ts
  packages/devui-vue/devui/form/src/form-types.ts
  packages/devui-vue/devui/form/src/form.tsx
  packages/devui-vue/docs/components/form/index.md
Labels: PR: unreviewed, feature

#594 feat(Form): 支持设置校验结果反馈图标
  packages/devui-vue/devui/form/src/components/form-control/form-control.scss
  packages/devui-vue/devui/form/src/components/form-control/form-control.tsx
  packages/devui-vue/devui/form/src/components/form-control/use-form-control.ts
  packages/devui-vue/devui/form/src/components/form-icons.tsx
  packages/devui-vue/devui/form/src/components/form-item/form-item-types.ts
  packages/devui-vue/devui/form/src/components/form-item/form-item.tsx
  packages/devui-vue/devui/form/src/form-types.ts
  packages/devui-vue/devui/input/src/composables/use-input-render.ts
  packages/devui-vue/devui/input/src/input.scss
  packages/devui-vue/docs/components/form/index.md
Labels: PR: unreviewed, feature
