Repository DevCloudFE/vue-devui, pull requests merged in 2022-09, with the labels that each got.

#1293 docs: fix docs problem
  packages/devui-vue/devui/menu/index.ts
  packages/devui-vue/package.json
Labels: PR: unreviewed

#1289 fix(docs): 修复 form 文档示例中 d-textarea 输入字符失去焦点清空的bug (close #1287)
  packages/devui-vue/docs/components/form/index.md
Labels: bug, PR: reviewed-approved

#1272 test(checkbox): 增加对颜色属性的测试
  packages/devui-vue/devui/checkbox/__tests__/checkbox.spec.ts
Labels: PR: reviewed-approved, unit-test

#1284 test(time-select): 完成一些对time-select的测试
  packages/devui-vue/devui/time-select/__tests__/time-select.spec.ts
Labels: PR: reviewed-approved, unit-test

#1286 fix(select): 当输入带空格的文本，select搜索功能显示异常
  packages/devui-vue/devui/select/src/use-select.ts
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1295 chore: add build script alias
  package.json
Labels: PR: unreviewed

#1298 chore: release v1.0.1
  packages/devui-vue/package.json
Labels: PR: unreviewed

#1296 fix(time-select): 修复 #1290 中step小于等于0时会卡死的问题
  packages/devui-vue/devui/time-select/src/use-time-select.ts
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1305 fix(mention): Mention 提及组件，第一次选择后删除输入，第二次输入点击无法选中 close #1292
  packages/devui-vue/devui/mention/src/mention.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1308 chore: release v1.0.2
  packages/devui-vue/package.json
Labels: PR: unreviewed

#1311 fix: fix doc 404 close #1310
  packages/devui-vue/docs/.vitepress/devui-theme/Layout.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/HomeFooter.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/NavBar.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/NavLinks.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageToc.vue
  packages/devui-vue/docs/.vitepress/devui-theme/composables/sideBar.js
  packages/devui-vue/docs/.vitepress/devui-theme/const.ts
Labels: bug, PR: unreviewed

#1314 fix: fix mobile sidebar scroll problem
  packages/devui-vue/docs/.vitepress/devui-theme/components/SideBar.vue
Labels: bug, PR: unreviewed

#1309 style(search): 优化search 搜索框样式，统一组件不同size的大小 #1199
  packages/devui-vue/devui/search/src/search.scss
Labels: enhancement, PR: unreviewed, PR: reviewed-approved

#1322 chore: refactor unit-test scripts
  .github/workflows/pull-request.yml
  .ls-lint.yml
  package.json
  packages/devui-vue/devui-cli/commands/code-check.js
  scripts.json
Labels: enhancement, PR: unreviewed

#1318 style(input): input组件 size 大小使用scss变量向标准统一 #1199
  packages/devui-vue/devui/input/src/input.scss
Labels: enhancement, PR: unreviewed, PR: reviewed-approved

#1144 fix(dragdrop): 修改可排序拖拽的bug
  packages/devui-vue/devui/dragdrop/src/droppable-directive.ts
  packages/devui-vue/devui/dragdrop/src/sortable-directive.ts
  packages/devui-vue/devui/dragdrop/src/utils.ts
Labels: bug, PR: unreviewed

#1333 fix(input): 修复 绑定数据为 ref(null) 导致无法获取 length 的错误 (close #1329)
  packages/devui-vue/devui/input/src/input.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1324 style(auto-complete): auto-complete 组件 size 大小使用scss变量向标准统一 #1199
  packages/devui-vue/devui/auto-complete/src/auto-complete.scss
  packages/devui-vue/docs/components/auto-complete/index.md
Labels: enhancement, PR: unreviewed, PR: reviewed-approved

#1328 docs(time-select): 更新文档，示例更友好
  packages/devui-vue/docs/components/time-select/index.md
Labels: documentation, PR: reviewed-approved

#1334 fix(menu): 修复组件部分错误
  packages/devui-vue/devui/menu/__tests__/menu.spec.ts
  packages/devui-vue/devui/menu/src/components/menu-item/menu-item.tsx
  packages/devui-vue/devui/menu/src/components/menu-item/use-menu-item.ts
  packages/devui-vue/devui/menu/src/components/sub-menu/sub-menu.tsx
  packages/devui-vue/devui/menu/src/composables/use-nearest-menu-element.ts
  packages/devui-vue/devui/menu/src/composables/use-store.ts
  packages/devui-vue/devui/menu/src/menu.scss
  packages/devui-vue/devui/menu/src/menu.tsx
  packages/devui-vue/devui/menu/src/styles/clear.scss
  packages/devui-vue/devui/menu/src/styles/horizontal.scss
  packages/devui-vue/devui/menu/src/styles/public.scss
  packages/devui-vue/devui/menu/src/styles/vertical.scss
  packages/devui-vue/docs/components/menu/index.md
  packages/devui-vue/docs/en-US/components/menu/index.md
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1335 fix(tag): 移除tag组件 size 属性 xs 类型，统一组件size类型 #1199
  packages/devui-vue/devui/tag/src/tag-types.ts
  packages/devui-vue/devui/tag/src/tag.scss
  packages/devui-vue/docs/components/tag/index.md
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1337 feat: release v1.1.0
  packages/devui-vue/devui-cli/index.js
  packages/devui-vue/package.json
Labels: PR: unreviewed, ignore-for-release

#1340 fix(colorPicker): 组件无法正常打开选择器
  packages/devui-vue/devui/color-picker/src/color-picker.tsx
  packages/devui-vue/devui/color-picker/src/utils/composeable.ts
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1342 优化 card 组件文档 ，props.shadow 类型 alway 修正为 always
  packages/devui-vue/devui/card/src/card-types.ts
  packages/devui-vue/docs/components/card/index.md
Labels: PR: reviewed-approved, refactoring

#1343 fix(checkbox): #1323 修复checkboxGroup下，组件底部遮挡问题
  packages/devui-vue/devui/checkbox/src/checkbox.scss
  packages/devui-vue/devui/checkbox/src/checkbox.tsx
  packages/devui-vue/devui/transfer/__tests__/transfer.spec.ts
Labels: bug, PR: unreviewed, PR: partially-approved

#1348 docs(radio-group): radio-group 根据条件终止切换操作示例，两个radio-group 没有间距
  packages/devui-vue/docs/components/radio/index.md
Labels: documentation, PR: reviewed-approved

#1354 docs: 完善头像英文文档
  packages/devui-vue/docs/en-US/components/avatar/index.md
Labels: documentation, PR: unreviewed, PR: reviewed-approved

#1408 chore: update version 1.2.0
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: PR: unreviewed, ignore-for-release
