Repository DevCloudFE/vue-devui, pull requests merged in 2022-11, with the labels that each got.

#1424 fix(date-picker-pro): 修复 range-date-picker-pro v-model 测试用例错误
  packages/devui-vue/devui/date-picker-pro/__tests__/range-date-picker-pro.spec.tsx
  packages/devui-vue/devui/date-picker-pro/__tests__/utils.ts
Labels: PR: reviewed-approved

#1423 docs: 增加友链
  README.md
  README.zh-CN.md
Labels: documentation, PR: unreviewed, PR: reviewed-approved

#1415 docs(button): 新增button英文文档
  packages/devui-vue/docs/en-US/components/button/index.md
Labels: documentation, PR: unreviewed, PR: reviewed-approved

#1427 fix(button): toggle theme button style questions
  packages/devui-vue/devui/button/src/button.scss
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1420 docs: 新增Modal组件英文文档
  packages/devui-vue/docs/en-US/components/modal/index.md
Labels: documentation, PR: unreviewed, PR: reviewed-approved

#1419 docs: 新增Message组件英文文档
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
  packages/devui-vue/docs/en-US/components/message/index.md
Labels: documentation, PR: unreviewed, PR: reviewed-approved

#1416 fix: #1236
  packages/devui-vue/docs/components/accordion/index.md
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1429 docs: update README
  README.md
  README.zh-CN.md
  packages/devui-vue/docs/.vitepress/devui-theme/components/HomeFooter.vue
  packages/devui-vue/package.json
Labels: documentation, PR: unreviewed

#1428 fix(tabs): 修复在“追光” 主题下 options tabs 样式问题 close #1014
  packages/devui-vue/devui/tabs/src/components/tab-nav/tab-nav.scss
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1434 fix(button): 解决loading效果覆盖底层文字问题
  packages/devui-vue/devui/button/src/button.scss
  packages/devui-vue/devui/button/src/button.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1431 fix(Bug) #1430: 修复DatePickerPro打开日历下拉面板时闪现两个滚动条的问题 close #1430
  packages/devui-vue/devui/virtual-list/src/virtual-list.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1440 test(menu): 添加menu测试用例
  packages/devui-vue/devui/menu/__tests__/menu.spec.ts
Labels: PR: partially-approved, unit-test

#1442 fix(mention): 修复Mention组件设置position为top，输入第一个字符列表选项没有贴近输入框的问题 close #1439
  packages/devui-vue/devui/mention/src/mention.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1443 chore(.github): 新增自动构建
  .github/workflows/auto-publish-npm.yml
Labels: enhancement, PR: reviewed-approved

#1447 fix(checkbox): 阻止事件冒泡，避免引发table中勾选时触发多个事件(#1446)
  packages/devui-vue/devui/checkbox/src/use-checkbox.ts
Labels: bug, PR: reviewed-approved

#1448 docs: update README
  README.md
  README.zh-CN.md
  packages/devui-vue/package.json
Labels: PR: unreviewed, ignore-for-release

#1456 fix(auto-complete): 修复类型定义报错问题
  packages/devui-vue/devui/auto-complete/src/auto-complete-types.ts
  packages/devui-vue/devui/auto-complete/src/composables/use-input-handle.ts
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1455 test(form): 添加form测试用例
  packages/devui-vue/devui/form/__tests__/form.spec.ts
Labels: PR: reviewed-approved, unit-test

#1453 fix: 修复自动化构建报错
  .github/workflows/auto-publish-npm.yml
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1450 fix(message)：修复duration为0时，移入移出自动关闭问题+修改关闭按钮不垂直居中样式(#1449)
  packages/devui-vue/devui/message/src/message.scss
  packages/devui-vue/devui/message/src/message.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1457 release: 1.3.3-alpha.0发布
  packages/devui-vue/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1451 test(popover): 添加popvoer测试用例
  packages/devui-vue/devui/popover/__tests__/popover.spec.tsx
Labels: PR: reviewed-approved, unit-test

#1459 docs: update README
  .github/workflows/auto-publish-npm.yml
  README.zh-CN.md
  packages/devui-vue/package.json
Labels: PR: unreviewed, ignore-for-release

#1461 feat: 下线自动化生成changelog
  .github/workflows/auto-publish-npm.yml
Labels: enhancement, PR: reviewed-approved
