Repository DevCloudFE/vue-devui, pull requests merged in 2022-01, with the labels that each got.

#129 docs(Form): 更新文档及demo示例
  packages/devui-vue/docs/components/form/index.md
Labels: PR: reviewed-approved

#130 doc(Form): 增加英文文档
  packages/devui-vue/docs/en-US/components/form/index.md
Labels: PR: reviewed-changes-requested

#137 feat(splitter): 完善 splitter 单元测试
  packages/devui-vue/devui/splitter/__mocks__/event-helper.ts
  packages/devui-vue/devui/splitter/__tests__/splitter.spec.ts
Labels: PR: reviewed-approved

#128 fix(statistic): 优化文档 ts问题 插槽 不居中问题 暂时隐藏showGroupSeparator属性
  packages/devui-vue/devui/statistic/src/statistic-types.ts
  packages/devui-vue/devui/statistic/src/statistic.scss
  packages/devui-vue/devui/statistic/src/utils/animation.ts
  packages/devui-vue/devui/statistic/src/utils/easing.ts
  packages/devui-vue/docs/components/statistic/index.md
  packages/devui-vue/docs/en-US/components/statistic/index.md
Labels: PR: reviewed-approved

#126 fix(Form): 修复一些bug
  packages/devui-vue/devui/form/src/directive/d-validate-rules.ts
  packages/devui-vue/devui/form/src/form-control/form-control.tsx
Labels: PR: reviewed-approved

#70 feat(tree-select): 新增自定义图标和标签化
  packages/devui-vue/devui/tree-select/hooks/use-clear.ts
  packages/devui-vue/devui/tree-select/hooks/use-select.ts
  packages/devui-vue/devui/tree-select/src/tree-select-types.ts
  packages/devui-vue/devui/tree-select/src/tree-select.scss
  packages/devui-vue/devui/tree-select/src/tree-select.tsx
  packages/devui-vue/devui/tree-select/src/utils.ts
  packages/devui-vue/docs/components/tree-select/index.md
Labels: PR: reviewed-approved, ✨ feature

#141 fixed: 重构tooltip代码
  packages/devui-vue/devui/tooltip/src/tooltip.tsx
  packages/devui-vue/devui/tooltip/utils/event-listener.js
Labels: PR: reviewed-approved

#139 fix(auto-complete): fix auto-complete docs build error: dead link
  packages/devui-vue/docs/components/auto-complete/index.md
  packages/devui-vue/docs/en-US/components/auto-complete/api-en.md
Labels: PR: unreviewed

#147 fix(devui-cli): dc -> devui
  package.json
  packages/devui-cli/package.json
Labels: PR: unreviewed

#146 fix(auto-complete): 修复污染全局样式问题
  packages/devui-vue/devui/auto-complete/src/auto-complete.scss
Labels: PR: reviewed-approved

#145 fix(docs): 修复了调试时首页白屏
  packages/devui-vue/docs/vite.config.ts
Labels: PR: reviewed-approved

#144 docs(comment):更新组件状态为100%
  packages/devui-vue/devui/comment/index.ts
  packages/devui-vue/devui/comment/src/comment.scss
  packages/devui-vue/devui/comment/src/comment.tsx
Labels: PR: reviewed-approved

#150 fix(drawer): modify h/render to createApp
  packages/devui-vue/devui/drawer/src/drawer-service.ts
  packages/devui-vue/devui/drawer/src/drawer-service.tsx
  packages/devui-vue/devui/drawer/src/drawer-types.ts
  packages/devui-vue/devui/drawer/src/drawer.tsx
Labels: PR: reviewed-approved

#155 fix: fix pull-request action
  .github/workflows/pull-request.yml
  package.json
  packages/devui-vue/package.json
Labels: PR: unreviewed

#157 fix: GITEE_RSA_PRIVATE_KEY -> SSH_PRIVATE_KEY
  .github/workflows/sync-gitee.yml
Labels: PR: unreviewed

#159 build: 注释yarn test命令
  .github/workflows/pull-request.yml
Labels: PR: unreviewed

#160 fix: tooltip test file
  packages/devui-vue/devui/tooltip/__tests__/tooltip.spec.ts
Labels: PR: reviewed-approved

#172 feat(tag): 补充组件单元测试
  packages/devui-vue/devui/tag/__tests__/tag.spec.ts
Labels: PR: unreviewed, unit test

#173 fix(tag): 修复关闭icon没有垂直居中的bug
  packages/devui-vue/devui/tag/src/hooks/use-class.ts
  packages/devui-vue/devui/tag/src/tag.scss
Labels: 🐛 bug, PR: unreviewed, PR: reviewed-approved

#164 fix: Carousel component test case
  packages/devui-vue/devui/carousel/__tests__/carousel.spec.ts
  packages/devui-vue/devui/carousel/index.ts
Labels: PR: reviewed-approved

#178 feat(drawer): add destroyOnHide prop
  packages/devui-vue/devui/drawer/index.ts
  packages/devui-vue/devui/drawer/src/components/drawer-body.tsx
  packages/devui-vue/devui/drawer/src/components/drawer-container.tsx
  packages/devui-vue/devui/drawer/src/components/drawer-header.tsx
  packages/devui-vue/devui/drawer/src/drawer-service.tsx
  packages/devui-vue/devui/drawer/src/drawer-types.ts
  packages/devui-vue/devui/drawer/src/drawer.tsx
  packages/devui-vue/docs/components/drawer/index.md
Labels: PR: reviewed-approved
