Repository DevCloudFE/vue-devui, pull requests merged in 2022-06, with the labels that each got.

#803 feat(collapse): 搭建collapse基本Dom结构
  packages/devui-vue/devui/collapse/__tests__/collapse.spec.tsx
  packages/devui-vue/devui/collapse/index.ts
  packages/devui-vue/devui/collapse/src/collapse-item.tsx
  packages/devui-vue/devui/collapse/src/collapse-types.ts
  packages/devui-vue/devui/collapse/src/collapse.scss
  packages/devui-vue/devui/collapse/src/collapse.tsx
  packages/devui-vue/devui/collapse/src/const.ts
  packages/devui-vue/docs/components/collapse/index.md
Labels: PR: unreviewed, feature

#805 fix(virtual-list): 解决拖动滚动条卡死的问题
  packages/devui-vue/devui/virtual-list/src/virtual-list-types.ts
  packages/devui-vue/devui/virtual-list/src/virtual-list.tsx
Labels: enhancement, PR: unreviewed, PR: reviewed-approved

#813 feat(steps): 创建steps组件源码和文档的基本目录结构
  packages/devui-vue/devui-cli/templates/component.js
  packages/devui-vue/devui/steps/__tests__/steps.spec.tsx
  packages/devui-vue/devui/steps/index.ts
  packages/devui-vue/devui/steps/src/steps-types.ts
  packages/devui-vue/devui/steps/src/steps.scss
  packages/devui-vue/devui/steps/src/steps.tsx
  packages/devui-vue/docs/components/steps/index.md
Labels: PR: unreviewed, feature

#806 feat(tabs): tabs支持tabChange事件，tab支持closeable属性
  packages/devui-vue/devui/tabs/__tests__/tabs.spec.tsx
  packages/devui-vue/devui/tabs/src/components/tab-nav/composables/use-tab-nav-event.ts
  packages/devui-vue/devui/tabs/src/components/tab-nav/composables/use-tab-nav-function.ts
  packages/devui-vue/devui/tabs/src/components/tab-nav/tab-nav-types.ts
  packages/devui-vue/devui/tabs/src/components/tab-nav/tab-nav.tsx
  packages/devui-vue/devui/tabs/src/components/tab/tab-types.ts
  packages/devui-vue/devui/tabs/src/tabs-types.ts
  packages/devui-vue/devui/tabs/src/tabs.tsx
  packages/devui-vue/devui/tabs/src/use-tabs.ts
  packages/devui-vue/docs/components/tabs/index.md
Labels: PR: reviewed-approved, feature

#807 refactor(radio): refactor radio css
  packages/devui-vue/devui/radio/src/radio-button.scss
  packages/devui-vue/devui/radio/src/radio.scss
Labels: PR: reviewed-approved, refactoring

#808 refactor(checkbox): refactor checkbox css var
  packages/devui-vue/devui/checkbox/src/checkbox-button.scss
  packages/devui-vue/devui/checkbox/src/checkbox.scss
Labels: PR: reviewed-approved, refactoring

#811 feat(tag): add tag size
  packages/devui-vue/devui/tag/__tests__/tag.spec.ts
  packages/devui-vue/devui/tag/src/composables/use-class.ts
  packages/devui-vue/devui/tag/src/tag-types.ts
  packages/devui-vue/devui/tag/src/tag.scss
  packages/devui-vue/docs/components/tag/index.md
Labels: PR: reviewed-approved, feature

#814 chore: 添加styles-var的ls-lint依赖
  .ls-lint.yml
Labels: PR: unreviewed, refactoring

#816 feat(collapse): 添加slide up down transition
  packages/devui-vue/devui/collapse/index.ts
  packages/devui-vue/devui/collapse/src/collapse-item.tsx
  packages/devui-vue/devui/collapse/src/collapse-types.ts
  packages/devui-vue/devui/collapse/src/collapse.scss
  packages/devui-vue/devui/collapse/src/collapse.tsx
Labels: PR: unreviewed

#817 feat(select): 整改select组件单元测试用例
  packages/devui-vue/devui/select/__tests__/option.spec.tsx
  packages/devui-vue/devui/select/__tests__/select.spec.tsx
  packages/devui-vue/devui/select/index.ts
  packages/devui-vue/devui/select/src/composables/use-option.ts
Labels: PR: unreviewed

#820 test(tabs): 完善tabs测试用例
  packages/devui-vue/devui/tabs/__tests__/tabs.spec.tsx
Labels: PR: unreviewed, unit-test

#821 feat(Form): 增加disabled&size参数，已适配Input组件
  packages/devui-vue/devui/form/index.ts
  packages/devui-vue/devui/form/src/form-types.ts
  packages/devui-vue/devui/input/src/composables/use-input-render.ts
  packages/devui-vue/devui/input/src/input-types.tsx
  packages/devui-vue/devui/input/src/input.scss
  packages/devui-vue/devui/input/src/input.tsx
  packages/devui-vue/docs/components/form/index.md
Labels: PR: unreviewed, feature

#815 fix(tabs): 修复options类型的样式问题，修复custom-width属性不生效问题
  packages/devui-vue/devui/tabs/src/components/tab-nav/composables/use-tab-nav-render.ts
  packages/devui-vue/devui/tabs/src/components/tab-nav/tab-nav-types.ts
  packages/devui-vue/devui/tabs/src/components/tab-nav/tab-nav.scss
  packages/devui-vue/devui/tabs/src/components/tab-nav/tab-nav.tsx
  packages/devui-vue/docs/components/tabs/index.md
Labels: PR: unreviewed

#818 feat(switch): add active-value inactive-value
  packages/devui-vue/devui/switch/__tests__/switch.spec.ts
  packages/devui-vue/devui/switch/src/switch-types.ts
  packages/devui-vue/devui/switch/src/use-switch.ts
  packages/devui-vue/docs/components/switch/index.md
Labels: PR: unreviewed, feature

#826 fix(collapse): 修复demo文案
  packages/devui-vue/docs/components/collapse/index.md
Labels: PR: unreviewed

#827 refactor(switch): refactor switch docs
  packages/devui-vue/docs/components/switch/index.md
Labels: PR: unreviewed, ignore-for-release

#828 feat: Form集成Textarea组件，支持校验&disabled
  packages/devui-vue/devui/textarea/src/composables/use-textarea-event.ts
  packages/devui-vue/devui/textarea/src/composables/use-textarea-render.ts
  packages/devui-vue/devui/textarea/src/textarea-types.ts
  packages/devui-vue/devui/textarea/src/textarea.scss
  packages/devui-vue/devui/textarea/src/textarea.tsx
  packages/devui-vue/docs/components/form/index.md
Labels: PR: unreviewed, feature

#829 feat(Form): 集成Checkbox，增加disabled&size&校验
  packages/devui-vue/devui/checkbox/src/use-checkbox.ts
  packages/devui-vue/docs/components/form/index.md
Labels: PR: unreviewed, feature

#822 feat(steps): 基础步骤条组件
  packages/devui-vue/devui/steps/index.ts
  packages/devui-vue/devui/steps/src/const.ts
  packages/devui-vue/devui/steps/src/step-types.ts
  packages/devui-vue/devui/steps/src/step.scss
  packages/devui-vue/devui/steps/src/step.tsx
  packages/devui-vue/devui/steps/src/steps-types.ts
  packages/devui-vue/devui/steps/src/steps.scss
  packages/devui-vue/devui/steps/src/steps.tsx
  packages/devui-vue/docs/components/steps/index.md
Labels: PR: unreviewed, feature

#832 fix(input): 修复input、auto-complete插槽图标不对齐问题
  packages/devui-vue/devui/auto-complete/src/auto-complete.tsx
  packages/devui-vue/devui/input/src/input.tsx
Labels: bug, PR: unreviewed

#830 feat(tabs): 支持tab-position属性
  packages/devui-vue/devui/tabs/__tests__/tabs.spec.tsx
  packages/devui-vue/devui/tabs/src/components/tab-nav/composables/use-tab-nav-function.ts
  packages/devui-vue/devui/tabs/src/components/tab-nav/composables/use-tab-nav-render.ts
  packages/devui-vue/devui/tabs/src/components/tab-nav/tab-nav-types.ts
  packages/devui-vue/devui/tabs/src/components/tab-nav/tab-nav.scss
  packages/devui-vue/devui/tabs/src/components/tab-nav/tab-nav.tsx
  packages/devui-vue/devui/tabs/src/components/tab/tab.scss
  packages/devui-vue/devui/tabs/src/tabs-types.ts
  packages/devui-vue/devui/tabs/src/tabs.tsx
  packages/devui-vue/devui/tabs/src/use-tabs.ts
  packages/devui-vue/docs/components/tabs/index.md
Labels: PR: unreviewed, feature

#831 feat(Form): 集成Radio，增加disabled&size&校验
  packages/devui-vue/devui/radio/src/use-radio.ts
  packages/devui-vue/docs/components/form/index.md
Labels: PR: unreviewed, feature

#825 docs(grid): 使用css变量解决Grid组件组件黑暗主题下背景颜色错误
  packages/devui-vue/docs/components/grid/index.md
Labels: bug, PR: unreviewed, PR: reviewed-approved

#835 feat(Form): 集成Switch，支持disabled&size
  packages/devui-vue/devui/switch/src/switch-types.ts
  packages/devui-vue/devui/switch/src/switch.tsx
  packages/devui-vue/devui/switch/src/use-switch.ts
Labels: PR: unreviewed, feature

#837 feat(Form): 集成Select，支持disabled&size&校验结果
  packages/devui-vue/devui/select/src/components/select-content.tsx
  packages/devui-vue/devui/select/src/composables/use-select-content.ts
  packages/devui-vue/devui/select/src/select-types.ts
  packages/devui-vue/devui/select/src/select.scss
  packages/devui-vue/devui/select/src/select.tsx
  packages/devui-vue/devui/select/src/use-select.ts
  packages/devui-vue/docs/components/form/index.md
Labels: PR: unreviewed, feature

#839 feat(steps): add align-center and description
  packages/devui-vue/devui/steps/src/const.ts
  packages/devui-vue/devui/steps/src/step-types.ts
  packages/devui-vue/devui/steps/src/step.scss
  packages/devui-vue/devui/steps/src/step.tsx
  packages/devui-vue/devui/steps/src/steps-types.ts
  packages/devui-vue/devui/steps/src/steps.tsx
  packages/devui-vue/docs/components/steps/index.md
Labels: PR: unreviewed, feature

#838 feat(date-picker-pro): 搭建single input Dom
  packages/devui-vue/devui/date-picker-pro/index.ts
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro-types.ts
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro.scss
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro.tsx
  packages/devui-vue/devui/date-picker-pro/src/use-picker-pro.ts
  packages/devui-vue/docs/components/date-picker-pro/index.md
Labels: PR: unreviewed, feature

#843 fix(collapse): 修复折叠面板展开动画页面抖动
  packages/devui-vue/devui/collapse/src/collapse.scss
Labels: bug, PR: unreviewed

#842 refactor(menu): 使用命名空间重构class，修复vue警告
  packages/devui-vue/devui/menu/src/components/menu-item/menu-item.tsx
  packages/devui-vue/devui/menu/src/components/menu-item/use-menu-item.ts
  packages/devui-vue/devui/menu/src/components/sub-menu/sub-menu.tsx
  packages/devui-vue/devui/menu/src/components/sub-menu/use-sub-menu.ts
  packages/devui-vue/devui/menu/src/composables/use-click.ts
  packages/devui-vue/devui/menu/src/composables/use-layer-operate.ts
  packages/devui-vue/devui/menu/src/menu.tsx
  packages/devui-vue/devui/menu/src/styles/public.scss
  packages/devui-vue/devui/menu/src/styles/vertical.scss
  packages/devui-vue/docs/components/menu/index.md
Labels: PR: unreviewed, refactoring

#841 fix(Form): 修复resetField方法的问题
  packages/devui-vue/devui/form/src/components/form-item/use-form-item.ts
  packages/devui-vue/docs/components/form/index.md
Labels: bug, PR: unreviewed

#844 fix(tabs/menu): 修复tabs，menu文档问题
  packages/devui-vue/devui/menu/src/components/sub-menu/sub-menu-types.ts
  packages/devui-vue/devui/menu/src/components/sub-menu/sub-menu.tsx
  packages/devui-vue/devui/tabs/src/tabs.tsx
  packages/devui-vue/docs/.vitepress/devui-theme/styles/demo-block.scss
  packages/devui-vue/docs/components/menu/index.md
  packages/devui-vue/docs/components/select/index.md
  packages/devui-vue/docs/components/tabs/index.md
Labels: PR: reviewed-approved, refactoring

#847 feat(date-picker-pro): 添加日历面板DOM
  packages/devui-vue/devui/date-picker-pro/src/components/calendar-panel.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/date-picker-panel.tsx
  packages/devui-vue/devui/date-picker-pro/src/composables/use-calendar-panel.ts
  packages/devui-vue/devui/date-picker-pro/src/const.ts
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro-types.ts
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro.scss
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro.tsx
Labels: PR: unreviewed, feature

#846 fix(menu): 功能问题修复及优化
  packages/devui-vue/devui/menu/src/components/menu-item/menu-item.tsx
  packages/devui-vue/devui/menu/src/components/sub-menu/sub-menu.tsx
  packages/devui-vue/devui/menu/src/menu.tsx
  packages/devui-vue/devui/menu/src/styles/horizontal.scss
  packages/devui-vue/devui/menu/src/styles/public.scss
  packages/devui-vue/devui/menu/src/styles/vertical.scss
  packages/devui-vue/docs/components/menu/index.md
Labels: bug, PR: unreviewed

#849 test(menu): 完善测试用例，所有事件增加key传递
  packages/devui-vue/devui/menu/__tests__/menu.spec.ts
  packages/devui-vue/devui/menu/index.ts
  packages/devui-vue/devui/menu/src/components/menu-item/menu-item.tsx
  packages/devui-vue/devui/menu/src/components/sub-menu/sub-menu.tsx
  packages/devui-vue/docs/components/menu/index.md
Labels: PR: reviewed-approved, unit-test

#850 feat(date-picker-pro): 添加input显示选中的日期功能
  packages/devui-vue/devui/date-picker-pro/src/components/calendar-panel.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/date-picker-panel.tsx
  packages/devui-vue/devui/date-picker-pro/src/composables/use-calendar-panel.ts
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro-types.ts
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro.scss
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro.tsx
  packages/devui-vue/devui/date-picker-pro/src/use-picker-pro.ts
  packages/devui-vue/docs/components/date-picker-pro/index.md
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: PR: unreviewed

#852 style: 视觉刷新
  packages/devui-theme/src/theme-collection/extend-theme.ts
  packages/devui-vue/devui/badge/src/badge.scss
  packages/devui-vue/devui/rate/src/rate.scss
  packages/devui-vue/devui/styles-var/private/_color.scss
  packages/devui-vue/devui/switch/src/switch.scss
  packages/devui-vue/devui/textarea/src/textarea.scss
Labels: PR: unreviewed

#851 feat(menu): 支持router属性
  packages/devui-vue/devui/menu/src/components/menu-item/menu-item-types.ts
  packages/devui-vue/devui/menu/src/components/menu-item/menu-item.tsx
  packages/devui-vue/devui/menu/src/components/menu-item/use-menu-item.ts
  packages/devui-vue/devui/menu/src/menu-types.ts
  packages/devui-vue/devui/menu/src/menu.tsx
  packages/devui-vue/docs/components/menu/index.md
Labels: PR: reviewed-approved, feature

#853 feat(steps): step组件增加status属性
  packages/devui-vue/devui/steps/src/step-types.ts
  packages/devui-vue/devui/steps/src/step.scss
  packages/devui-vue/devui/steps/src/step.tsx
  packages/devui-vue/docs/components/steps/index.md
Labels: PR: unreviewed, feature

#855 feat(steps): steps增加simple属性以支持简洁模式
  packages/devui-vue/devui/steps/src/step.scss
  packages/devui-vue/devui/steps/src/step.tsx
  packages/devui-vue/devui/steps/src/steps-types.ts
  packages/devui-vue/devui/steps/src/steps.scss
  packages/devui-vue/devui/steps/src/steps.tsx
  packages/devui-vue/docs/components/steps/index.md
Labels: PR: unreviewed, feature

#856 feat(date-picker-pro): date-picker-pro添加日期选中功能
  packages/devui-vue/devui/date-picker-pro/src/components/calendar-panel.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/date-picker-panel.tsx
  packages/devui-vue/devui/date-picker-pro/src/composables/use-calendar-panel.ts
  packages/devui-vue/devui/date-picker-pro/src/const.ts
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro-types.ts
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro.scss
Labels: PR: unreviewed

#854 style(Slider): Slider视觉刷新
  packages/devui-theme/src/styles-var/devui-var.scss
  packages/devui-theme/src/theme-collection/extend-theme-vue.scss
  packages/devui-theme/src/theme-collection/extend-theme.ts
  packages/devui-vue/devui/button/src/button-group.scss
  packages/devui-vue/devui/button/src/button.scss
  packages/devui-vue/devui/checkbox/src/checkbox.scss
  packages/devui-vue/devui/input/src/input.scss
  packages/devui-vue/devui/radio/src/radio.scss
  packages/devui-vue/devui/search/src/search.scss
  packages/devui-vue/devui/slider/src/slider.scss
  packages/devui-vue/devui/styles-var/private/_color.scss
  packages/devui-vue/docs/components/button/index.md
Labels: PR: unreviewed

#858 feat(time-picker): add time-picker size format readonly
  packages/devui-vue/devui/time-picker/__tests__/time-picker.spec.ts
  packages/devui-vue/devui/time-picker/src/components/popup-line/composables/use-popup-line.ts
  packages/devui-vue/devui/time-picker/src/components/popup-line/index.tsx
  packages/devui-vue/devui/time-picker/src/components/time-popup/index.scss
  packages/devui-vue/devui/time-picker/src/components/time-popup/index.tsx
  packages/devui-vue/devui/time-picker/src/composables/use-time-picker.ts
  packages/devui-vue/devui/time-picker/src/time-picker-types.ts
  packages/devui-vue/devui/time-picker/src/time-picker.scss
  packages/devui-vue/devui/time-picker/src/time-picker.tsx
  packages/devui-vue/devui/time-picker/src/types.ts
  packages/devui-vue/devui/time-picker/src/utils.ts
  packages/devui-vue/docs/components/time-picker/index.md
Labels: PR: unreviewed, feature

#857 fix(tree): 如果是叶子结点，不需要尝试获取子节点，以提升性能
  packages/devui-vue/devui/tree/src/composables/use-core.ts
Labels: PR: unreviewed

#859 style(Statistic): 重构样式命名，移除value-style参数
  packages/devui-vue/devui/statistic/src/statistic-types.ts
  packages/devui-vue/devui/statistic/src/statistic.scss
  packages/devui-vue/devui/statistic/src/statistic.tsx
  packages/devui-vue/docs/components/statistic/index.md
Labels: PR: unreviewed, refactoring

#860 feat(date-picker-pro): 实现单个日期选择时间功能
  packages/devui-vue/devui/date-picker-pro/src/components/calendar-panel.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/date-picker-panel.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/time-picker-panel.tsx
  packages/devui-vue/devui/date-picker-pro/src/composables/use-calendar-panel.ts
  packages/devui-vue/devui/date-picker-pro/src/composables/use-date-picker.ts
  packages/devui-vue/devui/date-picker-pro/src/composables/use-time-picker-panel.ts
  packages/devui-vue/devui/date-picker-pro/src/const.ts
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro-types.ts
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro.scss
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro.tsx
  packages/devui-vue/devui/date-picker-pro/src/use-picker-pro.ts
  packages/devui-vue/docs/components/date-picker-pro/index.md
Labels: PR: unreviewed

#861 feat(badge): 支持hidden属性
  packages/devui-vue/devui/badge/__tests__/badge.spec.ts
  packages/devui-vue/devui/badge/src/badge-types.ts
  packages/devui-vue/devui/badge/src/badge.scss
  packages/devui-vue/devui/badge/src/badge.tsx
  packages/devui-vue/docs/components/badge/index.md
Labels: PR: unreviewed

#863 fix(Search): 修复点击清空按钮时不会触发search事件的问题
  packages/devui-vue/devui/search/src/composables/use-search-keywords.ts
Labels: bug, PR: unreviewed

#862 feat(card): 支持shadow属性
  packages/devui-vue/devui/card/__tests__/__snapshots__/card.spec.ts.snap
  packages/devui-vue/devui/card/__tests__/card.spec.ts
  packages/devui-vue/devui/card/src/card-types.ts
  packages/devui-vue/devui/card/src/card.scss
  packages/devui-vue/devui/card/src/card.tsx
  packages/devui-vue/docs/components/card/index.md
Labels: PR: unreviewed, feature

#864 refactor(Slider): 重构代码结构&移除非必要部分
  packages/devui-vue/devui/shared/utils/is.ts
  packages/devui-vue/devui/slider/__tests__/slider.spec.ts
  packages/devui-vue/devui/slider/__tests__/slider.spec.tsx
  packages/devui-vue/devui/slider/src/slider-types.ts
  packages/devui-vue/devui/slider/src/slider.scss
  packages/devui-vue/devui/slider/src/slider.tsx
  packages/devui-vue/devui/slider/src/use-slider.ts
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
  packages/devui-vue/docs/components/slider/index.md
Labels: bug, PR: unreviewed, refactoring

#865 feat(upload): 支持limit属性，支持on-exceed钩子函数
  packages/devui-vue/devui/upload/__tests__/upload.spec.ts
  packages/devui-vue/devui/upload/src/upload-types.ts
  packages/devui-vue/devui/upload/src/upload.scss
  packages/devui-vue/devui/upload/src/upload.tsx
  packages/devui-vue/docs/components/upload/index.md
Labels: PR: unreviewed, feature

#869 feat(upload): 支持auto-upload属性，支持on-change钩子函数，支持submit和clearFiles方法
  packages/devui-vue/devui/upload/__tests__/upload.spec.ts
  packages/devui-vue/devui/upload/src/upload-types.ts
  packages/devui-vue/devui/upload/src/upload.tsx
  packages/devui-vue/docs/components/upload/index.md
Labels: PR: unreviewed, feature

#877 fix(jest-config): 把jest.config文件样式还原
  packages/devui-vue/jest.config.js
Labels: PR: reviewed-approved, ignore-for-release

#875 feat(upload): 支持http-request属性
  packages/devui-vue/devui/upload/__tests__/upload.spec.ts
  packages/devui-vue/devui/upload/src/upload-types.ts
  packages/devui-vue/devui/upload/src/upload.tsx
  packages/devui-vue/docs/components/upload/index.md
Labels: PR: reviewed-approved, feature

#876 test(tree): 添加单元测试
  packages/devui-vue/devui/tree/__tests__/basic-tree/basic-tree-data.ts
  packages/devui-vue/devui/tree/__tests__/basic-tree/basic-tree.spec.tsx
  packages/devui-vue/devui/tree/__tests__/checkable-tree/checkable-tree-data.ts
  packages/devui-vue/devui/tree/__tests__/checkable-tree/checkable-tree.spec.tsx
  packages/devui-vue/devui/tree/__tests__/node-merge/node-merge-data.ts
  packages/devui-vue/devui/tree/__tests__/node-merge/node-merge.spec.tsx
Labels: PR: reviewed-approved, unit-test

#878 fix(select): 修复多选取消选择问题
  packages/devui-vue/devui/select/src/use-select.ts
Labels: PR: unreviewed

#879 test(tree): 添加单元测试
  packages/devui-vue/devui/tree/__tests__/basic-tree/basic-tree.spec.tsx
  packages/devui-vue/devui/tree/__tests__/checkable-tree/checkable-tree.spec.tsx
Labels: PR: reviewed-approved, unit-test

#881 feat(date-picker-pro): 添加date-picker-pro单元测试用例
  packages/devui-vue/devui/date-picker-pro/__tests__/date-picker-pro.spec.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/calendar-panel.tsx
  packages/devui-vue/devui/date-picker-pro/src/composables/use-calendar-panel.ts
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro.tsx
Labels: PR: reviewed-approved, unit-test

#880 feat(select): 支持multiple-limit属性和toggleChange方法
  packages/devui-vue/devui/select/__tests__/select.spec.tsx
  packages/devui-vue/devui/select/src/select-types.ts
  packages/devui-vue/devui/select/src/select.tsx
  packages/devui-vue/devui/select/src/use-select.ts
  packages/devui-vue/docs/components/select/index.md
Labels: PR: reviewed-approved, feature

#882 docs: 完善贡献者信息
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
Labels: documentation, PR: unreviewed, ignore-for-release

#883 feat(docs): 增加主题切换器
  packages/devui-vue/docs/.vitepress/devui-theme/components/NavBar.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/ThemePicker.vue
  packages/devui-vue/docs/.vitepress/devui-theme/styles/layout.scss
Labels: documentation, PR: unreviewed

#884 fix(tree): 修复可勾选功能错误、修复一些eslint错误、补充单元测试
  packages/devui-vue/devui/tree/__tests__/checkable-tree/checkable-tree.spec.tsx
  packages/devui-vue/devui/tree/index.ts
  packages/devui-vue/devui/tree/src/components/tree-node.tsx
  packages/devui-vue/devui/tree/src/composables/use-check.ts
  packages/devui-vue/devui/tree/src/tree-types.ts
  packages/devui-vue/devui/tree/src/tree.tsx
  packages/devui-vue/devui/tree/src/utils.ts
Labels: bug, PR: unreviewed, PR: reviewed-approved, unit-test

#887 feat(date-picker-pro): range-date-picker-pro add utils
  packages/devui-vue/devui/date-picker-pro/__tests__/date-picker-pro.spec.tsx
  packages/devui-vue/devui/date-picker-pro/__tests__/range-date-picker-pro.spec.tsx
Labels: PR: reviewed-approved, unit-test

#890 fix(table): trackBy应为非必选
  packages/devui-vue/devui/table/src/components/column/config.tsx
  packages/devui-vue/devui/table/src/store/index.ts
  packages/devui-vue/devui/table/src/store/store-types.ts
  packages/devui-vue/devui/table/src/table-types.ts
  packages/devui-vue/docs/components/table/index.md
Labels: bug, PR: unreviewed

#885 style(editable-select): 重构样式为BEM风格
  packages/devui-vue/devui/editable-select/__tests__/editable-select.spec.ts
  packages/devui-vue/devui/editable-select/src/composables/use-cache-filtered-options.ts
  packages/devui-vue/devui/editable-select/src/composables/use-input.ts
  packages/devui-vue/devui/editable-select/src/composables/use-keyboard-select.ts
  packages/devui-vue/devui/editable-select/src/editable-select.scss
  packages/devui-vue/devui/editable-select/src/editable-select.tsx
Labels: PR: reviewed-approved, refactoring

#888 feat(table): check-change和check-all-change回调参数增加所有选中行数据
  packages/devui-vue/devui/table/src/components/column/config.tsx
  packages/devui-vue/docs/components/table/index.md
Labels: PR: reviewed-approved, feature

#894 feat(table): 支持toggleRowSelection方法，补充说明文档
  packages/devui-vue/devui/table/src/store/index.ts
  packages/devui-vue/devui/table/src/store/store-types.ts
  packages/devui-vue/devui/table/src/table-types.ts
  packages/devui-vue/docs/components/table/index.md
Labels: PR: reviewed-approved, feature

#895 feat(tree): 增加getCheckedNodes方法
  packages/devui-vue/devui/tree/src/composables/use-check.ts
  packages/devui-vue/devui/tree/src/composables/use-tree-types.ts
Labels: PR: unreviewed, feature

#898 test(table): 补充表格方法的测试用例
  packages/devui-vue/devui/table/__tests__/table.spec.tsx
Labels: PR: reviewed-approved, unit-test

#899 fix(select): 修复select组件 valueChange 事件的回调参数问题
  packages/devui-vue/devui/select/src/composables/use-option.ts
  packages/devui-vue/devui/select/src/select-types.ts
  packages/devui-vue/devui/select/src/use-select.ts
  packages/devui-vue/docs/components/select/index.md
Labels: bug, PR: unreviewed, PR: reviewed-approved

#900 feat(table): 删除trackBy属性，统一为rowKey属性，修复column事件报错问题
  packages/devui-vue/devui/table/__tests__/table.spec.tsx
  packages/devui-vue/devui/table/src/components/column/use-column.ts
  packages/devui-vue/devui/table/src/store/index.ts
  packages/devui-vue/devui/table/src/table-types.ts
  packages/devui-vue/devui/table/src/utils.ts
  packages/devui-vue/docs/components/table/index.md
Labels: PR: reviewed-approved, feature

#901 feat(transfer): add render-content
  packages/devui-vue/devui/transfer/__tests__/transfer.spec.ts
  packages/devui-vue/devui/transfer/src/components/transfer-body.tsx
  packages/devui-vue/devui/transfer/src/components/transfer-panel.tsx
  packages/devui-vue/devui/transfer/src/composables/use-transfer-body.ts
  packages/devui-vue/devui/transfer/src/composables/use-transfer-header.ts
  packages/devui-vue/devui/transfer/src/composables/use-transfer-panel.ts
  packages/devui-vue/devui/transfer/src/composables/use-transfer.ts
  packages/devui-vue/devui/transfer/src/transfer-types.ts
  packages/devui-vue/devui/transfer/src/transfer.scss
  packages/devui-vue/devui/transfer/src/transfer.tsx
  packages/devui-vue/docs/components/transfer/index.md
Labels: PR: reviewed-approved, feature

#909 refactor(time-picker): refactor time-picker class
  packages/devui-vue/devui/time-picker/src/components/popup-line/index.tsx
  packages/devui-vue/devui/time-picker/src/components/time-popup/index.scss
  packages/devui-vue/devui/time-picker/src/components/time-popup/index.tsx
  packages/devui-vue/devui/time-picker/src/components/time-scroll/index.tsx
  packages/devui-vue/devui/time-picker/src/time-picker.tsx
Labels: PR: reviewed-approved, refactoring

#908 feat(tree): 增加operate属性以支持增删改操作
  packages/devui-vue/devui/tree/src/components/tree-node.tsx
  packages/devui-vue/devui/tree/src/components/use-tree-node.ts
  packages/devui-vue/devui/tree/src/composables/use-operate.ts
  packages/devui-vue/devui/tree/src/composables/use-tree-types.ts
  packages/devui-vue/devui/tree/src/tree-types.ts
  packages/devui-vue/devui/tree/src/tree.scss
  packages/devui-vue/devui/tree/src/tree.tsx
  packages/devui-vue/docs/components/tree/index.md
Labels: PR: unreviewed, feature

#912 docs(virtual-list): 新增文档
  packages/devui-vue/docs/components/virtual-list/index.md
Labels: documentation, PR: unreviewed, PR: reviewed-approved

#913 chore: 更新组件进度状态
  packages/devui-vue/devui-cli/shared/constant.js
  packages/devui-vue/devui/date-picker-pro/index.ts
  packages/devui-vue/devui/dropdown/index.ts
  packages/devui-vue/devui/menu/index.ts
  packages/devui-vue/devui/select/index.ts
  packages/devui-vue/devui/steps/index.ts
  packages/devui-vue/devui/table/index.ts
  packages/devui-vue/devui/tabs/index.ts
  packages/devui-vue/devui/time-picker/index.ts
  packages/devui-vue/devui/tooltip/index.ts
  packages/devui-vue/devui/transfer/index.ts
  packages/devui-vue/devui/tree/index.ts
  packages/devui-vue/docs/.vitepress/devui-theme/Layout.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/SideBarLink.js
Labels: PR: unreviewed, ignore-for-release

#915 feat(date-picker-pro): 添加form控制属性及校验样式
  packages/devui-vue/devui/date-picker-pro/src/components/range-date-picker-pro.tsx
  packages/devui-vue/devui/date-picker-pro/src/composables/use-calendar-panel.ts
  packages/devui-vue/devui/date-picker-pro/src/composables/use-date-picker.ts
  packages/devui-vue/devui/date-picker-pro/src/composables/use-range-date-picker-pro.ts
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro-types.ts
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro.scss
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro.tsx
  packages/devui-vue/devui/date-picker-pro/src/range-date-picker-types.ts
  packages/devui-vue/devui/date-picker-pro/src/use-picker-pro.ts
  packages/devui-vue/devui/icon/src/icon.tsx
  packages/devui-vue/docs/components/form/index.md
Labels: PR: reviewed-approved, feature

#916 feat(date-picker-pro): 添加calenderRange、limitDateRange属性
  packages/devui-vue/devui/date-picker-pro/__tests__/date-picker-pro.spec.tsx
  packages/devui-vue/devui/date-picker-pro/__tests__/range-date-picker-pro.spec.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/calendar-panel.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/date-picker-panel.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/range-date-picker-pro.tsx
  packages/devui-vue/devui/date-picker-pro/src/composables/use-calendar-panel.ts
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro-types.ts
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro.scss
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro.tsx
  packages/devui-vue/devui/date-picker-pro/src/range-date-picker-types.ts
  packages/devui-vue/docs/components/date-picker-pro/index.md
Labels: PR: reviewed-approved, feature

#914 fix(upload): 修复输入框样式高度问题
  packages/devui-vue/devui/upload/src/upload.scss
Labels: bug, PR: unreviewed, PR: reviewed-approved

#919 fix(date-picker-pro): 解决date-picker-pro组件props代码重复问题、input框内部高度问题
  packages/devui-vue/devui/date-picker-pro/src/components/date-picker-panel.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/range-date-picker-pro.tsx
  packages/devui-vue/devui/date-picker-pro/src/composables/use-calendar-panel.ts
  packages/devui-vue/devui/date-picker-pro/src/composables/use-date-picker.ts
  packages/devui-vue/devui/date-picker-pro/src/composables/use-range-date-picker-pro.ts
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro-types.ts
  packages/devui-vue/devui/date-picker-pro/src/date-picker-pro.tsx
  packages/devui-vue/devui/date-picker-pro/src/range-date-picker-types.ts
  packages/devui-vue/devui/date-picker-pro/src/use-picker-pro.ts
  packages/devui-vue/devui/input/src/input.scss
Labels: bug, PR: unreviewed, PR: reviewed-approved, refactoring

#921 fix(input/icon): 修复input的input事件，修复icon的点击事件
  packages/devui-vue/devui/icon/src/icon.tsx
  packages/devui-vue/devui/input/__tests__/input.spec.ts
  packages/devui-vue/devui/input/src/composables/use-input-event.ts
Labels: bug, PR: reviewed-approved

#926 chore(input-number): 修复eslint报错
  packages/devui-vue/devui/input-number/src/input-number-types.ts
  packages/devui-vue/devui/input-number/src/use-input-number.ts
Labels: PR: reviewed-approved, refactoring

#920 fix: 使用精确定时器
  packages/devui-vue/devui/countdown/src/countdown.tsx
  packages/devui-vue/devui/countdown/src/utils.ts
  packages/devui-vue/docs/components/countdown/index.md
Labels: PR: reviewed-approved, refactoring

#928 fix(Modal): 修复弹窗关闭按钮样式 (#918)
  packages/devui-vue/devui/modal/src/modal.scss
Labels: bug, PR: unreviewed, PR: reviewed-approved

#935 feat(i18n): 初版组件国际化
  packages/devui-vue/devui/locale/create.ts
  packages/devui-vue/devui/locale/index.ts
  packages/devui-vue/devui/locale/lang/en-US.ts
  packages/devui-vue/devui/locale/lang/en-us.ts
  packages/devui-vue/devui/locale/lang/zh-CN.ts
  packages/devui-vue/devui/locale/lang/zh-cn.ts
  packages/devui-vue/devui/pagination/src/pagination-types.ts
  packages/devui-vue/devui/pagination/src/pagination.tsx
  packages/devui-vue/devui/shared/utils/deep-assign.ts
  packages/devui-vue/docs/.vitepress/devui-theme/components/NavBar.vue
  packages/devui-vue/docs/.vitepress/theme/index.ts
Labels: PR: unreviewed, feature

#930 feat(table): 树形表格样式优化，其他功能问题修复
  packages/devui-vue/devui/modal/src/modal.scss
  packages/devui-vue/devui/table/__tests__/table.spec.tsx
  packages/devui-vue/devui/table/src/components/column/column-types.ts
  packages/devui-vue/devui/table/src/components/column/column.scss
  packages/devui-vue/devui/table/src/components/column/config.tsx
  packages/devui-vue/devui/table/src/components/column/use-column.ts
  packages/devui-vue/devui/table/src/composables/use-table.ts
  packages/devui-vue/docs/components/table/index.md
Labels: bug, PR: unreviewed, PR: reviewed-approved, refactoring

#933 style(accordion): 修复eslint报错
  packages/devui-vue/devui/accordion/index.ts
  packages/devui-vue/devui/accordion/src/accordion-item-hreflink.tsx
  packages/devui-vue/devui/accordion/src/accordion-item-routerlink.tsx
  packages/devui-vue/devui/accordion/src/accordion-item.tsx
  packages/devui-vue/devui/accordion/src/accordion-list.tsx
  packages/devui-vue/devui/accordion/src/accordion-menu.tsx
  packages/devui-vue/devui/accordion/src/accordion-open-icon.tsx
  packages/devui-vue/devui/accordion/src/accordion-types.ts
  packages/devui-vue/devui/accordion/src/accordion.tsx
  packages/devui-vue/devui/accordion/src/accordion.type.ts
  packages/devui-vue/devui/accordion/src/utils.ts
Labels: PR: reviewed-approved, refactoring
