Repository DevCloudFE/vue-devui, pull requests merged in 2022-12, with the labels that each got.

#1464 fix(.github): 修复无法自动生成release_note的问题
  .github/workflows/auto-publish-npm.yml
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1465 chore: update version
  packages/devui-vue/package.json
Labels: PR: unreviewed, ignore-for-release

#1466 chore: update version
  packages/devui-vue/devui-cli/commands/release.js
  packages/devui-vue/package.json
Labels: PR: unreviewed, ignore-for-release

#1467 chore: release v1.3.3
  packages/devui-vue/package.json
Labels: PR: unreviewed, ignore-for-release

#1460 fix: 修复form组件文档校验出错 (#1454)
  packages/devui-vue/docs/components/form/index.md
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1472 fix: theme props type warning
  packages/devui-vue/docs/.vitepress/devui-theme/components/NavBar.vue
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1478 docs(form): 组件文档尺寸，增加 size 切换。
  packages/devui-vue/docs/components/form/index.md
Labels: documentation, PR: unreviewed

#1482 fix(select): 修复 select 组件 size 属性的逻辑 （#1199）
  packages/devui-vue/devui/select/__tests__/select.spec.tsx
  packages/devui-vue/devui/select/src/select-types.ts
  packages/devui-vue/devui/select/src/use-select.ts
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1483 fix(date-picker-pro): 修复date-picker-pro测试用例报错
  packages/devui-vue/devui/date-picker-pro/__tests__/date-picker-pro.spec.tsx
  packages/devui-vue/devui/date-picker-pro/__tests__/range-date-picker-pro.spec.tsx
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1484 style(algolia): 组件文档 algolia 检索主题适配
  packages/devui-vue/docs/.vitepress/devui-theme/components/AlgoliaSearchBox.vue
Labels: enhancement, PR: unreviewed, PR: reviewed-approved

#1485 chore: auto create a tag
  .github/workflows/auto-publish.yml
  packages/devui-vue/package.json
Labels: enhancement, PR: unreviewed

#1488 chore: fix release failed
  .github/workflows/auto-publish.yml
  packages/devui-vue/package.json
Labels: PR: unreviewed, ignore-for-release

#1489 chore: fix release failed
  .github/workflows/auto-publish.yml
  packages/devui-vue/package.json
Labels: PR: unreviewed, ignore-for-release

#1490 chore: fix release failed
  .github/workflows/auto-publish.yml
  packages/devui-vue/package.json
Labels: PR: unreviewed, ignore-for-release

#1496 timePicker组件 props size 在表单内部时应该跟随表单变化
  packages/devui-vue/devui/time-picker/__tests__/time-picker.spec.ts
  packages/devui-vue/devui/time-picker/src/time-picker-types.ts
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1494 timeSelect 组件 props size 在表单内部时应该跟随表单变化
  packages/devui-vue/devui/time-select/__tests__/time-select.spec.ts
  packages/devui-vue/devui/time-select/src/time-select-types.ts
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1495 form 文档 size 示例，增加 timeSelect、timePicker。
  packages/devui-vue/docs/components/form/index.md
Labels: documentation, PR: reviewed-approved

#1504 update version to v1.4.0
  .github/workflows/auto-publish.yml
  packages/devui-vue/package.json
Labels: PR: unreviewed, ignore-for-release

#1505 feat: release v1.4.0
  .github/workflows/auto-publish.yml
  packages/devui-vue/package.json
Labels: PR: unreviewed, ignore-for-release

#1509 test(icon): improve icon test case
  packages/devui-vue/devui/icon/__tests__/icon.spec.ts
  packages/devui-vue/devui/icon/__tests__/icon.spec.tsx
Labels: PR: reviewed-approved, unit-test

#1511 fix(tabs): fix content of tab has not changed when add a tab
  packages/devui-vue/devui/tabs/src/components/tab-nav/tab-nav.tsx
  packages/devui-vue/docs/components/tabs/index.md
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1514 fix(modal): 修复弹窗组件信息提示图标的颜色
  packages/devui-vue/devui/modal/src/modal.tsx
Labels: bug, PR: unreviewed

#1515 chore: release v1.4.1
  packages/devui-vue/package.json
Labels: PR: unreviewed, ignore-for-release
