Repository DevCloudFE/vue-devui, pull requests merged in 2023-03, with the labels that each got.

#1552 release v1.5.3
  README.md
  README.zh-CN.md
  packages/devui-vue/devui/image-preview/src/image-preview-directive.ts
  packages/devui-vue/package.json
Labels: PR: unreviewed, ignore-for-release

#1553 release v1.5.3
  README.md
  README.zh-CN.md
  packages/devui-vue/devui/image-preview/src/image-preview-directive.ts
  packages/devui-vue/package.json
Labels: PR: unreviewed, ignore-for-release

#1560 feat: 弹窗中新增autofocus自动聚焦
  packages/devui-vue/devui/modal/__tests__/modal.spec.tsx
  packages/devui-vue/devui/modal/src/modal.tsx
  packages/devui-vue/docs/components/modal/index.md
Labels: PR: reviewed-approved

#1561 fix: 修改eslint单行太长问题,对ts类型报红完善
  packages/devui-vue/devui/image-preview/src/image-preview-directive.ts
  packages/devui-vue/devui/image-preview/src/image-preview-service.ts
  packages/devui-vue/tsconfig.json
Labels: PR: reviewed-approved

#1563 Revert "release v1.5.4"
  README.md
  README.zh-CN.md
  packages/devui-vue/devui/image-preview/src/image-preview-directive.ts
  packages/devui-vue/devui/image-preview/src/image-preview-service.ts
  packages/devui-vue/devui/modal/__tests__/modal.spec.tsx
  packages/devui-vue/devui/modal/src/modal.tsx
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
  packages/devui-vue/docs/components/modal/index.md
  packages/devui-vue/package.json
  packages/devui-vue/tsconfig.json
  pnpm-lock.yaml
Labels: PR: unreviewed

#1564 release v1.5.4
  README.md
  README.zh-CN.md
  packages/devui-vue/devui/image-preview/src/image-preview-directive.ts
  packages/devui-vue/devui/image-preview/src/image-preview-service.ts
  packages/devui-vue/devui/modal/__tests__/modal.spec.tsx
  packages/devui-vue/devui/modal/src/modal.tsx
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
  packages/devui-vue/docs/components/modal/index.md
  packages/devui-vue/package.json
  packages/devui-vue/tsconfig.json
  pnpm-lock.yaml
Labels: PR: unreviewed, ignore-for-release

#1565 release v1.5.3
  packages/devui-vue/package.json
Labels: PR: unreviewed, ignore-for-release
