Repository DevCloudFE/vue-devui, pull requests merged in 2023-01, with the labels that each got.

#1517 fix(collapse): 修复折叠面板禁用时图标颜色
  packages/devui-vue/devui/collapse/src/collapse.scss
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1519 fix(time-picker): fix test case not pass
  packages/devui-vue/devui/time-picker/__tests__/time-picker.spec.ts
Labels: PR: reviewed-approved, unit-test

#1518 test(textarea、dropdown): improve test case
  packages/devui-vue/devui/dropdown/__tests__/dropdown.spec.tsx
  packages/devui-vue/devui/textarea/__tests__/textarea.spec.ts
Labels: PR: reviewed-approved, unit-test

#1523 release v1.5.0
  .eslintrc.js
  package.json
  packages/devui-vue/devui/collapse/src/collapse.scss
  packages/devui-vue/devui/dropdown/__tests__/dropdown.spec.tsx
  packages/devui-vue/devui/editable-select/src/components/dropdown/dropdown.tsx
  packages/devui-vue/devui/editable-select/src/composables/use-input-event.ts
  packages/devui-vue/devui/editable-select/src/composables/use-select.ts
  packages/devui-vue/devui/textarea/__tests__/textarea.spec.ts
  packages/devui-vue/devui/time-picker/__tests__/time-picker.spec.ts
  packages/devui-vue/docs/.vitepress/config/markdown.ts
  packages/devui-vue/docs/.vitepress/demo/Demo.vue
  packages/devui-vue/docs/.vitepress/demo/DemoBlock.vue
  packages/devui-vue/docs/.vitepress/plugins/block-plugin.ts
  packages/devui-vue/docs/.vitepress/theme/register-components.js
  packages/devui-vue/docs/.vitepress/utils/highlight.ts
  packages/devui-vue/docs/.vitepress/utils/parseInstruct.ts
  packages/devui-vue/docs/.vitepress/utils/utils.ts
  packages/devui-vue/docs/components/button/buttonGroup.vue
  packages/devui-vue/docs/components/button/disable.vue
  packages/devui-vue/docs/components/button/icon.vue
  packages/devui-vue/docs/components/button/index.md
  packages/devui-vue/docs/components/button/loading.vue
  packages/devui-vue/docs/components/button/shape.vue
  packages/devui-vue/docs/components/button/size.vue
  packages/devui-vue/docs/components/button/theme.vue
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: PR: unreviewed, ignore-for-release

#1527 docs: update contributors
  README.md
  README.zh-CN.md
Labels: PR: unreviewed, ignore-for-release

#1529 fix(ImagePreview): 修复图片拖动并重置，再次拖动时的位置问题
  packages/devui-vue/devui/image-preview/src/transform.ts
Labels: bug, PR: unreviewed, PR: partially-approved

#1532 feat: 1524 组件demo中，点击复制代码片段之后，文字消失问题解决
  packages/devui-vue/docs/.vitepress/config/lang.ts
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1533 chore(site): add current version number to the top nav bar
  packages/devui-vue/docs/.vitepress/config/nav.ts
Labels: documentation, PR: unreviewed

#1537 fix: the demo description is not rendered #1534
  packages/devui-vue/docs/.vitepress/demo/Demo.vue
Labels: PR: reviewed-approved

#1541 fix(menu): 修复#1540问题
  packages/devui-vue/devui/menu/src/composables/use-click.ts
  packages/devui-vue/devui/menu/src/composables/use-layer-operate.ts
Labels: PR: reviewed-approved

#1542 fix: 修复default-select-keys无法响应式的问题 #1542
  packages/devui-vue/devui/menu/src/components/menu-item/menu-item.tsx
  packages/devui-vue/devui/menu/src/menu.tsx
  packages/devui-vue/docs/components/menu/index.md
  pnpm-lock.yaml
Labels: bug, PR: unreviewed, PR: reviewed-approved

#1543 fix(tag): 修复Tag标签primary类型选中状态下，关闭按钮颜色与背景色一致 (close #1539)
  packages/devui-vue/devui/tag/src/tag.tsx
Labels: bug, PR: reviewed-approved

#1544 release v1.5.1
  .github/workflows/preview-build.yml
  README.md
  README.zh-CN.md
  packages/devui-vue/devui/image-preview/src/transform.ts
  packages/devui-vue/devui/menu/src/components/menu-item/menu-item.tsx
  packages/devui-vue/devui/menu/src/composables/use-click.ts
  packages/devui-vue/devui/menu/src/composables/use-layer-operate.ts
  packages/devui-vue/devui/menu/src/menu.tsx
  packages/devui-vue/devui/tag/src/tag.tsx
  packages/devui-vue/docs/.vitepress/config/lang.ts
  packages/devui-vue/docs/.vitepress/config/nav.ts
  packages/devui-vue/docs/.vitepress/demo/Demo.vue
  packages/devui-vue/docs/.vitepress/plugins/block-plugin.ts
  packages/devui-vue/docs/.vitepress/plugins/md-transformer.ts
  packages/devui-vue/docs/components/menu/index.md
  packages/devui-vue/docs/vite.config.ts
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: PR: unreviewed, ignore-for-release
