Repository DevCloudFE/vue-devui, pull requests merged in 2023-10, with the labels that each got.

#1754 refactor(markdown): 默认工具栏添加checkbox不加入list语法
  packages/devui-vue/devui/editor-md/src/toolbar-config.ts
  packages/devui-vue/docs/components/dragdrop/index.md
  packages/devui-vue/docs/components/editor-md/checkbox.vue
Labels: refactoring

#1755 refactor(markdown): highlightjs更新使用@11
  packages/devui-vue/devui/editor-md/src/composables/md-render-service.ts
  packages/devui-vue/package.json
Labels: refactoring

#1757 feat: 官网视觉优化
  packages/devui-vue/docs/.vitepress/devui-theme/Layout.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/AlgoliaSearchBox.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/DevuiFooter.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/HomeHero.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/Page.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributor.vue
  packages/devui-vue/docs/.vitepress/devui-theme/components/ThemePicker.vue
  packages/devui-vue/docs/assets/banner-bg-dark.png
  packages/devui-vue/docs/assets/banner-bg.png
  packages/devui-vue/docs/assets/banner-decorate.png
Labels: feature

#1758 fix: 左侧目录不展示gitgraph
  packages/devui-vue/docs/.vitepress/devui-theme/styles/sidebar-links.scss
Labels: bug
