Repository DevCloudFE/vue-devui, pull requests merged in 2023-07, with the labels that each got.

#1588 feat(Breadcrumb): 新增面包屑组件
  packages/devui-vue/devui/breadcrumb/index.ts
Labels: feature

#1587 feat: 添加codeEditor组件
  packages/devui-vue/devui/code-editor/index.ts
  packages/devui-vue/devui/code-editor/src/code-editor-types.ts
  packages/devui-vue/devui/code-editor/src/code-editor.scss
  packages/devui-vue/devui/code-editor/src/code-editor.tsx
  packages/devui-vue/devui/code-editor/src/composables/use-code-editor.ts
  packages/devui-vue/docs/components/code-editor/index.md
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: feature

#1589 release v1.5.4-alpha.0
  packages/devui-vue/devui/breadcrumb/index.ts
  packages/devui-vue/devui/code-editor/index.ts
  packages/devui-vue/devui/code-editor/src/code-editor-types.ts
  packages/devui-vue/devui/code-editor/src/code-editor.scss
  packages/devui-vue/devui/code-editor/src/code-editor.tsx
  packages/devui-vue/devui/code-editor/src/composables/use-code-editor.ts
  packages/devui-vue/devui/drawer/__tests__/drawer.spec.tsx
  packages/devui-vue/devui/input-number/__tests__/input-number.spec.tsx
  packages/devui-vue/devui/input/__tests__/input.spec.ts
  packages/devui-vue/devui/menu/__tests__/menu.spec.ts
  packages/devui-vue/devui/menu/src/components/menu-item/menu-item.tsx
  packages/devui-vue/devui/menu/src/components/menu-item/use-menu-item.ts
  packages/devui-vue/devui/menu/src/menu.tsx
  packages/devui-vue/devui/select/src/use-select.ts
  packages/devui-vue/devui/tree/src/composables/use-operate.ts
  packages/devui-vue/docs/components/code-editor/index.md
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: ignore-for-release

#1590 fix: 修改构建报错
  packages/devui-vue/devui/code-editor/src/code-editor.tsx
  packages/devui-vue/devui/code-editor/src/composables/use-code-editor.ts
Labels: ignore-for-release

#1591 release v1.5.4-alpha.0
  packages/devui-vue/devui/code-editor/src/code-editor.tsx
  packages/devui-vue/devui/code-editor/src/composables/use-code-editor.ts
Labels: ignore-for-release

#1594 fix: 优化文档内容
  packages/devui-vue/docs/components/code-editor/index.md
  packages/devui-vue/docs/components/editable-select/index.md
  packages/devui-vue/docs/components/modal/index.md
  packages/devui-vue/docs/components/tag/index.md
  packages/devui-vue/docs/en-US/components/editable-select/index.md
  packages/devui-vue/docs/en-US/components/modal/index.md
Labels: documentation, ignore-for-release

#1596 feat(ActionTimeline): 新增操作时间轴组件
  packages/devui-vue/devui-cli/shared/constant.js
  packages/devui-vue/devui/action-timeline/index.ts
  packages/devui-vue/devui/action-timeline/src/action-timeline-types.ts
  packages/devui-vue/devui/action-timeline/src/action-timeline.scss
  packages/devui-vue/devui/action-timeline/src/action-timeline.tsx
  packages/devui-vue/docs/components/action-timeline/index.md
  packages/devui-vue/docs/components/code-editor/index.md
Labels: feature

#1600 fix: 修改代码编辑器组件所属分类
  packages/devui-vue/devui/code-editor/index.ts
  packages/devui-vue/package.json
Labels: ignore-for-release

#1602 feat(Carousel): 新增走马灯组件
  packages/devui-vue/devui/carousel/index.ts
Labels: feature

#1603 feat(CodeReview): 新增代码检视组件(演进中)
  packages/devui-vue/devui/code-review/index.ts
  packages/devui-vue/devui/code-review/src/code-review-types.ts
  packages/devui-vue/devui/code-review/src/code-review.scss
  packages/devui-vue/devui/code-review/src/code-review.tsx
  packages/devui-vue/devui/code-review/src/composables/use-code-review.ts
  packages/devui-vue/docs/components/code-review/index.md
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: feature, ignore-for-release

#1604 feat: 添加markdown编辑器组件
  packages/devui-vue/devui/editor-md/index.ts
  packages/devui-vue/devui/editor-md/src/assets/editor.scss
  packages/devui-vue/devui/editor-md/src/components/font-color.tsx
  packages/devui-vue/devui/editor-md/src/components/font-size.tsx
  packages/devui-vue/devui/editor-md/src/components/md-render.tsx
  packages/devui-vue/devui/editor-md/src/components/toolbar-item.tsx
  packages/devui-vue/devui/editor-md/src/components/toolbar.scss
  packages/devui-vue/devui/editor-md/src/components/toolbar.tsx
  packages/devui-vue/devui/editor-md/src/composables/helper.ts
  packages/devui-vue/devui/editor-md/src/composables/md-render-service.ts
  packages/devui-vue/devui/editor-md/src/composables/use-editor-md-render.ts
  packages/devui-vue/devui/editor-md/src/composables/use-editor-md-theme.ts
  packages/devui-vue/devui/editor-md/src/composables/use-editor-md-toolbar.ts
  packages/devui-vue/devui/editor-md/src/composables/use-editor-md.ts
  packages/devui-vue/devui/editor-md/src/editor-md-types.ts
  packages/devui-vue/devui/editor-md/src/editor-md.scss
  packages/devui-vue/devui/editor-md/src/editor-md.tsx
  packages/devui-vue/devui/editor-md/src/icons-config.ts
  packages/devui-vue/devui/editor-md/src/plugins/mermaid.ts
  packages/devui-vue/devui/editor-md/src/plugins/toc.ts
  packages/devui-vue/devui/editor-md/src/toolbar-config.ts
  packages/devui-vue/devui/editor-md/src/utils.ts
  packages/devui-vue/docs/components/editor-md/index.md
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: feature

#1605 fix: 修改版本号
  packages/devui-vue/devui-cli/commands/build.js
  packages/devui-vue/devui/editor-md/src/components/font-color.tsx
  packages/devui-vue/devui/editor-md/src/components/font-size.tsx
  packages/devui-vue/devui/editor-md/src/components/md-render.tsx
  packages/devui-vue/devui/editor-md/src/components/toolbar-item.tsx
  packages/devui-vue/devui/editor-md/src/components/toolbar.tsx
  packages/devui-vue/devui/editor-md/src/composables/use-editor-md-render.ts
  packages/devui-vue/devui/editor-md/src/composables/use-editor-md.ts
  packages/devui-vue/devui/editor-md/src/editor-md-types.ts
  packages/devui-vue/devui/editor-md/src/editor-md.tsx
  packages/devui-vue/devui/editor-md/src/plugins/toc.ts
  packages/devui-vue/devui/editor-md/src/toolbar-config.ts
  packages/devui-vue/docs/components/editor-md/index.md
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: ignore-for-release

#1606 feat(Grid): 新增noOuter参数，抵消外层边距
  packages/devui-vue/devui/grid/src/grid-types.ts
  packages/devui-vue/devui/grid/src/row.tsx
  packages/devui-vue/docs/components/grid/index.md
Labels: feature

#1607 release 1.5.5
  packages/devui-vue/devui-cli/commands/build.js
  packages/devui-vue/devui/carousel/index.ts
  packages/devui-vue/devui/code-review/index.ts
  packages/devui-vue/devui/code-review/src/code-review-types.ts
  packages/devui-vue/devui/code-review/src/code-review.scss
  packages/devui-vue/devui/code-review/src/code-review.tsx
  packages/devui-vue/devui/code-review/src/composables/use-code-review.ts
  packages/devui-vue/devui/editor-md/index.ts
  packages/devui-vue/devui/editor-md/src/assets/editor.scss
  packages/devui-vue/devui/editor-md/src/components/font-color.tsx
  packages/devui-vue/devui/editor-md/src/components/font-size.tsx
  packages/devui-vue/devui/editor-md/src/components/md-render.tsx
  packages/devui-vue/devui/editor-md/src/components/toolbar-item.tsx
  packages/devui-vue/devui/editor-md/src/components/toolbar.scss
  packages/devui-vue/devui/editor-md/src/components/toolbar.tsx
  packages/devui-vue/devui/editor-md/src/composables/helper.ts
  packages/devui-vue/devui/editor-md/src/composables/md-render-service.ts
  packages/devui-vue/devui/editor-md/src/composables/use-editor-md-render.ts
  packages/devui-vue/devui/editor-md/src/composables/use-editor-md-theme.ts
  packages/devui-vue/devui/editor-md/src/composables/use-editor-md-toolbar.ts
  packages/devui-vue/devui/editor-md/src/composables/use-editor-md.ts
  packages/devui-vue/devui/editor-md/src/editor-md-types.ts
  packages/devui-vue/devui/editor-md/src/editor-md.scss
  packages/devui-vue/devui/editor-md/src/editor-md.tsx
  packages/devui-vue/devui/editor-md/src/icons-config.ts
  packages/devui-vue/devui/editor-md/src/plugins/mermaid.ts
  packages/devui-vue/devui/editor-md/src/plugins/toc.ts
  packages/devui-vue/devui/editor-md/src/toolbar-config.ts
  packages/devui-vue/devui/editor-md/src/utils.ts
  packages/devui-vue/devui/grid/src/grid-types.ts
  packages/devui-vue/devui/grid/src/row.tsx
  packages/devui-vue/docs/components/code-review/index.md
  packages/devui-vue/docs/components/editor-md/index.md
  packages/devui-vue/docs/components/grid/index.md
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: ignore-for-release

#1608 fix: 解决构建问题
  packages/devui-vue/devui-cli/commands/build.js
  packages/devui-vue/devui/editor-md/src/editor-md.scss
  packages/devui-vue/devui/editor-md/src/editor-md.tsx
Labels: ignore-for-release

#1610 fix: 暂时不开放英文网站访问
  packages/devui-vue/devui/alert/src/components/alert-close-icon.tsx
  packages/devui-vue/devui/alert/src/components/alert-type-icon.tsx
  packages/devui-vue/devui/avatar/src/components/icon-body.tsx
  packages/devui-vue/devui/avatar/src/components/icon-nobody.tsx
  packages/devui-vue/devui/collapse/src/collapse-open-icon.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/icon-calendar.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/icon-close.tsx
  packages/devui-vue/devui/form/src/components/form-icons.tsx
  packages/devui-vue/devui/image-preview/src/image-preview.tsx
  packages/devui-vue/devui/input-number/src/input-number-icons.tsx
  packages/devui-vue/devui/notification/src/notification-icons.tsx
  packages/devui-vue/devui/pagination/src/components/page-link-icons.tsx
  packages/devui-vue/devui/popover/src/popover-icons.tsx
  packages/devui-vue/devui/rate/src/rate.tsx
  packages/devui-vue/devui/search/src/components/search-close-icon.tsx
  packages/devui-vue/devui/search/src/components/search-icon.tsx
  packages/devui-vue/devui/select/src/components/select-arrow-icon.tsx
  packages/devui-vue/devui/skeleton/src/components/image-icon.tsx
  packages/devui-vue/docs/.vitepress/devui-theme/Layout.vue
Labels: ignore-for-release

#1612 feat: 添加design token文档
  packages/devui-vue/devui-cli/shared/constant.js
  packages/devui-vue/devui-cli/templates/vitepress-sidebar.js
  packages/devui-vue/docs/components/design-animation/index.md
  packages/devui-vue/docs/components/design-color/index.md
  packages/devui-vue/docs/components/design-font/index.md
  packages/devui-vue/docs/components/design-link/index.md
  packages/devui-vue/docs/components/design-radius/index.md
  packages/devui-vue/docs/components/design-shadow/index.md
  packages/devui-vue/docs/components/design-zindex/index.md
Labels: documentation

#1613 feat: 添加dCharts组件
  packages/devui-vue/devui/echarts/index.ts
  packages/devui-vue/devui/echarts/src/echarts-theme.ts
  packages/devui-vue/devui/echarts/src/echarts-types.ts
  packages/devui-vue/devui/echarts/src/echarts.tsx
  packages/devui-vue/docs/components/echarts/index.md
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: feature

#1614 feat(form): form-item增加label插槽
  packages/devui-vue/devui/form/src/components/form-item/form-item.tsx
  packages/devui-vue/docs/components/form/index.md
Labels: feature

#1615 fix: 修改版本号
  packages/devui-vue/devui-cli/commands/build.js
  packages/devui-vue/package.json
Labels: ignore-for-release

#1616 release 1.5.6
  packages/devui-vue/devui-cli/commands/build.js
  packages/devui-vue/devui-cli/shared/constant.js
  packages/devui-vue/devui-cli/templates/vitepress-sidebar.js
  packages/devui-vue/devui/alert/src/components/alert-close-icon.tsx
  packages/devui-vue/devui/alert/src/components/alert-type-icon.tsx
  packages/devui-vue/devui/avatar/src/components/icon-body.tsx
  packages/devui-vue/devui/avatar/src/components/icon-nobody.tsx
  packages/devui-vue/devui/collapse/src/collapse-open-icon.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/icon-calendar.tsx
  packages/devui-vue/devui/date-picker-pro/src/components/icon-close.tsx
  packages/devui-vue/devui/echarts/index.ts
  packages/devui-vue/devui/echarts/src/echarts-theme.ts
  packages/devui-vue/devui/echarts/src/echarts-types.ts
  packages/devui-vue/devui/echarts/src/echarts.tsx
  packages/devui-vue/devui/form/src/components/form-icons.tsx
  packages/devui-vue/devui/form/src/components/form-item/form-item.tsx
  packages/devui-vue/devui/image-preview/src/image-preview.tsx
  packages/devui-vue/devui/input-number/src/input-number-icons.tsx
  packages/devui-vue/devui/notification/src/notification-icons.tsx
  packages/devui-vue/devui/pagination/src/components/page-link-icons.tsx
  packages/devui-vue/devui/popover/src/popover-icons.tsx
  packages/devui-vue/devui/rate/src/rate.tsx
  packages/devui-vue/devui/search/src/components/search-close-icon.tsx
  packages/devui-vue/devui/search/src/components/search-icon.tsx
  packages/devui-vue/devui/select/src/components/select-arrow-icon.tsx
  packages/devui-vue/devui/skeleton/src/components/image-icon.tsx
  packages/devui-vue/docs/.vitepress/devui-theme/Layout.vue
  packages/devui-vue/docs/components/design-animation/index.md
  packages/devui-vue/docs/components/design-color/index.md
  packages/devui-vue/docs/components/design-font/index.md
  packages/devui-vue/docs/components/design-link/index.md
  packages/devui-vue/docs/components/design-radius/index.md
  packages/devui-vue/docs/components/design-shadow/index.md
  packages/devui-vue/docs/components/design-zindex/index.md
  packages/devui-vue/docs/components/echarts/index.md
  packages/devui-vue/docs/components/form/index.md
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: ignore-for-release

#1618 feat(CodeReview): 新增折叠能力
  packages/devui-theme/src/theme/theme-data.ts
  packages/devui-vue/devui-cli/commands/build.js
  packages/devui-vue/devui/code-review/src/code-review-types.ts
  packages/devui-vue/devui/code-review/src/code-review.scss
  packages/devui-vue/devui/code-review/src/code-review.tsx
  packages/devui-vue/devui/code-review/src/components/code-review-header.tsx
  packages/devui-vue/devui/code-review/src/components/code-review-icons.tsx
  packages/devui-vue/devui/code-review/src/composables/use-code-review-header.ts
  packages/devui-vue/devui/code-review/src/composables/use-code-review.ts
  packages/devui-vue/devui/shared/utils/index.ts
  packages/devui-vue/devui/shared/utils/to-clipboard.ts
  packages/devui-vue/devui/styles-var/private/_color.scss
  packages/devui-vue/devui/styles-var/private/_corner.scss
  packages/devui-vue/devui/styles-var/private/_shadow.scss
  packages/devui-vue/docs/components/code-review/index.md
  packages/devui-vue/package.json
Labels: feature

#1620 feat: 增加md demo与mode参数
  packages/devui-vue/devui/editor-md/src/composables/use-editor-md-render.ts
  packages/devui-vue/devui/editor-md/src/editor-md.scss
  packages/devui-vue/docs/components/editor-md/index.md
Labels: feature

#1621 feat: design tokens&&主题化变量值更新
  packages/devui-theme/src/styles-var/devui-var.scss
  packages/devui-theme/src/styles-var/private/_animation.scss
  packages/devui-theme/src/styles-var/private/_basic.scss
  packages/devui-theme/src/styles-var/private/_color.scss
  packages/devui-theme/src/styles-var/private/_corner.scss
  packages/devui-theme/src/styles-var/private/_font-size.scss
  packages/devui-theme/src/styles-var/private/_shadow.scss
  packages/devui-theme/src/styles-var/private/_z-index.scss
  packages/devui-theme/src/theme-collection/extend-theme.ts
  packages/devui-theme/src/theme-collection/theme-custom-components-data.ts
  packages/devui-theme/src/theme-collection/theme-initial-data.ts
  packages/devui-theme/src/theme/theme-data.ts
  packages/devui-vue/devui/styles-var/private/_color.scss
  packages/devui-vue/devui/styles-var/private/_font.scss
  packages/devui-vue/devui/styles-var/private/_shadow.scss
Labels: ignore-for-release

#1624 feat: 误删除组件变量恢复
  packages/devui-vue/devui/styles-var/private/_color.scss
  packages/devui-vue/devui/styles-var/private/_font.scss
Labels: ignore-for-release

#1625 feat(code-editor): add highlight directive
  packages/devui-vue/devui/code-editor/index.ts
  packages/devui-vue/devui/code-editor/src/code-highlight-directive.ts
  packages/devui-vue/docs/components/code-editor/index.md
Labels: feature

#1626 fix: 修改版本号
  packages/devui-vue/devui/code-review/src/code-review.scss
  packages/devui-vue/devui/code-review/src/code-review.tsx
  packages/devui-vue/package.json
  pnpm-lock.yaml
Labels: ignore-for-release

#1627 fix(Theme): 修复主题导出问题
  package.json
  packages/devui-theme/package.json
  packages/devui-theme/scripts/release.js
  scripts.json
Labels: ignore-for-release
