Repository DevCloudFE/vue-devui, pull requests merged in 2023-08, with the labels that each got.

#1628 fix(code-editor): v-model change not work
  packages/devui-vue/devui/code-editor/src/composables/use-code-editor.ts
Labels: bug

#1629 fix: 修改版本号
  packages/devui-vue/package.json
Labels: ignore-for-release

#1630 fix: 修复构建报错
  packages/devui-theme/package.json
Labels: ignore-for-release

#1631 fix(code-editor): some spelling bugs
  packages/devui-vue/devui/code-editor/src/composables/use-code-editor.ts
Labels: bug

#1633 fix: 修改版本号
  packages/devui-vue/devui/alert/src/components/alert-close-icon.tsx
  packages/devui-vue/devui/alert/src/components/alert-type-icon.tsx
  packages/devui-vue/package.json
Labels: ignore-for-release

#1634 feat: 新增图片上传示例demo
  packages/devui-vue/docs/components/upload/index.md
Labels: documentation

#1636 fix(code-editor): v-mode update not work
  packages/devui-vue/devui/code-editor/src/code-editor-types.ts
  packages/devui-vue/devui/code-editor/src/code-editor.tsx
  packages/devui-vue/devui/code-editor/src/composables/use-code-editor.ts
Labels: bug

#1637 Xingyan/fix version
  packages/devui-vue/devui/avatar/src/components/icon-body.tsx
  packages/devui-vue/devui/avatar/src/components/icon-nobody.tsx
  packages/devui-vue/package.json
Labels: ignore-for-release

#1647 feat:增加git_graph组件
  packages/devui-vue/devui/git-graph/index.ts
  packages/devui-vue/devui/git-graph/src/git-graph-class.ts
  packages/devui-vue/devui/git-graph/src/git-graph-types.ts
  packages/devui-vue/devui/git-graph/src/git-graph.tsx
  packages/devui-vue/devui/git-graph/src/use-git-graph.ts
  packages/devui-vue/docs/components/git-graph/index.md
Labels: feature

#1640 fix: 使用搜索后有//#刷新页面页面空白的问题 #1619
  packages/devui-vue/docs/.vitepress/devui-theme/components/AlgoliaSearchBox.vue
Labels: documentation

#1649 feat(CodeReview): 增加代码高亮功能
  packages/devui-vue/devui/code-review/src/code-review.scss
  packages/devui-vue/devui/code-review/src/code-review.tsx
  packages/devui-vue/devui/code-review/src/composables/use-code-review-comment.ts
  packages/devui-vue/devui/code-review/src/composables/use-code-review-fold.ts
  packages/devui-vue/devui/code-review/src/composables/use-code-review.ts
  packages/devui-vue/docs/components/code-review/index.md
Labels: feature

#1648 feat(Modal): Modal添加close监听事件
  packages/devui-vue/devui/modal/src/composables/use-modal.ts
  packages/devui-vue/devui/modal/src/modal-types.ts
  packages/devui-vue/devui/modal/src/modal.tsx
  packages/devui-vue/docs/components/modal/index.md
Labels: feature

#1654 feat(md): code block render add overflow-x style
  packages/devui-vue/devui/editor-md/src/editor-md.scss
Labels: feature

#1652 feat(CodeReview): line-by-line模式支持评论功能
  packages/devui-vue/devui/code-review/src/code-review-types.ts
  packages/devui-vue/devui/code-review/src/code-review.scss
  packages/devui-vue/devui/code-review/src/code-review.tsx
  packages/devui-vue/devui/code-review/src/composables/use-code-review-expand.ts
  packages/devui-vue/devui/code-review/src/composables/use-code-review.ts
  packages/devui-vue/devui/code-review/src/utils.ts
  packages/devui-vue/docs/components/code-review/index.md
Labels: feature

#1650 Jmy/feat form splitter
  packages/devui-vue/devui/form/src/components/form-label/form-label.scss
  packages/devui-vue/devui/form/src/components/form-label/use-form-label.ts
  packages/devui-vue/devui/form/src/form-types.ts
  packages/devui-vue/devui/splitter/src/components/splitter-pane.tsx
  packages/devui-vue/docs/components/form/index.md
  packages/devui-vue/docs/components/splitter/index.md
Labels: feature

#1655 feat: 新增拖拽组件
  packages/devui-vue/devui/dragdrop/index.ts
  packages/devui-vue/devui/dragdrop/src/const.ts
  packages/devui-vue/devui/dragdrop/src/draggable-directive.ts
  packages/devui-vue/devui/dragdrop/src/droppable-directive.ts
  packages/devui-vue/devui/dragdrop/src/sortable-directive.ts
  packages/devui-vue/devui/dragdrop/src/utils.ts
  packages/devui-vue/docs/.vitepress/devui-theme/components/PageContributorConfig.ts
  packages/devui-vue/docs/components/dragdrop/index.md
Labels: feature

#1656 fix: 修改版本号
  packages/devui-vue/package.json
Labels: ignore-for-release

#1658 feat(CodeReview): 支持side-by-side模式
  packages/devui-vue/devui/code-review/src/code-review-types.ts
  packages/devui-vue/devui/code-review/src/code-review.scss
  packages/devui-vue/devui/code-review/src/code-review.tsx
  packages/devui-vue/devui/code-review/src/composables/use-code-review-comment.ts
  packages/devui-vue/devui/code-review/src/composables/use-code-review-expand.ts
  packages/devui-vue/devui/code-review/src/composables/use-code-review.ts
  packages/devui-vue/devui/code-review/src/const.ts
  packages/devui-vue/devui/code-review/src/utils.ts
  packages/devui-vue/docs/.vitepress/theme/index.ts
  packages/devui-vue/docs/components/code-editor/index.md
  packages/devui-vue/docs/components/code-review/index.md
Labels: feature

#1668 fix: 修改版本号
  packages/devui-vue/package.json
Labels: ignore-for-release

#1657 feat(md): add image-upload-to-server api
  packages/devui-vue/devui/editor-md/src/composables/use-editor-md.ts
  packages/devui-vue/devui/editor-md/src/editor-md.tsx
  packages/devui-vue/devui/editor-md/src/toolbar-config.ts
  packages/devui-vue/docs/components/editor-md/index.md
Labels: feature

#1714 feat(CodeReview): 提供diff类型参数
  packages/devui-vue/devui/code-review/src/code-review-types.ts
  packages/devui-vue/devui/code-review/src/code-review.scss
  packages/devui-vue/devui/code-review/src/code-review.tsx
  packages/devui-vue/devui/code-review/src/components/code-review-header.tsx
  packages/devui-vue/docs/components/code-review/index.md
Labels: feature

#1715 fix(CodeEditor): 修复更新v-model失效问题
  packages/devui-vue/devui/code-editor/src/composables/use-code-editor.ts
Labels: bug
